import type { CountryTranslation } from "@/lib/i18n/translation";

const STATES_AND_TERRITORIES = [
  "New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Northern Territory",
  "Australian Capital Territory",
].map((name) => ({ name }));

/** English translation of data/australie — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "e0b1417dcdba",
  capital: "Canberra",
  geography: {
    headline: "An isolated island continent between the Indian and Pacific oceans, the flattest and driest inhabited continent, with no land borders",
    areaKm2: {
      note: "The world's sixth-largest country by area; includes Tasmania but not the external territories."
    },
    coastlineKm: {
      note: "Coastline of the mainland and Tasmania; a further 23,860 km or so of island coastline (nearby islands and external territories) can be added."
    },
    highestPoint: {
      name: "Mount Kosciuszko"
    },
    borderingCountries: [],
    climate: "Highly varied, from the tropical north (monsoons, cyclones) to the temperate south, across a vast arid to semi-arid interior covering more than a third of the territory. With average national rainfall of about 419 mm a year, Australia is the driest inhabited continent after Antarctica.",
    summary: "An island continent that shares no land border with any other country, Australia is dominated at its centre by the Outback, a vast, arid and very sparsely populated region of deserts (Great Sandy Desert, Gibson Desert) and iconic landforms such as Uluru. The Great Dividing Range runs along the east coast for nearly 4,000 km, while the Great Barrier Reef, the largest coral structure in the world, stretches for more than 2,300 km off Queensland. Most of the population lives on a narrow coastal fringe, mainly in the east, south-east and south-west."
  },
  population: {
    total: {
      note: "Estimate as of December 31, 2025."
    },
    density: {
      note: "One of the lowest national densities in the world, and very misleading: most of the territory, which is desert, is virtually uninhabited."
    },
    growthRate: {
      note: "Net migration accounts for about three-quarters of annual population growth, far above the average for developed countries."
    },
    urbanShare: {
      note: "The population is highly concentrated in a handful of large coastal cities (Sydney, Melbourne, Brisbane, Perth, Adelaide), while the interior remains almost empty."
    },
    summary: "Australia is one of the fastest-growing developed countries by population, driven by very high net immigration. About one in four inhabitants was born abroad, one of the highest rates among major economies. Aboriginal and Torres Strait Islander peoples, the continent's first inhabitants, make up about 3.2% of the total population (2.9% Aboriginal and 0.3% Torres Strait Islander according to the 2021 census)."
  },
  languages: {
    entries: [
      {
        name: "English",
        sharePercent: {
          note: "Share of residents who speak only English at home."
        },
        note: "The country's de facto language, but without official status in the Constitution or a federal law."
      },
      {
        name: "Mandarin",
        note: "The most spoken language at home after English, reflecting the importance of Chinese immigration."
      },
      {
        name: "Arabic"
      },
      {
        name: "Vietnamese"
      },
      {
        name: "Aboriginal and Torres Strait Islander languages",
        sharePercent: {
          note: "About 77,000 recorded speakers, across more than 160 distinct languages."
        },
        note: "Of the 250 to 300 or so languages spoken before colonisation, the vast majority are now extinct or severely endangered; Kriol and Yumplatok (Torres Strait Creole) are among the most widely spoken."
      }
    ],
    summary: "English overwhelmingly dominates public and private life without formal official status, a fairly common situation among English-speaking countries. The country nevertheless remains deeply multilingual because of immigration: nearly a quarter of the population speaks a language other than English at home, led by Mandarin, Arabic and Vietnamese. The Aboriginal linguistic heritage, rich in several hundred languages before 1788, was severely weakened by colonisation and survives today as living languages in only a limited number of communities, mainly in the Northern Territory."
  },
  religion: {
    surveyName: "Census of Population and Housing",
    ageScope: "Total population answering the optional religion question",
    points: [
      {
        label: "Christianity (all denominations)"
      },
      {
        label: "No religion"
      },
      {
        label: "Islam"
      },
      {
        label: "Hinduism"
      },
      {
        label: "Buddhism"
      },
      {
        label: "Other religions and not stated"
      }
    ],
    summary: "Australia is secularising rapidly: the share of the population reporting no religion has more than doubled since 2001 and, as early as the 2016 census, overtook Catholics as the largest single group. Catholicism (about 20% of the population) remains the largest Christian denomination, ahead of Anglicanism. Immigration has also greatly diversified the religious landscape, with steadily growing Muslim, Hindu and Buddhist communities.",
    methodologyNote: "The religion question is optional in the Australian census, which explains a significant share of unstated answers, grouped here with the remaining minority religions."
  },
  politics: {
    stateForm: "Federal constitutional monarchy",
    regime: "Westminster-style parliamentary democracy",
    headOfState: {
      title: "King",
      name: "Charles III",
      since: "September 8, 2022"
    },
    headOfGovernment: {
      title: "Prime Minister",
      name: "Anthony Albanese",
      since: "May 23, 2022"
    },
    legislature: {
      name: "Parliament of Australia",
      chambers: [
        {
          name: "House of Representatives"
        },
        {
          name: "Senate"
        }
      ]
    },
    constitution: {
      adopted: "January 1, 1901 (entry into force of the Constitution of the Commonwealth of Australia at Federation)"
    },
    summary: "Australia is a federal constitutional monarchy: King Charles III, also sovereign of the United Kingdom and the other Commonwealth realms, is represented day to day by a Governor-General — Sam Mostyn since July 2024 — who exercises nearly all constitutional functions in his name, on the advice of the government of the day. The Prime Minister, leader of the party holding the confidence of the House of Representatives, heads the federal government, whose powers are shared with six states and two mainland territories with their own executives. A referendum on becoming a republic was rejected in 1999 (54.9% No), and Australia has since remained tied to the British Crown, though fully sovereign since the Australia Act of 1986, which ended the last constitutional and judicial links with London."
  },
  economy: {
    currency: {
      name: "Australian dollar"
    },
    gdp: {
      note: "Current US dollars, estimate — the world's 12th-largest economy by nominal GDP."
    },
    gdpPerCapita: {
      note: "Current US dollars, estimate — one of the highest GDPs per capita in the world."
    },
    unemploymentRate: {
      note: "March 2026; unemployment among 15- to 24-year-olds remains markedly higher, at around 10%."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry (including mining)"
      },
      {
        name: "Agriculture"
      }
    ],
    indicators: [
      {
        label: "Largest trading partner",
        value: {
          value: "China",
          note: "About 30% of Australian exports, mostly iron ore, coal and liquefied natural gas."
        }
      }
    ],
    summary: "A developed, high-income economy, Australia earns a considerable share of its external wealth from exporting raw materials — iron ore, coal, liquefied natural gas, gold and, to a lesser extent, uranium — mainly to Asia and above all to China. The service sector (finance, international education, tourism) dominates employment and domestic value added. The country enjoyed nearly three decades of uninterrupted growth between the early 1990s and the Covid-19 pandemic, an exceptional performance among developed economies, driven in particular by Chinese demand for raw materials."
  },
  history: {
    intro: "A few milestones to place the major stages in the building of the modern country — not an exhaustive summary of Australian history, which is already widely documented elsewhere.",
    periods: [
      {
        title: "Aboriginal settlement and British colonisation",
        summary: "The continent has been inhabited for some 50,000 to 65,000 years by Aboriginal peoples and, in the Torres Strait, by the Torres Strait Islanders, organised into hundreds of nations with distinct languages and cultures. After the British explorer James Cook claimed the east coast for Great Britain in 1770, the First Fleet, commanded by Captain Arthur Phillip, landed at Sydney Cove on January 26, 1788 and founded a penal colony: some 162,000 convicts would be transported there until 1868. Colonisation relied on the doctrine of \"terra nullius\" (land belonging to no one), which denied any pre-existing Aboriginal sovereignty and paved the way for the dispossession of land and lasting frontier violence against Indigenous peoples throughout the 19th century.",
        events: [
          {
            date: "January 26, 1788",
            title: "Arrival of the First Fleet at Sydney Cove",
            description: "Captain Arthur Phillip founds the penal colony of New South Wales, the first permanent British settlement on the continent."
          }
        ]
      },
      {
        title: "Federation and the world wars",
        summary: "The six British colonies united on January 1, 1901 to form the Commonwealth of Australia, with a Westminster-style federal constitution. That same year, the Immigration Restriction Act introduced the \"White Australia policy\", which restricted non-European immigration until it was gradually dismantled between 1966 and 1973. Australia's part in the First World War, marked by the deadly Gallipoli landing in 1915, forged a strong national narrative around the ANZAC (Australian and New Zealand Army Corps), commemorated every April 25. The country fought alongside the Allies again in the Second World War, notably in the Pacific after the Japanese bombing of Darwin in 1942.",
        events: [
          {
            date: "January 1, 1901",
            title: "Federation of the Commonwealth of Australia",
            description: "Australia's six British colonies (New South Wales, Victoria, Queensland, South Australia, Western Australia, Tasmania) unite into a federal state."
          },
          {
            date: "April 25, 1915",
            title: "Gallipoli landing",
            description: "ANZAC troops (Australia and New Zealand) suffer heavy losses landing on the Gallipoli peninsula (Ottoman Empire); the date becomes the national ANZAC Day of remembrance."
          }
        ]
      },
      {
        title: "Mass immigration and first Indigenous recognition",
        summary: "The post-war period was marked by a massive immigration programme, at first European and then, after the White Australia policy was dismantled between 1966 and 1973, increasingly Asian, which lastingly turned Australian society into one of the most multicultural in the world. For Indigenous Australians, the referendum of May 27, 1967, approved by 90.8% of voters, gave the federal Parliament power to legislate for Aboriginal people and ended their exclusion from the census; the High Court's Mabo decision in 1992 formally rejected the doctrine of \"terra nullius\" and recognised the existence of native title predating colonisation. The country successfully hosted the Sydney Olympic Games in 2000, while a 1999 referendum on becoming a republic was rejected by 54.9% of voters.",
        events: [
          {
            date: "May 27, 1967",
            title: "Referendum on Aboriginal Australians",
            description: "90.8% of voters approve two constitutional amendments giving the federal Parliament power to legislate for Aboriginal people and ending their exclusion from population counts."
          },
          {
            date: "June 3, 1992",
            title: "Mabo decision",
            description: "The High Court of Australia rejects the doctrine of \"terra nullius\" and recognises for the first time the existence of Indigenous land title predating British colonisation."
          },
          {
            date: "November 6, 1999",
            title: "Republic referendum",
            description: "54.9% of voters reject the proposal to replace the monarch and the Governor-General with a president appointed by Parliament; Australia remains a constitutional monarchy."
          }
        ]
      },
      {
        title: "Reconciliation and contemporary Australia",
        summary: "Between the late 19th century and the 1970s, tens of thousands of Aboriginal and Torres Strait Islander children — estimates vary, with the 1997 official report citing at least 100,000 children over several generations — were forcibly removed from their families by the authorities and religious missions as part of assimilation policies; they are known as the \"Stolen Generations\". The \"Bringing Them Home\" report, published in 1997 after a national inquiry, documented this policy, before Prime Minister Kevin Rudd delivered an official apology to Parliament on behalf of the Australian state on February 13, 2008. More recently, on October 14, 2023, a referendum proposing to enshrine an Indigenous advisory body to Parliament in the Constitution (the \"Voice to Parliament\") was rejected nationally by 60.1% of voters to 39.9%, and failed to win a majority in any of the six states.",
        events: [
          {
            date: "1997",
            title: "\"Bringing Them Home\" report",
            description: "The Australian Human Rights Commission publishes the report of the national inquiry into the forced separation of Aboriginal and Torres Strait Islander children from their families."
          },
          {
            date: "February 13, 2008",
            title: "Official apology to the Stolen Generations",
            description: "Prime Minister Kevin Rudd delivers an official apology in the House of Representatives for the policies that led to the forced removal of Indigenous children from their families."
          },
          {
            date: "October 14, 2023",
            title: "\"Voice to Parliament\" referendum",
            description: "Voters reject, by 60.1% to 39.9%, the creation of an Indigenous advisory body enshrined in the Constitution; the proposal fails to win a majority in any state."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Heritage",
        title: "Sydney Opera House",
        description: "Designed by Danish architect Jørn Utzon and opened in 1973 after a ten-year delay and a huge budget overrun, the Sydney Opera House, known for its precast concrete shells covered with more than a million tiles, has been a UNESCO World Heritage site since 2007 and hosts more than 1,800 performances a year."
      },
      {
        category: "Aboriginal heritage and spirituality",
        title: "Uluru and Anangu culture",
        description: "This 348-metre-high sandstone monolith in the Northern Territory is a sacred site for the Aboriginal Anangu people, to whom ownership of the site was returned in 1985 before it was leased back to the state for 99 years. Climbing the rock, long tolerated despite Anangu opposition, has been banned since October 26, 2019."
      },
      {
        category: "Nature",
        title: "The Great Barrier Reef",
        description: "The largest coral ecosystem in the world, it stretches for more than 2,300 km off Queensland and is home to exceptional marine biodiversity, but suffers recurring coral bleaching events linked to warming waters."
      },
      {
        category: "Sport",
        title: "Cricket and Australian rules football",
        description: "Cricket, inherited from the British tradition, holds a central place in national identity, notably through the historic \"Ashes\" rivalry with England. The Australian Football League (AFL), an indigenous sport born in Melbourne in the 19th century and almost unique in the world, draws huge crowds every year, especially for the Grand Final.",
        examples: [
          "The Ashes",
          "AFL Grand Final",
          "Melbourne Cricket Ground"
        ]
      },
      {
        category: "Food",
        title: "Vegemite and the barbecue",
        description: "A dark spread made from yeast extract, Vegemite, invented in 1922, remains a strong marker of identity despite its very distinctive taste. Outdoor barbecue culture (the \"barbie\") and a cuisine strongly shaped by immigration (Asian, Mediterranean, Middle Eastern) characterise contemporary eating habits.",
        examples: [
          "Vegemite",
          "Meat pie",
          "Lamington",
          "Grilled barramundi"
        ]
      },
      {
        category: "Aboriginal art and music",
        title: "Aboriginal art and the didgeridoo",
        description: "Contemporary Aboriginal art, especially the dot painting developed from the 1970s in the central desert, draws on motifs and stories of the Dreaming that are tens of thousands of years old. The didgeridoo, a traditional wind instrument from northern Australia, is one of its best-known musical symbols abroad."
      }
    ]
  },
  territories: {
    summary: "The Commonwealth of Australia is a federation of six states and two mainland territories (the Northern Territory and the Australian Capital Territory). It also administers several external territories: three are permanently inhabited — Norfolk Island in the Pacific, Christmas Island and the Cocos (Keeling) Islands in the Indian Ocean — while others have no permanent civilian population, such as the Ashmore and Cartier Islands, the Coral Sea Islands, Heard Island and McDonald Islands, or the Australian Antarctic Territory, a territorial claim in Antarctica which, like the other claims on the continent, is not recognised by the whole international community under the Antarctic Treaty System.",
    divisions: [
      {
        name: "States"
      },
      {
        name: "Mainland territories",
        note: "Northern Territory and Australian Capital Territory."
      },
      {
        name: "Inhabited external territories",
        note: "Norfolk Island, Christmas Island, Cocos (Keeling) Islands."
      }
    ],
    metropolitanRegions: STATES_AND_TERRITORIES,
    overseas: [
      {
        name: "Norfolk Island",
        status: "External territory, run directly by an administrator appointed by the Commonwealth since its self-government was abolished in 2015"
      },
      {
        name: "Christmas Island",
        status: "Unorganised external territory, in the Indian Ocean"
      },
      {
        name: "Cocos (Keeling) Islands",
        status: "Unorganised external territory, in the Indian Ocean"
      }
    ]
  },
  environment: {
    renewableShare: {
      note: "Share of renewables (solar, wind, hydro) in total electricity generation; the country generates no nuclear electricity."
    },
    co2PerCapita: {
      note: "Among the highest per-capita emissions of the developed countries, the result of electricity still largely generated from coal and long domestic transport distances."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Share of world uranium reserves",
        value: {
          note: "The world's largest identified uranium reserves, all of it exported."
        }
      }
    ],
    risks: [
      "Increasingly intense and frequent bushfires",
      "Prolonged droughts and water stress",
      "Tropical cyclones in the north",
      "Coral bleaching on the Great Barrier Reef"
    ],
    summary: "The driest continent after Antarctica, Australia is highly exposed to bushfires, whose scale and frequency have increased in recent decades (the devastating 2019–2020 \"Black Summer\" fires burned tens of millions of hectares), as well as to droughts and cyclones. The country holds about a third of the world's identified uranium reserves and is one of its leading exporters, but generates no nuclear electricity: it is among the only G20 countries to combine large uranium reserves with zero domestic nuclear generation, as building power plants has been banned at federal level since the Environment Protection and Biodiversity Conservation Act of 1999 (EPBC Act) — a ban whose repeal has been the subject of growing political debate since the mid-2020s, but which remains in force. Its electricity generation, long dominated by coal, has been shifting rapidly to wind and solar since the mid-2020s."
  },
  keyFacts: [
    {
      title: "A purpose-built capital that is not the largest city",
      description: "Canberra was specially designed and built in the early 20th century to settle the rivalry between Sydney and Melbourne, both then vying to be capital; it has only about 485,000 inhabitants today, far behind Sydney and Melbourne (more than 5 million each)."
    },
    {
      title: "The world's largest uranium reserves, zero nuclear electricity",
      description: "Australia holds about a third of the world's identified uranium reserves and is one of its largest exporters, but building nuclear power plants has been banned there since 1999: the country generates no nuclear electricity, a unique case among the major uranium-exporting economies."
    },
    {
      title: "The driest inhabited continent after Antarctica",
      description: "With average rainfall of only 419 mm a year, Australia is the most arid inhabited continent after Antarctica, which explains the extreme concentration of its population on a narrow coastal strip."
    },
    {
      title: "No land borders",
      description: "The only nation to occupy an entire continent, Australia is the only large country in the world that shares no land border with another state."
    },
    {
      title: "A referendum on Indigenous recognition rejected in 2023",
      description: "On October 14, 2023, Australians rejected by 60.1% the constitutional creation of an Indigenous advisory body (the \"Voice to Parliament\"), with the proposal failing to win a majority in any of the six states."
    },
    {
      title: "One in four residents born abroad",
      description: "Australia has one of the highest shares of foreign-born population among the major developed economies, the result of one of the most generous net immigration policies in the world."
    }
  ],
  cities: [
    {
      name: "Canberra"
    },
    {
      name: "Sydney"
    },
    {
      name: "Melbourne"
    },
    {
      name: "Brisbane"
    },
    {
      name: "Perth"
    },
    {
      name: "Adelaide"
    }
  ],
  rivers: [
    {
      name: "Murray",
      lengthKm: {
        note: "Australia's longest river; forms part of the border between New South Wales and Victoria."
      },
      source_location: "Australian Alps, near Cowombat Flat (New South Wales)",
      mouth: "Southern Ocean, at the Murray Mouth, near Goolwa (South Australia)"
    },
    {
      name: "Darling (Baaka)",
      lengthKm: {
        note: "The Murray's main tributary; the Murray–Darling system forms the country's largest river basin."
      },
      source_location: "Confluence of the Culgoa and Barwon rivers, near Brewarrina (New South Wales)",
      mouth: "Confluence with the Murray, at Wentworth (New South Wales)"
    },
    {
      name: "Murrumbidgee",
      lengthKm: {
        note: "The Murray's second-longest tributary; irrigates a major farming region (the Riverina)."
      },
      source_location: "Snowy Mountains, near Peppercorn Hill (New South Wales)",
      mouth: "Confluence with the Murray, near Boundary Bend (New South Wales/Victoria border)"
    }
  ],
  regions: STATES_AND_TERRITORIES,
  sources: {
    "Australian Bureau of Statistics": "Australian Bureau of Statistics",
    "Australian Bureau of Statistics (ABS)": "Australian Bureau of Statistics (ABS)",
    "Australian Bureau of Statistics (ABS), recensement 2021": "Australian Bureau of Statistics (ABS), 2021 Census",
    "Clean Energy Council": "Clean Energy Council",
    "Geoscience Australia": "Geoscience Australia",
    "Geoscience Australia / Wikipedia": "Geoscience Australia / Wikipedia",
    "Parlement d'Australie": "Parliament of Australia",
    "World Nuclear Association / AIEA-OCDE": "World Nuclear Association / IAEA-OECD"
  }
};
