import type { CountryTranslation } from "@/lib/i18n/translation";

const STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia",
  "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine",
  "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
  "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
  "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
  "Washington", "West Virginia", "Wisconsin", "Wyoming",
].map((name) => ({ name }));

/** English translation of data/etats-unis — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "88d285052560",
  capital: "Washington, D.C.",
  geography: {
    headline: "A continental territory between two oceans, extended by Alaska, Hawaii and island territories",
    areaKm2: {
      note: "Land area. Including inland waters, the total area (Census Bureau) is about 9,833,520 km², which ranks the country 3rd or 4th in the world depending on the method used."
    },
    highestPoint: {
      name: "Denali (Alaska)"
    },
    borderingCountries: [
      "Canada",
      "Mexico"
    ],
    climate: "Highly varied given the size of the country: humid continental in the Northeast and Midwest, humid subtropical in the Southeast, semi-arid and desert across much of the interior West, Mediterranean on the California coast, oceanic in the Pacific Northwest, polar in Alaska and tropical in Hawaii and southern Florida.",
    summary: "The United States covers most of central North America, between the Atlantic and Pacific oceans, with Canada to the north and Mexico to the south. Its terrain combines the Atlantic coastal plains, the Appalachians in the east, the vast Great Plains in the centre and the high ranges of the Rocky Mountains in the west. The national territory also includes Alaska, at the north-western tip of the continent, the volcanic archipelago of Hawaii, isolated in the middle of the Pacific, and several non-contiguous island territories."
  },
  population: {
    total: {
      note: "2025 estimate; population of the 50 states and the District of Columbia, excluding island territories."
    },
    summary: "The world's third most populous country after India and China, the United States has an overwhelmingly urban population, concentrated along the Atlantic and Pacific coasts and in the south of the country (the Sun Belt), while vast areas of the Great Plains and the interior West remain sparsely populated. Population growth, now modest, relies increasingly on net migration."
  },
  languages: {
    entries: [
      {
        name: "English",
        sharePercent: {
          note: "Share of the population aged 5 and over speaking only English at home."
        },
        note: "De facto language of the federal administration; made official at federal level by a 2025 executive order, after having no national official status for more than two centuries. Some thirty states had individually made it their official language before then."
      },
      {
        name: "Spanish",
        sharePercent: {
          note: "Share of the population aged 5 and over speaking Spanish at home."
        }
      },
      {
        name: "Native American languages (Navajo, Central Yupik…)",
        note: "Several dozen Indigenous languages survive, some co-official locally (Navajo in the Navajo Nation, for example); most are classified as critically endangered by UNESCO."
      }
    ],
    summary: "For most of its history the United States had no official language at federal level, with English prevailing in practice as the language of government, education and business; a 2025 executive order gave it official status at federal level. Spanish is by far the most spoken language after English, especially in the Southwest, Florida and Puerto Rico, where it is co-official."
  },
  religion: {
    surveyName: "Religious Landscape Study",
    ageScope: "Adults (18 and over), whole United States",
    points: [
      {
        label: "Christianity"
      },
      {
        label: "No religion"
      },
      {
        label: "Other religions (Jewish, Muslim, Buddhist, Hindu…)"
      },
      {
        label: "No answer"
      }
    ],
    summary: "According to the Pew Research Center's 2023–2024 Religious Landscape Study, 63% of American adults identify as Christian — around 40 points of them Protestant (evangelical, mainline and historically Black churches combined) and 19% Catholic — while 30% say they have no religion (nothing in particular, agnostic or atheist).",
    methodologyNote: "These figures are based on self-declared religious affiliation and do not measure actual practice (attending a place of worship, prayer), which is considerably lower than declared affiliation across all faiths."
  },
  politics: {
    stateForm: "Federal republic",
    regime: "Presidential system",
    headOfState: {
      title: "President of the United States",
      name: "Donald Trump",
      since: "January 20, 2025"
    },
    headOfGovernment: {
      title: "President of the United States",
      name: "Donald Trump",
      since: "January 20, 2025"
    },
    legislature: {
      name: "Congress",
      chambers: [
        {
          name: "House of Representatives"
        },
        {
          name: "Senate"
        }
      ]
    },
    constitution: {
      adopted: "September 17, 1787 (signed) — in force since March 4, 1789"
    },
    summary: "The United States is a federal republic with a presidential system: unlike in parliamentary systems, the president is both head of state and head of government, is elected separately from Congress (by indirect universal suffrage, through the Electoral College) for a four-year term, and is not accountable to it. Legislative power belongs to a bicameral Congress, and each of the 50 states has its own constitution, governor and legislature."
  },
  economy: {
    currency: {
      name: "United States dollar"
    },
    gdp: {
      note: "Current US dollars — for a consistent comparison between countries. World's largest economy by nominal GDP."
    },
    gdpPerCapita: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    unemploymentRate: {
      note: "August 2026."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry"
      },
      {
        name: "Agriculture"
      }
    ],
    indicators: [
      {
        label: "Dollar's share of global foreign exchange reserves",
        value: {
          note: "The dollar remains by far the world's leading reserve currency, ahead of the euro."
        }
      }
    ],
    summary: "The world's largest economy by nominal GDP, the United States relies on a highly developed service sector (finance, technology, healthcare, retail) alongside a powerful but smaller industrial base (aerospace, automotive, energy, high tech) and highly productive agriculture despite its small share of GDP. The dollar plays a central role in the international financial system as the world's main reserve and trading currency."
  },
  history: {
    intro: "A few milestones to place the major stages in the country's formation and transformation — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Indigenous peoples and European colonisation",
        summary: "The territory of the present-day United States has been inhabited for millennia by several hundred Native American nations and peoples. Estimates of the population before European contact vary widely, from 2.5 to 7 million people north of Mexico depending on the study. From the early 17th century, European powers (Spain, France, the Netherlands, England) established colonies on the Atlantic coast.",
        events: [
          {
            date: "1607",
            title: "Founding of Jamestown",
            description: "The first permanent English colony in North America, in Virginia."
          },
          {
            date: "1620",
            title: "Arrival of the Mayflower",
            description: "Puritan settlers found Plymouth Colony, in present-day Massachusetts."
          },
          {
            date: "1619 – 1775",
            title: "Growth of colonial slavery",
            description: "From 1619, enslaved Africans are brought to the British colonies of North America; slavery spreads and is gradually legalised colony by colony, especially in the agricultural Southern colonies."
          }
        ]
      },
      {
        title: "Independence and the founding of the Republic",
        summary: "The thirteen British colonies in America rebelled and declared independence in 1776. The War of Independence ended with the recognition of American sovereignty in 1783, before a new federal Constitution was adopted in 1787–1789.",
        events: [
          {
            date: "July 4, 1776",
            title: "Declaration of Independence",
            description: "The Continental Congress adopts the Declaration of Independence, drafted mainly by Thomas Jefferson."
          },
          {
            date: "September 3, 1783",
            title: "Treaty of Paris",
            description: "Great Britain recognises the independence of the United States, which then extend as far as the Mississippi."
          },
          {
            date: "September 17, 1787 – March 4, 1789",
            title: "Adoption of the federal Constitution",
            description: "The Philadelphia Convention drafts the Constitution, ratified by the states and brought into force in 1789; George Washington becomes the first president."
          }
        ]
      },
      {
        title: "Territorial expansion and slavery",
        summary: "The young Republic expanded rapidly westward through purchases, annexations and wars, at the cost of the forced removal of Native American nations. Slavery, gradually abolished in the North, grew in the South, whose economy relied on plantations: the 1860 census counted about 3.95 million enslaved people, nearly 13% of the country's total population.",
        events: [
          {
            date: "1803",
            title: "Louisiana Purchase",
            description: "The United States buys a territory of about 2.1 million km² from France, doubling its size."
          },
          {
            date: "1830 – 1850",
            title: "Indian Removal Act and forced removals",
            description: "The 1830 law authorises the forced removal of the Southeastern Native American nations to an \"Indian Territory\" west of the Mississippi. The resulting \"Trail of Tears\" for the Cherokee Nation (1838) causes some 4,000 to 8,000 deaths among about 16,000 people removed; the removals of the period as a whole affect some 60,000 people of the Five Civilized Tribes."
          },
          {
            date: "1846 – 1848",
            title: "Mexican–American War",
            description: "At the end of the conflict, the Treaty of Guadalupe Hidalgo cedes more than 1.3 million km² of Mexican territory to the United States (present-day California, Nevada, Utah, Arizona and parts of New Mexico, Colorado and Wyoming)."
          }
        ]
      },
      {
        title: "Civil War and Reconstruction",
        summary: "Eleven Southern slave states seceded in 1860–1861 to form the Confederate States of America, mainly over the issue of slavery. The ensuing civil war, with a death toll now estimated at between 620,000 and 750,000, remains the deadliest conflict in US history. It ended with the defeat of the South, the abolition of slavery and a period of political and social reconstruction.",
        events: [
          {
            date: "April 12, 1861",
            title: "Start of the Civil War",
            description: "The bombardment of Fort Sumter, in South Carolina, marks the start of the conflict between the Union and the Confederacy."
          },
          {
            date: "January 1, 1863",
            title: "Emancipation Proclamation",
            description: "President Abraham Lincoln declares free the enslaved people in the states in rebellion."
          },
          {
            date: "April 9, 1865",
            title: "Surrender at Appomattox",
            description: "The surrender of Confederate General Robert E. Lee marks the effective end of the war."
          },
          {
            date: "December 6, 1865",
            title: "13th Amendment — abolition of slavery",
            description: "The 13th Amendment to the Constitution abolishes slavery throughout the United States."
          },
          {
            date: "1877",
            title: "End of Reconstruction",
            description: "The withdrawal of federal troops from the South ends Reconstruction; the following decades see the introduction of racial segregation laws (\"Jim Crow laws\"), which remain in force in the South until the 1960s."
          }
        ]
      },
      {
        title: "Industrial rise and world wars",
        summary: "Rapid industrialisation, massive waves of immigration and urbanisation turned the country into the world's leading industrial power. The United States took part in both world wars and, after going through the Great Depression, emerged from the Second World War as one of the two superpowers.",
        events: [
          {
            date: "1917 – 1918",
            title: "Entry into the First World War",
            description: "The United States joins the Allies in 1917; about 116,000 American soldiers die in the conflict."
          },
          {
            date: "1920",
            title: "19th Amendment — women's suffrage",
            description: "The 19th Amendment prohibits any restriction of the right to vote on the basis of sex."
          },
          {
            date: "1929 – 1939",
            title: "Great Depression and the New Deal",
            description: "The 1929 stock market crash opens a decade of severe economic crisis; President Franklin D. Roosevelt's New Deal introduces a vast programme of social and economic reforms from 1933."
          },
          {
            date: "December 7, 1941",
            title: "Attack on Pearl Harbor",
            description: "The Japanese attack on the Pearl Harbor naval base, in Hawaii, brings the United States into the war."
          },
          {
            date: "1945",
            title: "Atomic bombings and the end of the war",
            description: "The atomic bombings of Hiroshima and Nagasaki (August 6 and 9) precede Japan's surrender, which ends the Second World War."
          }
        ]
      },
      {
        title: "Cold War and the civil rights movement",
        summary: "In rivalry with the Soviet Union, the United States waged a global confrontation marked by the space race and several proxy conflicts (Korea, Vietnam). At home, the civil rights movement ended legal segregation.",
        events: [
          {
            date: "May 17, 1954",
            title: "Brown v. Board of Education",
            description: "The Supreme Court rules racial segregation in public schools unconstitutional."
          },
          {
            date: "July 2, 1964",
            title: "Civil Rights Act",
            description: "Signed by President Lyndon B. Johnson, this law prohibits discrimination based on race, colour, religion, sex or national origin, notably in public places and employment."
          },
          {
            date: "August 6, 1965",
            title: "Voting Rights Act",
            description: "This law outlaws the discriminatory practices (literacy tests, etc.) used in several Southern states to keep African Americans from voting."
          },
          {
            date: "July 20, 1969",
            title: "First steps on the Moon",
            description: "The Apollo 11 mission lands the first humans on the Moon, the high point of the space race with the USSR."
          },
          {
            date: "1955 – 1975",
            title: "Vietnam War",
            description: "American military involvement in Vietnam, widely contested at home from the mid-1960s, costs the lives of about 58,000 American soldiers."
          }
        ]
      },
      {
        title: "Today",
        summary: "Since the end of the Cold War, the United States has remained the world's leading economic and military power, marked by the September 11, 2001 attacks, the wars in Afghanistan and Iraq, and the 2008 financial crisis.",
        events: [
          {
            date: "September 11, 2001",
            title: "September 11 attacks",
            description: "Coordinated attacks on the World Trade Center in New York and the Pentagon kill nearly 3,000 people and lead to the launch of the \"war on terror\"."
          },
          {
            date: "2008 – 2009",
            title: "Global financial crisis",
            description: "The subprime crisis, which began in the United States, triggers the worst global recession since the Great Depression."
          },
          {
            date: "January 20, 2025",
            title: "Presidential inauguration",
            description: "Donald Trump begins a second, non-consecutive term as President of the United States."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Celebrations",
        title: "Thanksgiving",
        description: "A national holiday celebrated on the fourth Thursday of November, associated with autumn 1621 in Plymouth, where settlers and Wampanoag people are said to have shared a harvest meal; made an annual national holiday by Abraham Lincoln in 1863.",
        examples: [
          "Roast turkey",
          "Macy's parade in New York",
          "Family meal"
        ]
      },
      {
        category: "Music",
        title: "Jazz, blues and African American music",
        description: "Born at the turn of the 20th century in the South, especially in New Orleans, these genres have deeply shaped popular music worldwide and gave rise to rock 'n' roll, soul and later hip-hop.",
        examples: [
          "Louis Armstrong",
          "New Orleans",
          "Motown"
        ]
      },
      {
        category: "Cinema",
        title: "Hollywood",
        description: "Since the early 20th century, this Los Angeles neighbourhood has given its name to the American film industry, the most influential in the world in terms of international reach.",
        examples: [
          "Hollywood Sign",
          "Academy Awards (Oscars)",
          "Walk of Fame"
        ]
      },
      {
        category: "Sport",
        title: "National professional sports",
        description: "American football, baseball, basketball and ice hockey each have a major professional league followed nationwide, with heavily covered finals such as the Super Bowl.",
        examples: [
          "Super Bowl (NFL)",
          "World Series (MLB)",
          "NBA Finals"
        ]
      },
      {
        category: "Natural heritage",
        title: "The national parks",
        description: "Yellowstone, created in 1872, is the world's first national park; the country now has 63, managed together with all federal natural and historic sites by the National Park Service.",
        examples: [
          "Yellowstone",
          "Grand Canyon",
          "Yosemite"
        ]
      },
      {
        category: "Heritage",
        title: "27 UNESCO World Heritage properties",
        description: "The country has 27 inscribed sites (thirteen cultural, thirteen natural, one mixed), including national parks and historic monuments linked to its independence.",
        examples: [
          "Statue of Liberty",
          "Independence Hall",
          "Grand Canyon National Park"
        ]
      }
    ]
  },
  territories: {
    summary: "The United States is a federation of 50 states, plus the federal district of Washington, D.C., seat of the federal government and separate from any state. The country also administers five inhabited, non-contiguous island territories, most of them acquired after the Spanish–American War of 1898, whose inhabitants are US citizens or nationals but have no full voting representation in Congress.",
    divisions: [
      {
        name: "States"
      },
      {
        name: "Federal district",
        note: "Washington, D.C., seat of the federal government."
      },
      {
        name: "Inhabited island territories",
        note: "Puerto Rico, Guam, US Virgin Islands, American Samoa, Northern Mariana Islands."
      }
    ],
    metropolitanRegions: STATES,
    overseas: [
      {
        name: "Puerto Rico",
        status: "Unincorporated, organised territory with Commonwealth status",
        population: {
          note: "2020 decennial census; about 3.2 million inhabitants according to the latest estimates."
        }
      },
      {
        name: "Guam",
        status: "Unincorporated, organised territory"
      },
      {
        name: "US Virgin Islands",
        status: "Unincorporated, organised territory"
      },
      {
        name: "American Samoa",
        status: "Unincorporated, unorganised territory"
      },
      {
        name: "Northern Mariana Islands",
        status: "Unincorporated territory with Commonwealth status, in political union with the United States"
      }
    ]
  },
  environment: {
    renewableShare: {
      note: "Share of renewable energy in total primary energy consumption. Their share of electricity generation alone is higher, about 21% in 2023."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Nuclear share of electricity",
        value: {
          note: "The United States operates the world's largest fleet of nuclear reactors by number of units, but their relative share of electricity remains lower than in many European countries."
        }
      }
    ],
    risks: [
      "Hurricanes (Atlantic and Gulf coasts)",
      "Tornadoes (Midwest and Great Plains)",
      "Wildfires (West)",
      "Earthquakes (California, Alaska)",
      "Floods"
    ],
    summary: "The size and geographic diversity of the country expose it to a wide range of natural hazards, from hurricanes on the Atlantic and Gulf coasts to tornadoes on the Great Plains, as well as wildfires and earthquakes in the West. The energy mix remains dominated by fossil fuels, with nuclear power (the world's largest fleet by number of reactors) and renewables growing, which results in CO₂ emissions per capita among the highest of the major economies."
  },
  keyFacts: [
    {
      title: "A capital that is not the largest city",
      description: "Washington, D.C., seat of the federal government, is only the country's 21st most populous city (about 694,000 inhabitants), far behind New York (8.6 million) or Los Angeles (3.9 million)."
    },
    {
      title: "The world's largest economy",
      description: "With a nominal GDP of about $29.3 trillion in 2024, the United States remains the world's largest economy, and the dollar the main international reserve currency (nearly 57% of global foreign exchange reserves)."
    },
    {
      title: "The world's largest fleet of nuclear reactors",
      description: "The United States operates more civilian nuclear reactors than any other country, but they supply only about 19% of the electricity generated, compared with more than two-thirds in France."
    },
    {
      title: "A territory spread across many time zones",
      description: "Between Alaska, the 48 contiguous states, Hawaii and the island territories in the Pacific and the Caribbean, the country spans eleven time zones including its territories, a world record shared with France."
    },
    {
      title: "The birthplace of the national park system",
      description: "Yellowstone, created in 1872, is the world's first national park; the country now has 63, managed together with all federal natural and historic heritage by the National Park Service."
    },
    {
      title: "No federal official language for more than two centuries",
      description: "Although English has been the de facto language of government since the country's founding, it was only designated the official language of the United States at federal level in 2025, by executive order."
    }
  ],
  cities: [
    {
      name: "Washington, D.C.",
      population: {
        note: "Despite its status as capital, only the country's 21st most populous city."
      }
    },
    {
      name: "New York"
    },
    {
      name: "Los Angeles"
    },
    {
      name: "Chicago"
    },
    {
      name: "Houston"
    },
    {
      name: "Phoenix"
    },
    {
      name: "Philadelphia"
    },
    {
      name: "San Antonio"
    },
    {
      name: "San Diego"
    },
    {
      name: "Dallas"
    }
  ],
  rivers: [
    {
      name: "Mississippi",
      source_location: "Lake Itasca (Minnesota)",
      mouth: "Gulf of Mexico"
    },
    {
      name: "Missouri",
      source_location: "Montana (confluence of the Jefferson, Madison and Gallatin rivers)",
      mouth: "Mississippi River"
    },
    {
      name: "Rio Grande",
      source_location: "San Juan Mountains (Colorado)",
      mouth: "Gulf of Mexico"
    },
    {
      name: "Colorado",
      source_location: "Rocky Mountains (Colorado)",
      mouth: "Gulf of California (Mexico)"
    },
    {
      name: "Columbia",
      source_location: "British Columbia (Canada)",
      mouth: "Pacific Ocean"
    }
  ],
  regions: STATES,
  sources: {
    "9/11 Memorial & Museum": "9/11 Memorial & Museum",
    "Academy of Motion Picture Arts and Sciences": "Academy of Motion Picture Arts and Sciences",
    "Bureau of Labor Statistics (BLS)": "Bureau of Labor Statistics (BLS)",
    "FMI — COFER": "IMF — COFER",
    "Federal Emergency Management Agency (FEMA)": "Federal Emergency Management Agency (FEMA)",
    "Library of Congress": "Library of Congress",
    NASA: "NASA",
    "National Archives": "National Archives",
    "National Park Service": "National Park Service",
    "Nations unies / FMI": "United Nations / IMF",
    "Smithsonian Institution": "Smithsonian Institution",
    "The White House": "The White House",
    "U.S. Census Bureau": "U.S. Census Bureau",
    "U.S. Census Bureau — American Community Survey": "U.S. Census Bureau — American Community Survey",
    "U.S. Energy Information Administration (EIA)": "U.S. Energy Information Administration (EIA)",
    "Wikipédia (d'après CIA World Factbook)": "Wikipedia (based on the CIA World Factbook)"
  }
};
