import type { CountryTranslation } from "@/lib/i18n/translation";

const STATES_AND_UNION_TERRITORIES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh",
  "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha",
  "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi (NCT)", "Jammu and Kashmir",
  "Ladakh", "Lakshadweep", "Puducherry",
].map((name) => ({ name }));

const CITY_CENSUS_NOTE =
  "Population of the municipality proper (excluding the wider urban agglomeration) at the last full census; the following census, planned for 2021, has been postponed indefinitely.";

/** English translation of data/inde — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "e47ee024b3ef",
  capital: "New Delhi",
  geography: {
    headline: "A subcontinent in itself, from the high Himalayas to the Ganges plains and the tropical Deccan",
    areaKm2: {
      note: "The world's seventh-largest country by area; the border with China, not fully demarcated, is disputed (see Aksai Chin and Arunachal Pradesh)."
    },
    highestPoint: {
      name: "Kangchenjunga"
    },
    borderingCountries: [
      "Pakistan",
      "China",
      "Nepal",
      "Bhutan",
      "Bangladesh",
      "Myanmar"
    ],
    climate: "Highly varied by region: desert in the west (Thar), alpine and glacial in the Himalayas to the north, humid tropical in the south-west and the islands. The summer monsoon (June to September), carried by south-westerly winds, brings most of the annual rainfall and shapes the country's farming calendar.",
    summary: "India occupies most of the Indian subcontinent, between the Himalayan range to the north — home to its highest point, Kangchenjunga, on the border of Sikkim and Nepal — and the Indian Ocean to the south. The country combines vast, densely populated alluvial plains along the Ganges and the Indus, an ancient volcanic plateau (the Deccan) in the south-centre, and two long coastlines bordered by the Arabian Sea to the west and the Bay of Bengal to the east. Its north-eastern border with China (Arunachal Pradesh sector) and its north-western border in the Kashmir region (Aksai Chin sector, administered by China) have been disputed since the mid-20th century."
  },
  population: {
    total: {
      note: "Estimate (World Bank/United Nations): the 2011 decennial census, the last full census, counted 1,210,854,977 inhabitants; the census planned for 2021 was postponed indefinitely (the pandemic, then administrative delays) and has still not taken place."
    },
    growthRate: {
      note: "Steadily slowing since the 1980s; India overtook China as the world's most populous country around 2023 according to United Nations estimates."
    },
    urbanShare: {
      note: "One of the lowest urbanisation rates among major economies, despite the size of its megacities."
    },
    summary: "The world's most populous country since the mid-2020s, India nevertheless remains mostly rural: more than two-thirds of its population lives outside the big cities. Its population growth, long very rapid, has slowed markedly since the 1980s, but large differences remain between states — the North and East remaining generally more fertile than the South, already close to replacement level."
  },
  languages: {
    entries: [
      {
        name: "Hindi",
        note: "Official language of the Union (in Devanagari script) and the most widely spoken mother tongue in the country, but the Constitution recognises no \"national language\"."
      },
      {
        name: "English",
        sharePercent: {
          note: "Share of native speakers; English is very widely used as a second or third language (about 11% of the population), especially in government, the courts, higher education and business."
        },
        note: "Co-official language of the Union \"as a subsidiary\" since 1967, with no time limit, alongside Hindi."
      },
      {
        name: "Bengali",
        note: "Official language of West Bengal and Tripura; the country's second most common mother tongue."
      },
      {
        name: "Marathi",
        note: "Official language of Maharashtra."
      },
      {
        name: "Telugu",
        note: "Official language of Andhra Pradesh and Telangana."
      },
      {
        name: "Tamil",
        note: "Official language of Tamil Nadu and Puducherry; one of the oldest classical languages still in use."
      },
      {
        name: "Gujarati",
        note: "Official language of Gujarat."
      },
      {
        name: "Urdu",
        note: "Official or co-official language in several northern states, notably Jammu and Kashmir."
      },
      {
        name: "Kannada",
        note: "Official language of Karnataka."
      },
      {
        name: "Malayalam",
        note: "Official language of Kerala."
      },
      {
        name: "Punjabi",
        note: "Official language of Punjab and the liturgical language of Sikhism."
      }
    ],
    summary: "The Indian Constitution establishes no \"national language\": Hindi and English are the two official languages of the Union, while 22 further languages are listed in the Eighth Schedule of the Constitution and serve as official languages in the states where they predominate. Hindi, the mother tongue of about 44% of the population, is concentrated in the north and centre of the country; the southern states (Tamil Nadu, Kerala, Karnataka, Andhra Pradesh, Telangana) use Dravidian languages unrelated to Hindi and are often reluctant to see it spread. In all, the 2011 census recorded 121 languages and more than 19,500 declared dialects."
  },
  religion: {
    surveyName: "Census of India",
    ageScope: "Total population reporting a religious affiliation",
    points: [
      {
        label: "Hindu"
      },
      {
        label: "Muslim"
      },
      {
        label: "Christian"
      },
      {
        label: "Sikh"
      },
      {
        label: "Buddhist"
      },
      {
        label: "Jain"
      },
      {
        label: "Other / not stated"
      }
    ],
    summary: "India is a Hindu-majority state (about 80% of the population) but is home, in absolute terms, to one of the largest Muslim populations in the world — more than 170 million people according to the 2011 census, more than in most Muslim-majority countries. It also has large Sikh (concentrated in Punjab), Christian (especially in Kerala and the North-East) and Buddhist communities (historical heir to Buddhism, also strengthened by the mass conversion of former untouchables led by B. R. Ambedkar in 1956), as well as a small but influential Jain community. The 1950 Constitution makes India a secular republic (constitutional \"secularism\", a term explicitly added to the preamble in 1976), guaranteeing freedom of worship to all faiths.",
    methodologyNote: "Latest available religion data, from the 2011 census (the next decennial census, planned for 2021, has been postponed indefinitely)."
  },
  politics: {
    stateForm: "Federal republic",
    regime: "Federal parliamentary republic",
    headOfState: {
      title: "President of India",
      name: "Droupadi Murmu",
      since: "July 25, 2022"
    },
    headOfGovernment: {
      title: "Prime Minister",
      name: "Narendra Modi",
      since: "May 26, 2014 (began a 3rd consecutive term on June 9, 2024)"
    },
    legislature: {
      name: "Parliament of India (Sansad)",
      chambers: [
        {
          name: "Lok Sabha (House of the People)"
        },
        {
          name: "Rajya Sabha (Council of States)"
        }
      ]
    },
    constitution: {
      adopted: "November 26, 1949 (in force since January 26, 1950)"
    },
    summary: "India is a federal parliamentary republic of 28 states and 8 union territories. The President, elected for five years by indirect suffrage through an electoral college of national MPs and members of the state assemblies, has an essentially representative and ceremonial role. Real executive power lies with the Prime Minister, leader of the majority party or coalition in the Lok Sabha, who heads the Council of Ministers and is accountable to Parliament. Narendra Modi and his party, the Bharatiya Janata Party (BJP), have dominated national politics since 2014."
  },
  economy: {
    currency: {
      name: "Indian rupee"
    },
    gdp: {
      note: "Current US dollars; the world's 5th-largest GDP in nominal terms."
    },
    gdpPerCapita: {
      note: "Current US dollars; much higher in purchasing power parity (about 11,000–12,000 USD according to the IMF), the gap reflecting a low domestic price level."
    },
    unemploymentRate: {
      note: "Modelled estimate (ILO); the national Periodic Labour Force Survey (PLFS, MoSPI) gives noticeably different results depending on the definition of activity used, as the overwhelming majority of Indian employment remains informal."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry"
      },
      {
        name: "Agriculture"
      }
    ],
    indicators: [
      {
        label: "Foreign exchange reserves",
        value: {
          value: "785.7 billion"
        }
      },
      {
        label: "UPI digital transactions",
        value: {
          value: "about 20 billion a month",
          note: "The public UPI instant payment system is estimated to process nearly half of all digital transactions made worldwide."
        }
      }
    ],
    summary: "The world's fifth-largest economy in nominal terms but 149th in GDP per capita, India combines a developed service economy — software, information technology, generic pharmaceuticals (the country alone supplies about 20% of global demand for generic medicines) — with agriculture that still employs nearly half the workforce for less than a fifth of the wealth produced. The economic liberalisation reforms launched in 1991, in response to a severe balance-of-payments crisis, opened the country to trade and foreign investment and set off three decades of sustained growth. The economy remains marked by a very large informal sector, wide regional and income inequalities, and a public digital infrastructure (UPI payments, the Aadhaar biometric ID) seen as a model by several developing countries."
  },
  history: {
    intro: "A few milestones to place the major stages in the building of the modern country — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Ancient civilisations, empires and sultanates",
        summary: "The Indus Valley Civilisation (c. 2600–1900 BC), one of the oldest urban civilisations, preceded the arrival of the Indo-Aryans and the Vedic texts. Then came the Maurya Empire (4th–2nd century BC), under which Ashoka converted to Buddhism, and the Gupta Empire (4th–6th century), a \"golden age\" of science and the arts. Muslim sultanates took hold in the north from the 13th century, before the Mughal Empire, founded in 1526 by Babur, unified most of the subcontinent and left an immense heritage, including the Taj Mahal.",
        events: []
      },
      {
        title: "British rule: from the East India Company to the Raj",
        summary: "The East India Company's victory at Plassey in 1757 began its growing grip on the subcontinent, which was administered directly by the Crown (the \"British Raj\") after the 1857 rebellion. The independence movement took shape around the Indian National Congress, founded in 1885, then became a mass movement under Mahatma Gandhi, based on non-violence (satyagraha) and civil disobedience, notably during the Salt March of 1930. Exhausted by the Second World War, the United Kingdom granted independence in 1947, at the cost of a partition along largely religious lines.",
        events: [
          {
            date: "1857-1858",
            title: "Rebellion of 1857",
            description: "The revolt of the Company army's sepoys spreads across much of northern India before being crushed; in 1858 the British Crown takes over the administration directly."
          },
          {
            date: "August 15, 1947",
            title: "Independence and partition of India",
            description: "British India is divided into two dominions, India (Hindu-majority) and Pakistan (Muslim-majority, then in two wings). Partition causes one of the largest population movements in history — 10 to 20 million people — and massive intercommunal violence, with a death toll, estimated at between 200,000 and about two million, that remains debated."
          }
        ]
      },
      {
        title: "The Republic and its first decades",
        summary: "The 1950 Constitution made India a federal parliamentary republic. Kashmir's accession in October 1947, contested by Pakistan, opened a conflict that remains unresolved (see Territories); the two countries fought again in 1965 and in 1971, a war that led to the independence of Bangladesh. The 1962 border war with China left a dispute open over Aksai Chin and Arunachal Pradesh. Indira Gandhi imposed a 21-month state of emergency (1975–1977), and the economy remained largely closed and state-regulated until the late 1980s.",
        events: [
          {
            date: "January 26, 1950",
            title: "Constitution comes into force",
            description: "India becomes a republic; its Constitution abolishes untouchability (Article 17) and introduces quotas (\"reservations\") for scheduled castes and tribes."
          },
          {
            date: "May 18, 1974",
            title: "First nuclear test (\"Smiling Buddha\")",
            description: "India's first nuclear test, presented as peaceful, at Pokhran: India becomes the sixth country to master the technology."
          }
        ]
      },
      {
        title: "Economic liberalisation and contemporary India",
        summary: "The 1991 liberalisation — the end of industrial licensing, opening to trade and foreign investment — set off three decades of sustained growth. India asserted itself as a nuclear power in 1998; a limited conflict, the Kargil War, pitted it against Pakistan in Kashmir in 1999. The country has also established itself as a space power.",
        events: [
          {
            date: "July 1991",
            title: "Start of the economic liberalisation reforms",
            description: "Faced with a balance-of-payments crisis, P. V. Narasimha Rao's government launches a sweeping economic opening."
          },
          {
            date: "May 11-13, 1998",
            title: "Pokhran-II nuclear tests",
            description: "India officially declares itself a nuclear-weapon state, outside the NPT; Pakistan responds with its own tests."
          },
          {
            date: "August 5, 2019",
            title: "Revocation of Article 370",
            description: "The government revokes the special autonomy of Jammu and Kashmir (Article 370), reorganised on October 31, 2019 into two union territories (Jammu and Kashmir, and Ladakh)."
          },
          {
            date: "August 23, 2023",
            title: "Chandrayaan-3 Moon landing",
            description: "Chandrayaan-3 achieves the first landing near the Moon's south pole: India is the fourth nation to land on the Moon."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list of the diversity of an immense country.",
    items: [
      {
        category: "Heritage",
        title: "The Taj Mahal",
        description: "A white marble mausoleum built in Agra between 1632 and 1648 by the Mughal emperor Shah Jahan for his wife Mumtaz Mahal, the Taj Mahal has been a World Heritage site since 1983. India has more than 40 World Heritage sites in all, from the Ajanta caves to the temples of Khajuraho."
      },
      {
        category: "Cinema",
        title: "The world's largest film industry by volume",
        description: "With several thousand feature films a year in some twenty languages, India has been the world's largest film producer by number of titles since the 1980s. Hindi cinema from Mumbai (\"Bollywood\") is the best known abroad, but Tamil, Telugu, Bengali and Malayalam cinema also carry great weight.",
        examples: [
          "Bollywood (Hindi cinema)",
          "Tamil cinema (Kollywood)",
          "Telugu cinema (Tollywood)"
        ]
      },
      {
        category: "Celebrations",
        title: "Diwali and Holi",
        description: "Diwali, the \"festival of lights\" in October or November, and Holi, the spring \"festival of colours\", are celebrated well beyond their Hindu origins, alongside the festivals of other traditions (Eid, Christmas, Guru Nanak Jayanti).",
        examples: [
          "Diwali",
          "Holi",
          "Durga Puja"
        ]
      },
      {
        category: "Food",
        title: "A highly diverse regional cuisine",
        description: "Indian cuisine varies greatly by region: spices (turmeric, cumin, cardamom, chilli), rice in the south and wheat (chapati, naan) in the north, widespread vegetarianism among some Hindus and Jains, and a Mughal heritage in the north.",
        examples: [
          "Thali",
          "Biryani",
          "Dosa",
          "Chai (spiced milk tea)"
        ]
      },
      {
        category: "Sport",
        title: "Cricket, by far the most popular sport",
        description: "Introduced by the British, cricket is a major social and economic phenomenon: the national team is a three-time world champion (1983, 2011, 2025) and the Indian Premier League (IPL), launched in 2008, is one of the most lucrative competitions in the world."
      },
      {
        category: "Spirituality",
        title: "Yoga and Indian philosophical traditions",
        description: "Yoga, codified in antiquity (Patañjali's Yoga Sutras), has spread worldwide; at India's initiative, the UN declared June 21 International Day of Yoga in 2014. The country is also the birthplace of four major religions (Hinduism, Buddhism, Jainism, Sikhism)."
      }
    ]
  },
  territories: {
    summary: "India is a federation of 28 states and 8 union territories, the latter administered directly (wholly or partly) by the central government rather than by a fully fledged state government. The most sensitive case is the former princely state of Jammu and Kashmir, disputed since 1947 between India, Pakistan and, for one portion, China, and reorganised in 2019 into two union territories. India has no territory outside the subcontinent: the Andaman and Nicobar Islands and Lakshadweep, although far from the mainland, are fully fledged union territories, counted among the 36 subdivisions below rather than as separate overseas territories.",
    divisions: [
      {
        name: "States"
      },
      {
        name: "Union territories",
        note: "Including Delhi (national capital), Jammu and Kashmir, Ladakh, the Andaman and Nicobar Islands and Lakshadweep."
      }
    ],
    metropolitanRegions: STATES_AND_UNION_TERRITORIES,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "Share of renewables (including large hydro) in electricity actually generated in fiscal year 2024–2025; their share of installed capacity is much higher (about 52% in 2026), a gap due to the intermittency of solar and wind. Nuclear power, not counted as renewable, supplies about 3% of the electricity generated."
    },
    co2PerCapita: {
      note: "Far below the world average despite being the world's third-largest emitter in absolute terms, because of the size of the population; coal remains the country's main source of electricity."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Nuclear share of electricity",
        value: {
          note: "25 reactors in operation in fiscal year 2024–2025 (8,880 MW installed) and 11 more under construction; official target of 100 GW of installed nuclear capacity by 2047. India is not a signatory to the Treaty on the Non-Proliferation of Nuclear Weapons (NPT) and has had nuclear weapons since its tests of 1974 and 1998."
        }
      }
    ],
    risks: [
      "Monsoon and floods",
      "Cyclones (Bay of Bengal and Arabian Sea)",
      "Droughts and water stress",
      "Urban air pollution",
      "Heatwaves",
      "Earthquakes along the Himalayan arc"
    ],
    summary: "India, the world's third-largest CO2 emitter in absolute terms but far below the world average per capita, remains heavily dependent on coal for its electricity while running one of the largest renewable energy programmes in the world, driven mainly by solar. It also operates a modest but rapidly expanding civilian nuclear fleet. The country is also one of the most exposed to natural disasters and the effects of climate change — an increasingly erratic monsoon, extreme heatwaves, growing water stress in the north — and its big cities, especially Delhi, are among the most polluted in the world for fine particles, particularly in winter."
  },
  keyFacts: [
    {
      title: "The world's most populous country",
      description: "India overtook China as the world's most populous country around 2023, with about 1.45 billion inhabitants in 2024 — more than 4 in every 100 people in the world live in India."
    },
    {
      title: "The world's largest democracy",
      description: "With nearly a billion registered voters, India's general elections are the largest in the world; the 2024 election drew more than 640 million voters over about six weeks."
    },
    {
      title: "A nuclear power outside the Non-Proliferation Treaty",
      description: "After a first test in 1974, India declared itself a nuclear-weapon state in 1998. It has never signed the Non-Proliferation Treaty (NPT), like Pakistan and Israel."
    },
    {
      title: "First landing near the Moon's south pole",
      description: "On August 23, 2023, the Indian space agency's (ISRO) Chandrayaan-3 mission achieved the first landing near the Moon's south pole, on a budget often compared to that of a Hollywood film."
    },
    {
      title: "The world's largest instant digital payment system",
      description: "The public UPI (Unified Payments Interface) system processed nearly 20 billion transactions in August 2025 alone, and is estimated to account for about half of all digital transactions made worldwide each month."
    },
    {
      title: "22 official languages, no \"national language\"",
      description: "The Indian Constitution designates no national language: Hindi and English are co-official at Union level, while 22 other languages are recognised in the Eighth Schedule of the Constitution and used as official languages in the states where they predominate."
    }
  ],
  cities: [
    {
      name: "New Delhi",
      population: {
        note: "Figure for the whole National Capital Territory (Delhi); New Delhi proper is only an administrative district of a few hundred thousand inhabitants within this metropolis."
      }
    },
    {
      name: "Mumbai",
      population: {
        note: CITY_CENSUS_NOTE
      }
    },
    {
      name: "Bengaluru",
      population: {
        note: CITY_CENSUS_NOTE
      }
    },
    {
      name: "Hyderabad",
      population: {
        note: CITY_CENSUS_NOTE
      }
    },
    {
      name: "Chennai",
      population: {
        note: CITY_CENSUS_NOTE
      }
    },
    {
      name: "Ahmedabad",
      population: {
        note: CITY_CENSUS_NOTE
      }
    },
    {
      name: "Kolkata",
      population: {
        note: CITY_CENSUS_NOTE
      }
    },
    {
      name: "Srinagar",
      population: {
        note: "Summer capital of the union territory of Jammu and Kashmir."
      }
    }
  ],
  rivers: [
    {
      name: "Ganges (Ganga)",
      lengthKm: {
        note: "The most sacred river in Hinduism; length estimates vary by source and the point of origin used (from 2,525 to about 2,700 km)."
      },
      source_location: "Confluence of the Alaknanda and the Bhagirathi at Devprayag (Uttarakhand); the Bhagirathi, the traditionally sacred source, itself rises at the Gangotri Glacier.",
      mouth: "Bay of Bengal, via a vast delta shared with the Brahmaputra in Bangladesh"
    },
    {
      name: "Brahmaputra",
      lengthKm: {
        note: "Estimates vary between about 2,880 and 3,080 km depending on the source."
      },
      source_location: "Chemayungdung Glacier, near Mount Kailash (Tibet), where it is known as the Yarlung Tsangpo",
      mouth: "Bay of Bengal, via the Ganges delta, in Bangladesh"
    },
    {
      name: "Yamuna",
      source_location: "Yamunotri Glacier, in the Himalayas (Uttarakhand)",
      mouth: "Confluence with the Ganges at Prayagraj (Triveni Sangam), Uttar Pradesh"
    },
    {
      name: "Godavari",
      lengthKm: {
        note: "The longest river in southern India, sometimes nicknamed the \"Ganges of the South\"."
      },
      source_location: "Brahmagiri hills, near Trimbakeshwar (Maharashtra)",
      mouth: "Bay of Bengal, near Antarvedi (Andhra Pradesh)"
    },
    {
      name: "Narmada",
      source_location: "Amarkantak plateau (Madhya Pradesh)",
      mouth: "Arabian Sea, via the Gulf of Khambhat (Gujarat)"
    }
  ],
  regions: STATES_AND_UNION_TERRITORIES,
  sources: {
    "Election Commission of India": "Election Commission of India",
    "Gouvernement de l'Inde": "Government of India",
    "India Meteorological Department (IMD) / Wikipedia": "India Meteorological Department (IMD) / Wikipedia",
    "Indian Space Research Organisation (ISRO)": "Indian Space Research Organisation (ISRO)",
    "Ministry of Law and Justice, Government of India": "Ministry of Law and Justice, Government of India",
    "Ministère de l'Énergie (Inde) / Wikipedia": "Ministry of Power (India) / Wikipedia",
    "National Payments Corporation of India (NPCI)": "National Payments Corporation of India (NPCI)",
    "Nations unies / Banque mondiale": "United Nations / World Bank",
    "Nuclear Power Corporation of India Limited (NPCIL) / Wikipedia": "Nuclear Power Corporation of India Limited (NPCIL) / Wikipedia",
    "Office of the Registrar General & Census Commissioner of India": "Office of the Registrar General & Census Commissioner of India",
    "Recensement de l'Inde": "Census of India",
    "Recensement de l'Inde (2011)": "Census of India (2011)",
    "Reserve Bank of India (RBI)": "Reserve Bank of India (RBI)",
    "Wikipedia (géographie de l'Inde)": "Wikipedia (geography of India)"
  },
  units: {
    transactions: "transactions"
  }
};
