import type { CountryTranslation } from "@/lib/i18n/translation";

const REGIONS = [
  "Piedmont", "Aosta Valley", "Lombardy", "Trentino-Alto Adige", "Veneto", "Friuli-Venezia Giulia", "Liguria", "Emilia-Romagna",
  "Tuscany", "Umbria", "Marche", "Lazio", "Abruzzo", "Molise", "Campania", "Apulia", "Basilicata", "Calabria", "Sicily", "Sardinia",
].map((name) => ({ name }));

/** English translation of data/italy — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "2811e1e53bdc",
  capital: "Rome",
  geography: {
    headline: "A mountainous peninsula, surrounded by the Mediterranean on three sides",
    highestPoint: {
      name: "Mont Blanc (Italian side)"
    },
    borderingCountries: [
      "France",
      "Switzerland",
      "Austria",
      "Slovenia",
      "San Marino",
      "Vatican City"
    ],
    climate: "Mediterranean climate on the coasts and in the south, more continental in the Po Valley, alpine in the northern mountains.",
    summary: "Italy forms a long peninsula reaching into the Mediterranean, bordered by the Tyrrhenian, Ionian and Adriatic seas. Its terrain is dominated by the Alps in the north and the Apennines, which run the length of the peninsula, with the vast Po Valley in the north."
  },
  population: {
    total: {
      note: "Resident population as of December 31, 2025."
    },
    summary: "Italy's population is broadly stable, supported by net migration that offsets a negative natural balance. It is concentrated in the large northern metropolitan areas (Milan, Turin) and around Rome and Naples, while the Apennine interior remains sparsely populated."
  },
  languages: {
    entries: [
      {
        name: "Italian",
        note: "Official language of the Republic, enshrined by Law No. 482/1999 on the protection of historical linguistic minorities."
      },
      {
        name: "German, French, Slovene, Sardinian, Friulian, Ladin, Occitan, Albanian, Greek, Catalan…",
        note: "Twelve historical minority languages are legally protected. German is co-official in the province of Bolzano, French in the Aosta Valley."
      }
    ],
    summary: "Italian is the only official language at national level. The 1999 law on historical linguistic minorities grants local co-official status to German (South Tyrol) and French (Aosta Valley), and protects several other regional languages."
  },
  religion: {
    surveyName: "Censis survey",
    ageScope: "Italian population, survey conducted from September 27 to October 1, 2024",
    points: [
      {
        label: "Catholic (of which 15.3% practising)"
      },
      {
        label: "Other beliefs or no declared religion"
      }
    ],
    summary: "According to a Censis survey (2024), 71.1% of respondents in Italy identify as Catholic — 15.3% regularly practising, 34.9% occasionally practising and 20.9% non-practising.",
    methodologyNote: "These figures are based on self-declared affiliation at a given time and do not break down other faiths in detail (Islam and non-Catholic Christian minorities account for a notable share of the immigrant population). They do not measure actual practice, which is far lower than declared affiliation."
  },
  politics: {
    stateForm: "Republic",
    regime: "Parliamentary republic",
    headOfState: {
      title: "President of the Republic",
      name: "Sergio Mattarella",
      since: "February 3, 2015 (re-elected in 2022)"
    },
    headOfGovernment: {
      title: "President of the Council of Ministers",
      name: "Giorgia Meloni",
      since: "October 22, 2022"
    },
    legislature: {
      name: "Parliament",
      chambers: [
        {
          name: "Chamber of Deputies"
        },
        {
          name: "Senate of the Republic"
        }
      ]
    },
    constitution: {
      adopted: "January 1, 1948"
    },
    summary: "Italy has been a parliamentary republic since the referendum of June 2, 1946, which ended the monarchy. The President of the Republic, elected by Parliament, acts as institutional guarantor, while executive power is exercised by the government, accountable to both chambers."
  },
  economy: {
    currency: {
      name: "Euro"
    },
    gdp: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    gdpPerCapita: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    unemploymentRate: {
      note: "2025 annual average."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry and agriculture"
      },
      {
        name: "Construction"
      }
    ],
    indicators: [],
    summary: "The world's eighth-largest economy, Italy relies on a developed service economy and a powerful manufacturing industry — machinery, cars, fashion and food — built around many small and medium-sized companies, especially in the north of the country."
  },
  history: {
    intro: "A few milestones to place the major stages in the country's formation and transformation — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Antiquity",
        summary: "From the legendary founding of Rome to the fall of the Western Roman Empire, this period saw the rise of a city-state that unified the peninsula and then dominated the whole Mediterranean basin.",
        events: [
          {
            date: "753 BC",
            title: "Legendary founding of Rome",
            description: "The traditional date of Rome's founding, used by the ancient authors themselves."
          },
          {
            date: "509 BC",
            title: "Establishment of the Roman Republic",
            description: "End of Etruscan kingship and establishment of a republican regime in Rome."
          },
          {
            date: "27 BC",
            title: "Beginning of the Empire",
            description: "Octavian receives the title of Augustus, marking the beginning of the Roman Empire."
          },
          {
            date: "476",
            title: "Fall of the Western Roman Empire",
            description: "Deposition of the last Western emperor, Romulus Augustulus."
          }
        ]
      },
      {
        title: "Middle Ages",
        summary: "The peninsula fragmented into kingdoms, city-states and papal territories; the merchant republics (Venice, Genoa, Florence) and the papacy became major powers.",
        events: [
          {
            date: "756",
            title: "Birth of the Papal States",
            description: "The Frankish king Pepin the Short donates territories to the pope, founding the papacy's temporal power."
          },
          {
            date: "11th – 13th century",
            title: "Rise of the city-states",
            description: "Venice, Genoa, Pisa and Florence become major commercial and political powers in the Mediterranean."
          }
        ]
      },
      {
        title: "Renaissance",
        summary: "The Italian peninsula became the centre of the artistic and intellectual Renaissance, while remaining politically divided and fought over by European powers.",
        events: [
          {
            date: "15th – 16th century",
            title: "Italian Renaissance",
            description: "Florence, Rome and Venice become major artistic centres (Leonardo da Vinci, Michelangelo, Raphael)."
          },
          {
            date: "1494 – 1559",
            title: "Italian Wars",
            description: "The peninsula becomes the battlefield of the rivalry between France and the Habsburgs."
          }
        ]
      },
      {
        title: "Unification & 19th century",
        summary: "The Risorgimento movement led to the political unification of the peninsula under a constitutional monarchy, after centuries of fragmentation.",
        events: [
          {
            date: "March 17, 1861",
            title: "Proclamation of the Kingdom of Italy",
            description: "Victor Emmanuel II becomes the first king of a unified Italy, at the end of the Risorgimento."
          },
          {
            date: "1870",
            title: "Annexation of Rome",
            description: "Rome, the last major papal territory, is annexed to the Kingdom of Italy and becomes its capital."
          }
        ]
      },
      {
        title: "20th century",
        summary: "The century was marked by the First World War, the rise and fall of the Fascist regime, and the advent of the Republic in 1946.",
        events: [
          {
            date: "1922",
            title: "March on Rome",
            description: "Benito Mussolini is appointed head of government, marking the beginning of the Fascist regime."
          },
          {
            date: "1940 – 1945",
            title: "Second World War",
            description: "Italy enters the war alongside Nazi Germany, then goes through the 1943 armistice and a civil war until the Liberation."
          },
          {
            date: "June 2, 1946",
            title: "Institutional referendum",
            description: "Italians vote to abolish the monarchy; the Republic is proclaimed."
          },
          {
            date: "January 1, 1948",
            title: "Constitution comes into force",
            description: "The republican Constitution comes into force, establishing the current institutional framework."
          },
          {
            date: "1957",
            title: "Treaty of Rome",
            description: "Italy is a founding member of the European Economic Community."
          }
        ]
      },
      {
        title: "Today",
        summary: "Italy remains a founding member state of the European Union, using the euro, and continues to adapt its institutions and economy.",
        events: [
          {
            date: "2002",
            title: "Euro notes and coins introduced",
            description: "Euro coins and banknotes replace the Italian lira in everyday transactions."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Food",
        title: "The art of the Neapolitan pizzaiuolo",
        description: "The art of Neapolitan pizzaiuoli has been inscribed since 2017 on UNESCO's list of the Intangible Cultural Heritage of Humanity, for the skilled gestures and social ritual that surround it in Naples.",
        examples: [
          "Pizza margherita",
          "Pizza marinara"
        ]
      },
      {
        category: "Celebrations",
        title: "Festa della Repubblica",
        description: "Celebrated on June 2, it commemorates the 1946 referendum that established the Italian Republic.",
        examples: [
          "Military parade in Rome (Via dei Fori Imperiali)",
          "Frecce Tricolori flypast"
        ]
      },
      {
        category: "Cinema",
        title: "The Venice Film Festival",
        description: "Founded in 1932, it is the oldest film festival in the world, known for its Golden Lion."
      },
      {
        category: "Heritage",
        title: "The world's largest UNESCO heritage",
        description: "With 62 inscribed sites in 2025, Italy is the country with the most properties on the UNESCO World Heritage List.",
        examples: [
          "Historic centre of Rome",
          "Venice and its lagoon",
          "Pompeii",
          "Historic centre of Florence",
          "Amalfi Coast"
        ]
      },
      {
        category: "Sport",
        title: "The Giro d'Italia",
        description: "Created in 1909, the Tour of Italy cycle race is one of the three Grand Tours of the world calendar, alongside the Tour de France and the Vuelta.",
        examples: [
          "Maglia rosa (pink jersey)"
        ]
      }
    ]
  },
  territories: {
    summary: "Italy is organised into regions, themselves divided into provinces and metropolitan cities, then into municipalities. Five regions (Aosta Valley, Trentino-Alto Adige, Friuli-Venezia Giulia, Sicily, Sardinia) have special status granting them greater autonomy.",
    divisions: [
      {
        name: "Regions",
        note: "Including 5 with special status."
      },
      {
        name: "Provinces and metropolitan cities",
        note: "Second-level administrative units, including 14 metropolitan cities."
      },
      {
        name: "Municipalities",
        note: "Comuni."
      }
    ],
    metropolitanRegions: REGIONS,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "Share of renewable energy in gross final energy consumption."
    },
    indicators: [
      {
        label: "Forest cover"
      }
    ],
    risks: [
      "Earthquakes",
      "Floods",
      "Landslides",
      "Volcanic eruptions"
    ],
    summary: "Located at the junction of the African and Eurasian plates, Italy is the European country most exposed to seismic and volcanic risk, and dissesto idrogeologico — landslides and floods — affects a large part of its territory. Its share of renewable energy remains below the European Union average."
  },
  keyFacts: [
    {
      title: "Two states enclosed within its territory",
      description: "Vatican City and the Republic of San Marino are both entirely enclosed within Italian territory — two of the smallest states in the world."
    },
    {
      title: "Three active volcanoes under constant watch",
      description: "Etna, Vesuvius and Stromboli are among the most active and most closely monitored volcanoes in the world, a direct consequence of Italy's position at the junction of the African and Eurasian plates."
    },
    {
      title: "The oldest population in the European Union",
      description: "With a median age of 48.7 years as of January 1, 2024, Italy has the oldest population in the EU, the result of a persistently low birth rate."
    },
    {
      title: "The world's largest wine exporter",
      description: "With 21.6 million hectolitres exported in 2023, Italy is the world's largest wine exporter by volume, ahead of Spain and France."
    },
    {
      title: "The country with the most EU-protected specialities",
      description: "Italy ranks first in the European Union for the number of food and wine products with a protected geographical indication (PDO/PGI), with more than 850 recognised specialities in 2024."
    },
    {
      title: "The second-highest public debt in the euro area",
      description: "With public debt equal to 135.3% of GDP at the end of 2024, Italy ranks second in the euro area for public debt, behind Greece."
    }
  ],
  cities: [
    {
      name: "Rome"
    },
    {
      name: "Milan"
    },
    {
      name: "Naples"
    },
    {
      name: "Turin"
    },
    {
      name: "Palermo"
    },
    {
      name: "Genoa"
    },
    {
      name: "Bologna"
    },
    {
      name: "Florence"
    },
    {
      name: "Bari"
    },
    {
      name: "Catania"
    }
  ],
  rivers: [
    {
      name: "Po",
      source_location: "Monviso (Cottian Alps)",
      mouth: "Adriatic Sea (Po delta)"
    },
    {
      name: "Adige",
      source_location: "Alps, Reschen Pass (province of Bolzano)",
      mouth: "Adriatic Sea"
    },
    {
      name: "Tiber",
      source_location: "Monte Fumaiolo (Tuscan-Romagnol Apennines)",
      mouth: "Tyrrhenian Sea, near Rome"
    }
  ],
  regions: REGIONS,
  sources: {
    "Banca d'Italia": "Bank of Italy",
    "Biennale di Venezia": "Venice Biennale",
    Censis: "Censis",
    "Dipartimento della Protezione Civile": "Italian Civil Protection Department",
    ISPRA: "ISPRA",
    ISTAT: "ISTAT",
    "Istituto Geografico Militare": "Italian Military Geographic Institute",
    "Istituto Nazionale di Geofisica e Vulcanologia": "National Institute of Geophysics and Volcanology",
    "Organisation internationale de la vigne et du vin (OIV)": "International Organisation of Vine and Wine (OIV)",
    "Presidenza della Repubblica": "Presidency of the Italian Republic",
    "RCS Sport": "RCS Sport",
    "Rapporto Ismea-Qualivita": "Ismea-Qualivita Report",
    "Treccani — Enciclopedia": "Treccani Encyclopedia"
  }
};
