import type { CountryTranslation } from "@/lib/i18n/translation";

const COUNTIES = [
  "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo-Marakwet", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado", "Kakamega",
  "Kericho", "Kiambu", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu", "Machakos", "Makueni",
  "Mandera", "Marsabit", "Meru", "Migori", "Mombasa", "Murang'a", "Nairobi", "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua",
  "Nyeri", "Samburu", "Siaya", "Taita-Taveta", "Tana River", "Tharaka-Nithi", "Trans-Nzoia", "Turkana", "Uasin Gishu", "Vihiga",
  "Wajir", "West Pokot",
].map((name) => ({ name }));

/** English translation of data/kenya — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "dd12aba894d9",
  capital: "Nairobi",
  geography: {
    headline: "From the shores of the Indian Ocean to the highlands of the Rift Valley, straddling the equator",
    areaKm2: {
      note: "Including about 11,000 km² of inland water, mainly the Kenyan part of Lakes Victoria and Turkana."
    },
    highestPoint: {
      name: "Mount Kenya (Batian)"
    },
    borderingCountries: [
      "Ethiopia",
      "Somalia",
      "Tanzania",
      "Uganda",
      "South Sudan"
    ],
    climate: "A tropical climate moderated by altitude: hot and humid on the Indian Ocean coast, temperate in the central and western highlands, home to Nairobi and the farming regions, and arid to semi-arid in the north and east, which cover more than four-fifths of the territory. Rain falls in two seasons, the \"long rains\" from March to May and the \"short rains\" from October to December.",
    summary: "Crossed through its middle by the equator, Kenya stretches from the beaches and reefs of the Indian Ocean to Lake Victoria, the largest lake in Africa. The Rift Valley cuts through it from north to south, dotted with volcanoes and lakes, while the fertile highlands on either side, dominated by Mount Kenya, the continent's second-highest peak, hold most of the population and agriculture. The arid north and east are the domain of nomadic herders. The southern savannahs, such as the Masai Mara, are home to one of the highest concentrations of large wildlife in the world."
  },
  population: {
    total: {
      note: "Estimate; the last census, in 2019, counted 47,564,296 inhabitants."
    },
    density: {
      note: "Very unevenly distributed: more than 1,000 people/km² in the western counties near Lake Victoria, fewer than 20 in the arid north."
    },
    summary: "Kenya's population is young and growing fast, even though fertility has fallen sharply since the 1980s. Two-thirds of the inhabitants still live in the countryside, mainly in the highlands and around Lake Victoria, but Nairobi and its outskirts are growing very quickly. The country has more than 40 ethnic groups; the largest are the Kikuyu, Luhya, Kalenjin, Luo and Kamba, and ethnicity weighs heavily in political life. Kenya also hosts more than 800,000 refugees, mainly Somali and South Sudanese, in the Dadaab and Kakuma camps."
  },
  languages: {
    entries: [
      {
        name: "Swahili (Kiswahili)",
        note: "National and official language under the 2010 Constitution, spoken as a common language throughout the country and across much of East Africa."
      },
      {
        name: "English",
        note: "Official language inherited from British colonisation; the language of Parliament, the courts, secondary and higher education and business."
      },
      {
        name: "Ethnic languages (Kikuyu, Luhya, Kalenjin, Luo, Kamba…)",
        note: "More than 60 Bantu, Nilotic and Cushitic languages, spoken at home and locally; none is a majority language nationally."
      },
      {
        name: "Sheng",
        note: "An urban slang born in Nairobi that mixes Swahili, English and local languages, now the language of urban youth and popular music."
      }
    ],
    summary: "Kenya is a multilingual country where most people speak at least three languages: their mother tongue, Swahili, the national language and the glue between communities, and English, the language of school, government and the economy. The 2010 Constitution made Swahili an official language on an equal footing with English and recognises Kenyan Sign Language."
  },
  religion: {
    surveyName: "Population and Housing Census",
    ageScope: "Total population",
    points: [
      {
        label: "Protestant"
      },
      {
        label: "Catholic"
      },
      {
        label: "Evangelical"
      },
      {
        label: "African independent churches"
      },
      {
        label: "Other Christian (including Orthodox)"
      },
      {
        label: "Muslim"
      },
      {
        label: "No religion"
      },
      {
        label: "Other religions and no answer"
      }
    ],
    summary: "Kenya is an overwhelmingly Christian country (85.5% of the population) with high levels of practice, where the historic Protestant churches, the Catholic Church and a growing number of evangelical and Pentecostal churches play a central role in social and political life. Muslims, about one Kenyan in ten, live mainly on the Swahili coast and in the north-east, populated by Somalis. The state is secular and the Constitution guarantees freedom of worship.",
    methodologyNote: "The \"Other religions and no answer\" category includes Hindus, traditional African religions, other beliefs and \"don't know\" answers (about 2% in total)."
  },
  politics: {
    stateForm: "Decentralised unitary republic",
    regime: "Presidential system",
    headOfState: {
      title: "President of the Republic of Kenya",
      name: "William Ruto",
      since: "September 13, 2022"
    },
    headOfGovernment: {
      title: "President of the Republic of Kenya",
      name: "William Ruto",
      since: "September 13, 2022"
    },
    legislature: {
      name: "Parliament",
      chambers: [
        {
          name: "National Assembly"
        },
        {
          name: "Senate"
        }
      ]
    },
    constitution: {
      adopted: "August 27, 2010, after approval by referendum on August 4, 2010"
    },
    summary: "Kenya is a presidential republic: the president, head of state and government, is elected by direct universal suffrage for five years, renewable once, and must win more than half the votes and at least 25% in half of the counties. The 2010 Constitution, adopted after the post-election violence of 2007–2008, created a Senate, an independent Supreme Court and 47 counties with elected governors. William Ruto, elected in 2022, governs with Deputy President Kithure Kindiki, appointed in 2024 after the impeachment of Rigathi Gachagua. His term has been marked by mass youth protests against the cost of living and police violence in 2024 and 2025. The next presidential election is scheduled for August 2027."
  },
  economy: {
    currency: {
      name: "Kenyan shilling"
    },
    gdp: {
      note: "Current US dollars."
    },
    gdpPerCapita: {
      note: "Current US dollars."
    },
    unemploymentRate: {
      note: "This rate hides very high underemployment: most workers are in the informal sector (\"jua kali\")."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Agriculture, forestry and fishing"
      },
      {
        name: "Industry (including construction)"
      }
    ],
    indicators: [],
    summary: "One of the two largest economies in East Africa along with Ethiopia, Kenya is a regional hub for finance, transport and digital services, nicknamed \"Silicon Savannah\" since the success of M-Pesa mobile payments. Agriculture still employs a large share of the population and provides the main exports: tea, of which the country is the world's largest exporter, cut flowers, coffee and fruit. Safari tourism and diaspora remittances are other major sources of foreign currency. Growth is solid, but the country faces high public debt, which led the government to highly contested tax rises in 2024."
  },
  history: {
    intro: "A few milestones to place the major stages in the building of the modern country — not an exhaustive summary of Kenyan history.",
    periods: [
      {
        title: "Swahili city-states and Indian Ocean trade",
        summary: "From the first millennium, trading city-states such as Lamu, Malindi and Mombasa emerged on the coast, where the Swahili culture took shape, blending Bantu, Arab and Persian traditions and largely Islamised. The Portuguese settled there in the 16th century, before being driven out by the Sultanate of Oman, then of Zanzibar. The interior remained the domain of farming and pastoral societies, linked by caravans to the ivory and slave trade.",
        events: [
          {
            date: "1498",
            title: "Vasco da Gama in Malindi",
            description: "The Portuguese navigator finds there the pilot who guides him to India."
          },
          {
            date: "1593",
            title: "Construction of Fort Jesus",
            description: "The Portuguese build a fortress in Mombasa, now a World Heritage site."
          }
        ]
      },
      {
        title: "British colonisation",
        summary: "The United Kingdom established a protectorate in 1895 and built the Uganda Railway, from Mombasa to Lake Victoria, along which Nairobi was born. After it became a Crown colony in 1920, the best land in the highlands, the \"White Highlands\", was reserved for European settlers, while Africans, especially the Kikuyu, were pushed into reserves and subjected to forced labour and taxation.",
        events: [
          {
            date: "July 1, 1895",
            title: "East Africa Protectorate",
            description: "London takes direct control of the territory, until then administered by a chartered company."
          },
          {
            date: "1899",
            title: "Founding of Nairobi",
            description: "A mere railway depot, the town becomes the colony's capital as early as 1907."
          }
        ]
      },
      {
        title: "The Mau Mau uprising and independence",
        summary: "The Mau Mau uprising, led mainly by Kikuyu deprived of their land, was crushed by the British army: more than 11,000 insurgents were killed and tens of thousands of Kenyans held in camps where torture was systematic. The repression did not halt the march to independence, achieved in 1963 under the leadership of Jomo Kenyatta.",
        events: [
          {
            date: "October 20, 1952",
            title: "State of emergency",
            description: "The colonial authorities declare a state of emergency and arrest Jomo Kenyatta, sentenced to seven years' hard labour."
          },
          {
            date: "December 12, 1963",
            title: "Independence",
            description: "Kenya becomes independent; it becomes a republic a year later, with Jomo Kenyatta as president."
          }
        ]
      },
      {
        title: "Kenyatta, Moi and the one-party state",
        summary: "Jomo Kenyatta (1964–1978) and then Daniel arap Moi (1978–2002) governed a stable, pro-Western but increasingly authoritarian country: KANU became the sole legal party in 1982. Under domestic and donor pressure, multiparty politics was restored in 1991, but Moi won the 1992 and 1997 elections, marred by fraud and violence.",
        events: [
          {
            date: "August 1, 1982",
            title: "Attempted coup",
            description: "A mutiny by air force officers fails; Moi tightens his regime."
          },
          {
            date: "August 7, 1998",
            title: "US embassy bombing",
            description: "Al-Qaeda kills more than 200 people in Nairobi, on the same day as an attack in Dar es Salaam."
          }
        ]
      },
      {
        title: "Change of power, post-election crisis and a new Constitution",
        summary: "The election of Mwai Kibaki in 2002 marked the first democratic change of power. His disputed re-election in December 2007 triggered inter-ethnic violence that killed more than 1,100 people and displaced hundreds of thousands. Mediation led by Kofi Annan produced a unity government with Raila Odinga as Prime Minister, and then the adoption by referendum of the 2010 Constitution.",
        events: [
          {
            date: "December 30, 2007",
            title: "Disputed announcement of the results",
            description: "The announcement of Kibaki's re-election over Raila Odinga triggers two months of violence."
          },
          {
            date: "August 4, 2010",
            title: "Constitutional referendum",
            description: "67% of voters approve a new Constitution that devolves power to 47 counties."
          }
        ]
      },
      {
        title: "The era of the counties and Gen Z",
        summary: "Uhuru Kenyatta, son of the first president, governed from 2013 to 2022, a period marked by attacks by Somalia's al-Shabaab and by the Supreme Court's annulment of the 2017 presidential election. William Ruto succeeded him in 2022. In June 2024, a finance bill raising taxes sparked mass youth protests, during which demonstrators stormed Parliament; the crackdown left dozens dead. Raila Odinga, a leading opposition figure for three decades, died in October 2025.",
        events: [
          {
            date: "September 21, 2013",
            title: "Westgate attack",
            description: "An al-Shabaab commando kills 67 people in a Nairobi shopping centre."
          },
          {
            date: "September 1, 2017",
            title: "Annulment of the presidential election",
            description: "For the first time in Africa, a Supreme Court overturns the re-election of a sitting president because of irregularities."
          },
          {
            date: "June 25, 2024",
            title: "Storming of Parliament",
            description: "Protesters break into Parliament; the next day President Ruto withdraws the finance bill."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list.",
    items: [
      {
        category: "Sport",
        title: "Long-distance running",
        description: "Kenyan runners, many from the Kalenjin highlands around Iten, have dominated middle-distance running and the marathon since the 1960s. Eliud Kipchoge was the first to run a marathon in under two hours, in Vienna in 2019, in a race not ratified as a record.",
        examples: [
          "Kipchoge Keino",
          "Eliud Kipchoge",
          "Faith Kipyegon",
          "David Rudisha"
        ]
      },
      {
        category: "Peoples and traditions",
        title: "Maasai and Samburu pastoral cultures",
        description: "Semi-nomadic herders of the south and centre of the country, the Maasai and Samburu have kept an age-set organisation, beadwork and rites of passage such as Eunoto, the young warriors' ceremony inscribed by UNESCO on its list of Intangible Cultural Heritage in Need of Urgent Safeguarding.",
        examples: [
          "Age sets",
          "Shuka (red cloth)",
          "Beadwork"
        ]
      },
      {
        category: "Heritage",
        title: "Lamu Old Town",
        description: "The oldest Swahili town in East Africa still inhabited, Lamu has kept its coral-stone and carved-wood houses, its car-free alleys where donkeys roam and its dhows; it has been a World Heritage site since 2001.",
        examples: [
          "Carved doors",
          "Dhows",
          "Lamu Cultural Festival"
        ]
      },
      {
        category: "Literature",
        title: "Ngũgĩ wa Thiong'o and writing in African languages",
        description: "Imprisoned without trial in 1977–1978, Ngũgĩ wa Thiong'o (1938–2025) abandoned English to write in Kikuyu and became one of the great champions of African languages in literature. Kenya has also produced other major voices, such as Binyavanga Wainaina.",
        examples: [
          "A Grain of Wheat",
          "Petals of Blood",
          "Decolonising the Mind"
        ]
      },
      {
        category: "Music",
        title: "Benga and urban music",
        description: "Born in the 1960s among the Luo around Lake Victoria, benga, with its fast guitars, is Kenya's quintessential popular music. Nairobi's youth today listen to genge, gengetone and Afropop, often sung in Sheng.",
        examples: [
          "D. O. Misiani",
          "Sauti Sol",
          "Ethic Entertainment"
        ]
      },
      {
        category: "Food",
        title: "Ugali, nyama choma and chai",
        description: "Ugali, a maize-flour porridge, accompanies most meals with sukuma wiki (sautéed greens). Grilled meat, or nyama choma, is shared among friends, and chai, spiced milk tea, is drunk at any time of day; on the coast, Swahili cuisine favours pilau rice and coconut.",
        examples: [
          "Ugali",
          "Nyama choma",
          "Sukuma wiki",
          "Pilau",
          "Chai"
        ]
      }
    ]
  },
  territories: {
    summary: "Since the 2010 Constitution, applied from the 2013 elections, Kenya has been divided into 47 counties, each with an elected governor and assembly, which manage healthcare, agriculture and local roads among other things. They replaced the eight provinces inherited from colonial times. In the north-west, Kenya administers de facto the Ilemi Triangle, an area of about 10,000 to 14,000 km² also claimed by South Sudan; the two countries have begun talks to settle this border dispute.",
    divisions: [
      {
        name: "Counties"
      },
      {
        name: "Sub-counties",
        note: "Correspond to the National Assembly constituencies."
      },
      {
        name: "Wards"
      }
    ],
    metropolitanRegions: COUNTIES,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "Share of renewable energy in electricity generation: geothermal, hydro, wind and solar."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Access to electricity"
      }
    ],
    risks: [
      "Recurring droughts",
      "Floods",
      "Desert locust invasions",
      "Deforestation and soil degradation"
    ],
    summary: "Kenya generates most of its electricity from renewable sources, notably geothermal power from the Rift Valley, of which it is Africa's leading producer, and the Lake Turkana wind farm, the largest on the continent when it came online in 2019. The country is, however, highly exposed to climate change: the 2020–2023 drought, the worst in forty years, decimated the livestock of herders in the north, before deadly floods in 2024. Nobel laureate Wangari Maathai brought the fight against deforestation to wide attention with her Green Belt Movement."
  },
  keyFacts: [
    {
      title: "The country that invented banking by text message",
      description: "Launched in 2007 by Safaricom, M-Pesa lets people send and receive money with a simple mobile phone; it has become the country's main means of payment and has been copied around the world."
    },
    {
      title: "The world's largest tea exporter",
      description: "Grown in the highlands of Kericho and the foothills of Mount Kenya, Kenyan black tea is the most exported in the world and one of the country's leading sources of foreign currency."
    },
    {
      title: "A marathon in under two hours",
      description: "On October 12, 2019 in Vienna, Eliud Kipchoge ran the 42.195 km in 1 h 59 min 40 s, a first in history, in a specially organised race not ratified as a record."
    },
    {
      title: "Africa's first woman Nobel Peace laureate",
      description: "Wangari Maathai, founder of the Green Belt Movement, which planted more than 30 million trees, received the Nobel Peace Prize in 2004."
    },
    {
      title: "A Supreme Court that annulled a presidential election",
      description: "In 2017 Kenya's Supreme Court overturned Uhuru Kenyatta's re-election because of irregularities, a first on the African continent; the vote was rerun two months later."
    },
    {
      title: "Africa's leading producer of geothermal electricity",
      description: "The Olkaria power plants, in the heart of the Rift Valley, make Kenya the continent's leading producer of geothermal energy; this source supplies nearly half of its electricity."
    }
  ],
  cities: [
    {
      name: "Nairobi",
      population: {
        note: "Nairobi County, which coincides with the city; home to many international organisations, including the United Nations Environment Programme."
      }
    },
    {
      name: "Mombasa",
      population: {
        note: "East Africa's largest port, the maritime gateway for Uganda, Rwanda and South Sudan."
      }
    },
    {
      name: "Nakuru"
    },
    {
      name: "Eldoret"
    },
    {
      name: "Kisumu",
      population: {
        note: "Kenya's main city on the shores of Lake Victoria."
      }
    },
    {
      name: "Lamu"
    }
  ],
  rivers: [
    {
      name: "Tana",
      lengthKm: {
        note: "Kenya's longest river; a series of dams on its upper course, the \"Seven Forks\", supplies much of the country's hydroelectricity and Nairobi's water."
      },
      source_location: "Aberdare Range, west of Mount Kenya",
      mouth: "Indian Ocean, Formosa (Ungwana) Bay, near Kipini"
    },
    {
      name: "Athi-Galana-Sabaki",
      lengthKm: {
        note: "The country's second river, which changes name three times; it flows through the Nairobi metropolitan area, whose wastewater it receives, then through Tsavo National Park."
      },
      source_location: "Highlands south-west of Nairobi (Ngong Hills)",
      mouth: "Indian Ocean, north of Malindi"
    },
    {
      name: "Ewaso Ng'iro",
      lengthKm: {
        note: "A vital river for herders and wildlife in the Samburu and Buffalo Springs reserves; it disappears into the Lorian Swamp, often dry, without reaching the sea."
      },
      source_location: "Western slopes of Mount Kenya and the Aberdare Range",
      mouth: "Lorian Swamp (endorheic basin), in the north-east"
    },
    {
      name: "Mara",
      lengthKm: {
        note: "A river shared with Tanzania, famous for the spectacular crossings of wildebeest and zebras during the Great Migration in the Masai Mara reserve."
      },
      source_location: "Mau Escarpment, in the Rift Valley",
      mouth: "Lake Victoria, at Musoma (Tanzania)"
    },
    {
      name: "Nzoia",
      lengthKm: {
        note: "One of the main Kenyan tributaries of Lake Victoria, often causing floods in the Budalangi area."
      },
      source_location: "Mount Elgon and the Cherangani Hills",
      mouth: "Lake Victoria, near Port Victoria"
    }
  ],
  regions: COUNTIES,
  sources: {
    "Constitution du Kenya (2010), premier tableau annexé": "Constitution of Kenya (2010), First Schedule",
    "IEBC (commission électorale)": "IEBC (electoral commission)",
    "KNBS (recensement 2019)": "KNBS (2019 census)",
    "KNBS / Wikipedia": "KNBS / Wikipedia",
    "Kenya Law": "Kenya Law",
    "Kenya National Bureau of Statistics (KNBS)": "Kenya National Bureau of Statistics (KNBS)",
    "Kenya National Bureau of Statistics (KNBS), recensement 2019": "Kenya National Bureau of Statistics (KNBS), 2019 census",
    "Présidence de la République du Kenya": "Presidency of the Republic of Kenya"
  }
};
