// Generates (or refreshes) the English translation file of a country:
// data/<slug>/en.ts, holding every French text string of the country that
// needs translating, in the same shape as the source data.
//
// Usage: npx tsx scripts/i18n/extract-translation.ts <slug> [<slug>…]
//
// - Strings already translated in an existing en.ts are kept (matched by path),
//   so the script can be re-run after the French data changes: new or moved
//   text shows up in French, ready to translate.
// - Bordering-country names and the nuclear-share label are pre-filled from the
//   registry / dictionary, since they must match them exactly.
// - `source` and `unit` strings missing from lib/i18n/glossary-en.ts are listed
//   once in `sources` / `units`.
// - `sourceHash` fingerprints the French text; `npm run validate:data` warns when
//   the French data has changed since the translation was last refreshed.
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { FULL_COUNTRIES } from "../../data/countries-full";
import { COUNTRIES } from "../../data/countries-registry";
import { TRANSLATIONS } from "../../data/translations";
import { COUNTRY_NAMES_EN } from "../../lib/i18n/country-names-en";
import { SHARED_GLOSSARY_EN } from "../../lib/i18n/glossary-en";
import { getDictionary } from "../../lib/i18n";
import { GLOSSARY_KEYS, NON_TEXT_KEYS } from "../../lib/i18n/translation";
import { translatableSource, sourceTextHash } from "./source-text";

const ROOT = path.resolve(import.meta.dirname, "../..");

function englishBorderName(frName: string): string | undefined {
  const match = COUNTRIES.find((c) => c.name === frName);
  return match ? COUNTRY_NAMES_EN[match.slug]?.name : undefined;
}

function skeleton(base: unknown, existing: unknown, pathKey: string, glossary: { sources: Set<string>; units: Set<string> }): unknown {
  if (Array.isArray(base)) {
    const ex = Array.isArray(existing) ? existing : [];
    return base.map((item, i) => {
      if (pathKey === "geography.borderingCountries" && typeof item === "string") {
        return englishBorderName(item) ?? (typeof ex[i] === "string" ? ex[i] : item);
      }
      return skeleton(item, ex[i], pathKey, glossary) ?? {};
    });
  }
  if (base && typeof base === "object") {
    const ex = (existing && typeof existing === "object" ? existing : {}) as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(base)) {
      if (key in GLOSSARY_KEYS) {
        if (typeof value !== "string" || !value) continue;
        if (key === "source" && SHARED_GLOSSARY_EN.sources[value] === undefined) glossary.sources.add(value);
        if (key === "unit" && SHARED_GLOSSARY_EN.units[value] === undefined) glossary.units.add(value);
        continue;
      }
      if (NON_TEXT_KEYS.has(key)) continue;
      const child = skeleton(value, ex[key], pathKey ? `${pathKey}.${key}` : key, glossary);
      if (child !== undefined) out[key] = child;
    }
    return Object.keys(out).length ? out : undefined;
  }
  if (typeof base === "string" && base.trim()) {
    if (pathKey === "environment.indicators.label" && base === getDictionary("fr").metrics.nuclearShare) {
      return getDictionary("en").metrics.nuclearShare;
    }
    return typeof existing === "string" ? existing : base;
  }
  return undefined;
}

/** JSON with unquoted identifier keys, to read like the rest of data/. */
function toTs(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/^(\s*)"([A-Za-z_$][\w$]*)":/gm, "$1$2:");
}

function extract(slug: string) {
  const country = FULL_COUNTRIES[slug];
  if (!country) throw new Error(`Pays inconnu ou sans données complètes : "${slug}".`);
  const existing = TRANSLATIONS.en[slug];
  const glossary = { sources: new Set<string>(), units: new Set<string>() };
  const body = skeleton(translatableSource(country), existing, "", glossary) as Record<string, unknown>;

  const pick = (keys: Set<string>, prev: Record<string, string> | undefined) =>
    Object.fromEntries([...keys].sort().map((k) => [k, prev?.[k] ?? k]));
  const sources = pick(glossary.sources, existing?.sources);
  const units = pick(glossary.units, existing?.units);

  const file = `import type { CountryTranslation } from "@/lib/i18n/translation";

/** English translation of data/${slug} — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = ${toTs({
    sourceHash: sourceTextHash(country),
    ...body,
    ...(Object.keys(sources).length ? { sources } : {}),
    ...(Object.keys(units).length ? { units } : {}),
  })};
`;
  const target = path.join(ROOT, "data", slug, "en.ts");
  writeFileSync(target, file);
  console.log(`${existsSync(target) ? "✓" : "?"} data/${slug}/en.ts (${glossary.sources.size} source(s), ${glossary.units.size} unité(s) hors glossaire)`);
}

const slugs = process.argv.slice(2);
if (!slugs.length) {
  console.error("Usage: npx tsx scripts/i18n/extract-translation.ts <slug> [<slug>…]");
  process.exit(1);
}
slugs.forEach(extract);
