import type { CountryTranslation } from "@/lib/i18n/translation";

const PREFECTURES = [
  "Hokkaidō", "Aomori", "Iwate", "Miyagi", "Akita", "Yamagata", "Fukushima", "Ibaraki", "Tochigi", "Gunma", "Saitama", "Chiba",
  "Tokyo", "Kanagawa", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi", "Nagano", "Gifu", "Shizuoka", "Aichi", "Mie",
  "Shiga", "Kyōto", "Ōsaka", "Hyōgo", "Nara", "Wakayama", "Tottori", "Shimane", "Okayama", "Hiroshima", "Yamaguchi",
  "Tokushima", "Kagawa", "Ehime", "Kōchi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto", "Ōita", "Miyazaki", "Kagoshima", "Okinawa",
].map((name) => ({ name }));

/** English translation of data/japon — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "33e2ab6056b2",
  capital: "Tokyo",
  geography: {
    headline: "A mountainous archipelago of more than 14,000 islands, stretching nearly 3,000 km along the Pacific Ring of Fire",
    coastlineKm: {
      note: "The world's sixth-longest coastline, a direct result of the archipelago being split into more than 14,000 islands."
    },
    highestPoint: {
      name: "Mount Fuji"
    },
    borderingCountries: [],
    climate: "Stretching far from north to south, the country has contrasting climates: snowy winters and short summers in Hokkaidō, four distinct seasons across most of Honshū, Shikoku and Kyūshū with a rainy season (tsuyu) in early summer, and a humid subtropical climate in the Ryūkyū Islands (Okinawa). The archipelago is also highly exposed to typhoons between summer and autumn.",
    summary: "Japan is an archipelago of more than 14,000 islands, four of which — Honshū, Hokkaidō, Kyūshū and Shikoku — account for most of the territory and population; to the south-west it ends in the chain of the Ryūkyū Islands, including Okinawa. More than 70% of the terrain is mountainous, leaving few habitable plains, where most of the population is nevertheless concentrated. Located on the Pacific Ring of Fire, at the junction of several tectonic plates, the country has 111 active volcanoes and intense seismic activity, causing recurring earthquakes and tsunamis. Japan also claims several territories without a civilian population under Japanese administration, disputed with its neighbours: the southern Kuril Islands (the \"Northern Territories\") with Russia, the Liancourt Rocks (Takeshima/Dokdo) with South Korea, and the Senkaku Islands (Diaoyu) with China and Taiwan."
  },
  population: {
    total: {
      note: "Monthly estimate; the world's eleventh-largest population, steadily declining since a peak of about 128 million reached in 2008–2010."
    },
    growthRate: {
      note: "Continuous natural decline since 2010, only slightly offset by labour immigration."
    },
    medianAge: {
      note: "The second-highest median age in the world, after Monaco."
    },
    urbanShare: {
      note: "Last decennial census detailing the urban/rural split; since then the population has remained overwhelmingly concentrated in the large coastal metropolitan areas."
    },
    summary: "Since the mid-2000s Japan has been in continuous demographic decline, the result of a persistently low birth rate and rapid population ageing: more than one in three inhabitants is now over 65. The population remains concentrated on the narrow coastal strip and the plains of Honshū, especially around the Tokyo megalopolis, one of the most populous urban areas in the world with nearly 37 million inhabitants, while vast rural and mountainous areas are emptying."
  },
  languages: {
    entries: [
      {
        name: "Japanese",
        note: "No law explicitly grants it \"official language\" status at national level, but standard Japanese (based on the Tokyo dialect) is de facto the sole language of government, education and the media."
      },
      {
        name: "Ryukyuan languages",
        note: "A group of languages distinct from Japanese (not mutually intelligible with it), spoken in the Ryūkyū Islands (Okinawa); classified as endangered by UNESCO because of schooling in standard Japanese since the Meiji era."
      },
      {
        name: "Ainu",
        note: "A language isolate, historically spoken by the Ainu people of Hokkaidō, recognised as an Indigenous people of Japan by a 2019 law; classified as critically endangered by UNESCO, with an extremely small number of native speakers today."
      },
      {
        name: "Korean",
        note: "Spoken by part of the Zainichi minority (Koreans in Japan and their descendants, about 0.4 to 0.5% of the population), largely descended from immigration and labour transfers during the colonial period (1910–1945)."
      }
    ],
    summary: "Japanese, without official language status written into law, is unchallenged in the country's public and administrative life. The archipelago is nevertheless more linguistically diverse than it appears: the Ryukyuan languages of Okinawa and Ainu in Hokkaidō, both threatened with extinction, bear witness to the distinct history of regions annexed later by the modern Japanese state, while English is rarely spoken day to day despite being taught universally."
  },
  religion: {
    surveyName: "Global Attitudes Survey (Pew Research Center)",
    ageScope: "Adults (18 and over), self-identification",
    points: [
      {
        label: "Buddhism"
      },
      {
        label: "No religion"
      },
      {
        label: "Christianity"
      },
      {
        label: "Other religions (including Shinto as an exclusive identity)"
      },
      {
        label: "Don't know / no answer"
      }
    ],
    summary: "The vast majority of Japanese people do not identify with any single religion, while routinely taking part in Shinto rites (shrine visits at New Year, weddings) and Buddhist rites (funerals, ancestor festivals), the two traditions having coexisted for centuries without excluding each other. Christianity, introduced by Portuguese missionaries in the 16th century and then brutally suppressed for more than two centuries, remains a minority faith but has left a lasting mark, especially around Nagasaki.",
    methodologyNote: "Japanese religious statistics vary greatly depending on the method: the official counts of the Agency for Cultural Affairs, based on membership registers declared by shrines and temples, add up to about 70% \"Shinto\" and 70% \"Buddhist\" (a total well above 100%, because of overlapping, non-exclusive institutional affiliations), whereas individual self-identification surveys like this one show a majority of people saying they have no religion."
  },
  politics: {
    stateForm: "Constitutional monarchy",
    regime: "Parliamentary monarchy",
    headOfState: {
      title: "Emperor",
      name: "Naruhito",
      since: "May 1, 2019"
    },
    headOfGovernment: {
      title: "Prime Minister",
      name: "Sanae Takaichi",
      since: "October 21, 2025"
    },
    legislature: {
      name: "National Diet (Kokkai)",
      chambers: [
        {
          name: "House of Representatives"
        },
        {
          name: "House of Councillors"
        }
      ]
    },
    constitution: {
      adopted: "Promulgated on November 3, 1946, in force since May 3, 1947"
    },
    summary: "Japan is a parliamentary constitutional monarchy in which the Emperor's role has been strictly limited since the 1947 Constitution. Its Article 1 defines the Emperor as \"the symbol of the State and of the unity of the people\", and Article 4 states that he \"shall not have powers related to government\": he merely performs ceremonial acts in matters of state — promulgating laws, convening the Diet, formally appointing the Prime Minister designated by Parliament — on the mandatory advice and approval of the Cabinet, with no personal discretion. This is a clear break with the Meiji Constitution of 1889, which made the Emperor a \"sacred and inviolable\" sovereign. Executive power belongs entirely to the Prime Minister and the Cabinet, accountable to the National Diet, whose politics have been dominated since 1955 by the Liberal Democratic Party (LDP), apart from two brief interruptions (1993–1994 and 2009–2012)."
  },
  economy: {
    currency: {
      name: "Japanese yen"
    },
    gdp: {
      note: "Current US dollars; the world's fourth-largest economy by nominal GDP, after being overtaken by Germany in 2024 because of the weak yen."
    },
    gdpPerCapita: {
      note: "Current US dollars."
    },
    unemploymentRate: {
      note: "Among the lowest unemployment rates of the advanced economies, structurally held down by ageing and a shrinking workforce."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry"
      },
      {
        name: "Agriculture"
      }
    ],
    indicators: [
      {
        label: "Public debt",
        value: {
          note: "One of the highest ratios in the world, but very largely held by domestic creditors."
        }
      }
    ],
    summary: "Driven by a spectacular post-war industrial recovery — the \"economic miracle\" of 1955–1990 — the Japanese economy remains a leading manufacturing and technology power in cars, electronics and robotics. Since the speculative bubble burst in 1991, however, it has gone through several \"lost decades\" of sluggish growth and persistent deflation, before a return to more conventional inflation in the 2020s along with a marked weakening of the yen. It has to cope with the most pronounced ageing of all the major economies and one of the highest public debts in the world, partly financed by abundant domestic savings."
  },
  history: {
    intro: "A few milestones to place the major stages in the building of modern Japan — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Ancient Japan, the imperial court and the feudal shogunates",
        summary: "After the Jōmon and then Yayoi cultures, a unified state emerged under the Yamato clan; the court of Nara and then Heian (8th–12th century), strongly influenced by China, later ceded real power to military shoguns. Three shogunates followed: Kamakura (1185–1333), Muromachi (1338–1573), marked by civil wars (the Sengoku period), and then Tokugawa (1603–1868), which imposed two and a half centuries of peace under a regime of almost total isolation (sakoku). The Emperor, withdrawn to Kyoto, kept only symbolic authority.",
        events: []
      },
      {
        title: "The Meiji era: imperial restoration and rapid modernisation",
        summary: "The squadron of American Commodore Matthew Perry forced Japan open in 1853 and precipitated the fall of the shogunate. The Meiji Restoration of 1868 launched sweeping modernisation — industry, army, schools, a Constitution in 1889 — that made Japan the first non-Western industrial power, soon engaged in colonial expansion.",
        events: [
          {
            date: "January 3, 1868",
            title: "Meiji Restoration",
            description: "Young reformist samurai overthrow the Tokugawa shogunate and formally restore the Emperor's power."
          },
          {
            date: "1904-1905",
            title: "Russo-Japanese War",
            description: "After a first victory over China (1894–1895), Japan defeats the Russian Empire: the first defeat of a major European power by an Asian state in the modern era."
          },
          {
            date: "August 22, 1910",
            title: "Annexation of Korea",
            description: "Japan formally annexes Korea, which remains a Japanese colony until 1945."
          }
        ]
      },
      {
        title: "Militarism, imperial expansion and the Second World War",
        summary: "After a brief democratic opening in the Taishō era (1912–1926), the army took an increasingly large place in political life from the 1930s. Expansion into China and then the Pacific War ended in 1945 with the atomic bombings and surrender.",
        events: [
          {
            date: "September 18, 1931",
            title: "Mukden Incident and invasion of Manchuria",
            description: "A bombing staged by the Japanese army serves as a pretext for the invasion of Manchuria, where the puppet state of Manchukuo is set up."
          },
          {
            date: "July 7, 1937",
            title: "Start of the Second Sino-Japanese War",
            description: "The Marco Polo Bridge incident, near Beijing, triggers all-out war against China, marked by mass atrocities against civilians, including the Nanjing Massacre (December 1937–March 1938): most historians put the death toll at 100,000 to 200,000."
          },
          {
            date: "December 7-8, 1941",
            title: "Attack on Pearl Harbor",
            description: "Japanese aircraft launch a surprise attack on the US Pacific Fleet, bringing the United States into the war."
          },
          {
            date: "August 6 and 9, 1945",
            title: "Atomic bombings of Hiroshima and Nagasaki",
            description: "The only two uses of nuclear weapons in armed conflict to date. Estimates put the deaths at 90,000 to 166,000 in Hiroshima and 60,000 to 80,000 in Nagasaki by the end of 1945, including deaths from radiation."
          },
          {
            date: "August 15 and September 2, 1945",
            title: "Surrender of Japan",
            description: "Emperor Hirohito announces the surrender by radio on August 15; the instrument of surrender is signed aboard the USS Missouri on September 2, 1945."
          }
        ]
      },
      {
        title: "Allied occupation, a new Constitution and the economic miracle",
        summary: "From 1945 to 1952 Japan was occupied by the Allies under the authority of General Douglas MacArthur: demilitarisation, land reform and a new pacifist Constitution. The Treaty of San Francisco (1951) restored sovereignty in 1952. The \"economic miracle\", driven by heavy industry and then electronics and cars, made Japan the world's second-largest economy from the 1960s–1970s until the speculative bubble of the late 1980s.",
        events: [
          {
            date: "May 3, 1947",
            title: "The pacifist Constitution comes into force",
            description: "Drafted under American supervision, it makes the Emperor a symbol without political power and renounces war in Article 9."
          },
          {
            date: "1964",
            title: "Tokyo Olympics and the first Shinkansen",
            description: "The first Olympic Games held in Asia coincide with the opening of the Tōkaidō Shinkansen, symbols of reconstruction."
          }
        ]
      },
      {
        title: "Contemporary Japan: lost decades, disasters and ageing",
        summary: "The bursting of the bubble in 1991 opened a long period of sluggish growth and deflation, the \"lost decades\". The country suffered major disasters, including the Fukushima Daiichi accident in 2011 — the worst since Chernobyl — which led to the temporary shutdown of almost the entire nuclear fleet.",
        events: [
          {
            date: "January 17, 1995",
            title: "Kobe earthquake",
            description: "The Great Hanshin-Awaji earthquake kills more than 6,000 people and exposes the weaknesses of earthquake-resistance standards."
          },
          {
            date: "March 11, 2011",
            title: "Tōhoku earthquake and tsunami, and the Fukushima nuclear accident",
            description: "A magnitude 9.0–9.1 earthquake triggers a tsunami on the north-east coast: about 19,750 dead and more than 2,500 missing. The Fukushima Daiichi accident has its own toll: 2,313 deaths linked to the evacuation according to Japan's Reconstruction Agency, while UNSCEAR has identified no health effects attributable to radiation in the population, apart from one worker death recognised in 2018."
          },
          {
            date: "May 1, 2019",
            title: "Abdication of Akihito and enthronement of Naruhito",
            description: "Akihito, the first emperor to abdicate in more than two centuries, hands the throne to his son Naruhito, who opens the Reiwa era."
          },
          {
            date: "October 21, 2025",
            title: "Sanae Takaichi, first woman Prime Minister",
            description: "Elected leader of the Liberal Democratic Party, Sanae Takaichi becomes the first woman to head the Japanese government."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices and output — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Heritage",
        title: "UNESCO-listed temples, shrines and castles",
        description: "Japan has 27 properties on the UNESCO World Heritage List (22 cultural and 5 natural), including the monuments of ancient Kyōto, Himeji Castle, Itsukushima Shrine and the hidden Christian sites of the Nagasaki region, witnesses to Christianity's clandestine survival under the Tokugawa shogunate.",
        examples: [
          "Himeji Castle",
          "Historic Kyōto",
          "Itsukushima",
          "Hidden Christian sites of Nagasaki"
        ]
      },
      {
        category: "Performing arts",
        title: "Noh, kabuki and the tea ceremony",
        description: "Noh theatre, a masked dramatic form codified in the 14th century, and kabuki, more spectacular and popular, born in the early 17th century, are both inscribed on UNESCO's Intangible Cultural Heritage list. The tea ceremony (chanoyu) and flower arranging (ikebana) are still taught as disciplines in their own right.",
        examples: [
          "Noh",
          "Kabuki",
          "Chanoyu",
          "Ikebana"
        ]
      },
      {
        category: "Food",
        title: "A world-renowned cuisine",
        description: "Washoku, traditional Japanese cuisine based on rice, fish and seasonal vegetables, has been on UNESCO's Intangible Cultural Heritage list since 2013. Tokyo is the city with the most Michelin stars.",
        examples: [
          "Sushi",
          "Ramen",
          "Tempura",
          "Wagyu"
        ]
      },
      {
        category: "Popular culture",
        title: "Manga, anime and video games",
        description: "Japan is the world's leading producer of comics (manga) and animated films (anime), with considerable international reach, alongside a video game industry that has been a pioneer since the 1980s (Nintendo, Sony, Sega).",
        examples: [
          "Studio Ghibli",
          "Dragon Ball",
          "Super Mario",
          "One Piece"
        ]
      },
      {
        category: "Sport",
        title: "Sumo, the national sport",
        description: "Sumo, a ritual wrestling of Shinto origin, remains the iconic traditional sport, with six professional tournaments (basho) a year; judo, karate and baseball, introduced in the 19th century, are among the most popular disciplines.",
        examples: [
          "Sumo",
          "Judo",
          "Karate",
          "Baseball (yakyū)"
        ]
      }
    ]
  },
  territories: {
    summary: "Japan is divided into 47 prefectures (todōfuken): the metropolis (to) of Tokyo, the circuit (dō) of Hokkaidō, two urban prefectures (fu), Ōsaka and Kyōto, and 43 ordinary prefectures (ken). The country has no inhabited overseas territory in the sense that other states administer them: its most remote islands, such as the Ogasawara Islands or Minami Torishima, are administratively attached to prefectures of the main archipelago (in this case, Tokyo). Japan also claims several disputed territories without a civilian population under Japanese administration: the southern Kuril Islands with Russia, the Liancourt Rocks (Takeshima/Dokdo) with South Korea, and the Senkaku Islands with China and Taiwan.",
    divisions: [
      {
        name: "Prefectures (todōfuken)",
        note: "1 metropolis (Tokyo), 1 circuit (Hokkaidō), 2 urban prefectures (Ōsaka, Kyōto) and 43 ordinary prefectures."
      }
    ],
    metropolitanRegions: PREFECTURES,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "Share of renewables in electricity generation (solar 11.4%, hydro 7.9%, biomass 5.9%, wind 1.1%), rising steadily since a feed-in tariff was introduced in 2012."
    },
    co2PerCapita: {
      note: "Down more than 20% since 2000, but pushed up by electricity generation that has remained highly dependent on coal and gas since the nuclear fleet was shut down after 2011."
    },
    indicators: [
      {
        label: "Forest cover",
        value: {
          note: "About two-thirds of the territory, one of the highest forest cover rates among developed countries."
        }
      },
      {
        label: "Nuclear share of electricity"
      }
    ],
    risks: [
      "Earthquakes and tsunamis",
      "Volcanic eruptions (111 active volcanoes)",
      "Typhoons and floods",
      "Mudslides and landslides"
    ],
    summary: "Nuclear power supplied about 30% of Japan's electricity before the Fukushima Daiichi accident in March 2011; almost all reactors were then shut down, bringing nuclear's share to zero by 2012, before a slow recovery as some reactors restarted under stricter safety standards — about 8.2% in 2024, with a government target of 20 to 22% by 2030. Located on the Pacific Ring of Fire, Japan also remains one of the countries most exposed to natural hazards — earthquakes, tsunamis, volcanic eruptions and typhoons — which explains earthquake-resistant building standards and warning systems among the most advanced in the world."
  },
  keyFacts: [
    {
      title: "The oldest company in the world",
      description: "Founded in 578 to build Buddhist temples, the construction company Kongō Gumi operated without interruption for more than 1,400 years, until it became a subsidiary of a large Japanese construction group in 2006."
    },
    {
      title: "An electricity mix upended by Fukushima",
      description: "Nuclear power supplied about 30% of Japan's electricity before the Fukushima Daiichi accident in 2011; its share fell to zero the following year, before slowly climbing back to about 8% in 2024 as some reactors gradually restarted."
    },
    {
      title: "The oldest society in the world after Monaco",
      description: "With a median age of 49.9 years in 2024, Japan has the second-highest median age in the world, the result of a persistently low birth rate and one of the longest life expectancies on the planet."
    },
    {
      title: "Greater Tokyo, one of the largest urban areas in the world",
      description: "The Greater Tokyo area is home to nearly 37 million people, making it one of the most populous urban areas on the planet."
    },
    {
      title: "The world capital of Michelin-starred dining",
      description: "Tokyo had 183 Michelin-starred restaurants in 2024 (including 12 with three stars), more than any other city in the world since the guide's Japanese edition began in 2007."
    },
    {
      title: "The only uses of nuclear weapons in history",
      description: "The American bombings of Hiroshima (August 6, 1945) and Nagasaki (August 9, 1945) remain, to this day, the only two uses of nuclear weapons in armed conflict in all of history."
    }
  ],
  cities: [
    {
      name: "Tokyo (23 special wards)",
      population: {
        note: "Population of the 23 special wards only; the Greater Tokyo area has about 37 million inhabitants."
      }
    },
    {
      name: "Yokohama"
    },
    {
      name: "Ōsaka"
    },
    {
      name: "Nagoya"
    },
    {
      name: "Sapporo"
    },
    {
      name: "Fukuoka"
    },
    {
      name: "Hiroshima",
      population: {
        note: "Rebuilt after the atomic bombing of August 6, 1945."
      }
    },
    {
      name: "Naha",
      population: {
        note: "Capital of Okinawa Prefecture, the main city of the Ryūkyū archipelago."
      }
    }
  ],
  rivers: [
    {
      name: "Shinano",
      lengthKm: {
        note: "The longest river in Japan."
      },
      source_location: "Mount Kobushi, on the border of Nagano, Yamanashi and Saitama prefectures",
      mouth: "Sea of Japan, at Niigata"
    },
    {
      name: "Tone",
      lengthKm: {
        note: "Japan's largest river basin, supplying water to a large part of the Tokyo metropolitan area."
      },
      source_location: "Mount Ōminakami, Gunma Prefecture",
      mouth: "Pacific Ocean, at Chōshi (Chiba Prefecture)"
    },
    {
      name: "Ishikari",
      lengthKm: {
        note: "The main river of Hokkaidō."
      },
      source_location: "Mount Ishikari, Daisetsuzan range (Hokkaidō)",
      mouth: "Sea of Japan, near the city of Ishikari"
    },
    {
      name: "Kitakami",
      source_location: "Nanashigure Mountains, Iwate Prefecture",
      mouth: "Pacific Ocean, near Ishinomaki (Miyagi Prefecture)"
    }
  ],
  regions: PREFECTURES,
  sources: {
    "Agence météorologique du Japon (JMA)": "Japan Meteorological Agency (JMA)",
    "Bureau des statistiques du Japon": "Statistics Bureau of Japan",
    "Global Carbon Atlas / Wikipedia": "Global Carbon Atlas / Wikipedia",
    "Guide Michelin": "Michelin Guide",
    "Institute for Sustainable Energy Policies (ISEP)": "Institute for Sustainable Energy Policies (ISEP)",
    "National Diet Library": "National Diet Library",
    "Nations unies (World Urbanization Prospects)": "United Nations (World Urbanization Prospects)",
    "Pew Research Center (via Wikipedia)": "Pew Research Center (via Wikipedia)",
    "UNSCEAR / World Nuclear Association": "UNSCEAR / World Nuclear Association",
    "Wikipedia (démographie du Japon)": "Wikipedia (demographics of Japan)",
    "Wikipedia (foresterie au Japon)": "Wikipedia (forestry in Japan)",
    "Wikipedia (géographie du Japon)": "Wikipedia (geography of Japan)",
    "Wikipedia (liste des cours d'eau du Japon)": "Wikipedia (list of rivers of Japan)"
  }
};
