import type { CountryTranslation } from "@/lib/i18n/translation";

const LANDER = [
  "Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Mecklenburg-Western Pomerania",
  "Lower Saxony", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt",
  "Schleswig-Holstein", "Thuringia",
].map((name) => ({ name }));

/** English translation of data/germany — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "a41ef80366d7",
  capital: "Berlin",
  geography: {
    headline: "From the northern plain to the Bavarian Alps, at the heart of Europe",
    highestPoint: {
      name: "Zugspitze"
    },
    borderingCountries: [
      "Denmark",
      "Poland",
      "Czechia",
      "Austria",
      "Switzerland",
      "France",
      "Luxembourg",
      "Belgium",
      "Netherlands"
    ],
    climate: "Temperate oceanic climate in the west and north, more continental in the east, with alpine variations in southern Bavaria.",
    summary: "Germany stretches from the North Sea and the Baltic in the north to the Bavarian Alps in the south. Its terrain combines the great northern plain, uplands in the centre (Black Forest, Ore Mountains) and the Alps on the Austrian border."
  },
  population: {
    total: {
      note: "Estimate as of end 2025."
    },
    summary: "With 83.5 million inhabitants, Germany is the most populous country in the European Union. Its population, which fell slightly in 2025, is concentrated along the Rhine axis and in the large metropolitan areas (Berlin, Hamburg, Munich, the Ruhr)."
  },
  languages: {
    entries: [
      {
        name: "German",
        note: "Official language of the Federal Republic, established by constitutional and administrative practice."
      },
      {
        name: "Lower Sorbian, Upper Sorbian, Danish, North Frisian, Romani, Low German",
        note: "Recognised as minority or regional languages under the European Charter for Regional or Minority Languages, ratified by Germany in 1998."
      }
    ],
    summary: "German is the official language at federal level. Several historical minority languages (Sorbian, Frisian, Danish, Romani) and Low German are protected under the European Charter for Regional or Minority Languages."
  },
  religion: {
    surveyName: "Statistics of religious communities (fowid)",
    ageScope: "Entire population, end of year",
    points: [
      {
        label: "No religious affiliation"
      },
      {
        label: "Catholic"
      },
      {
        label: "Protestant (EKD)"
      },
      {
        label: "Muslim"
      },
      {
        label: "Other religious communities"
      }
    ],
    summary: "At the end of 2024, for the first time, people with no religious affiliation (46.8%) outnumbered the members of the Catholic (23.7%) and Protestant (21.5%) churches combined, according to the religious communities' own counts.",
    methodologyNote: "These figures come from the official registers of the churches and religious communities (legal membership, notably through the church tax), not from a survey of belief or practice — actual religious practice is considerably lower."
  },
  politics: {
    stateForm: "Federal republic",
    regime: "Federal parliamentary republic",
    headOfState: {
      title: "Federal President",
      name: "Frank-Walter Steinmeier",
      since: "March 19, 2017 (re-elected in 2022)"
    },
    headOfGovernment: {
      title: "Federal Chancellor",
      name: "Friedrich Merz",
      since: "May 6, 2025"
    },
    legislature: {
      name: "Parliament",
      chambers: [
        {
          name: "Bundestag"
        },
        {
          name: "Bundesrat"
        }
      ]
    },
    constitution: {
      adopted: "May 23, 1949"
    },
    summary: "Germany is a federal parliamentary republic made up of 16 Länder. The Federal President, elected indirectly, has a representative role, while the Federal Chancellor, accountable to the Bundestag, leads the government."
  },
  economy: {
    currency: {
      name: "Euro"
    },
    gdp: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    gdpPerCapita: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry"
      },
      {
        name: "Construction"
      },
      {
        name: "Agriculture"
      }
    ],
    indicators: [],
    summary: "Europe's largest economy, Germany relies on a powerful export industry — cars, machine tools, chemicals — built around a vast network of medium-sized companies (the Mittelstand), alongside a predominant service sector."
  },
  history: {
    intro: "A few milestones to place the major stages in the country's formation and transformation — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Antiquity",
        summary: "The present-day territory was inhabited by Germanic peoples, partly facing the Roman Empire along the limes, before the rise of the Frankish kingdom.",
        events: [
          {
            date: "AD 9",
            title: "Battle of the Teutoburg Forest",
            description: "A Roman defeat at the hands of a Germanic coalition, which helped fix the Roman frontier on the Rhine."
          }
        ]
      },
      {
        title: "Middle Ages",
        summary: "The coronation of Charlemagne and then the formation of the Holy Roman Empire structured a political space fragmented into many principalities.",
        events: [
          {
            date: "962",
            title: "Coronation of Otto I",
            description: "Otto I is crowned emperor, founding what would become the Holy Roman Empire."
          }
        ]
      },
      {
        title: "Early modern period",
        summary: "The Protestant Reformation and then the Thirty Years' War profoundly reshaped the religious and political landscape of an increasingly fragmented Holy Roman Empire.",
        events: [
          {
            date: "1517",
            title: "Luther's theses",
            description: "Martin Luther circulates his 95 Theses in Wittenberg, the starting point of the Protestant Reformation."
          },
          {
            date: "1618 – 1648",
            title: "Thirty Years' War",
            description: "A devastating conflict in central Europe, ended by the Peace of Westphalia."
          }
        ]
      },
      {
        title: "Unification & 19th century",
        summary: "After the Napoleonic period and the German Confederation, political unification was achieved in 1871 under the leadership of Prussia.",
        events: [
          {
            date: "January 18, 1871",
            title: "Proclamation of the German Empire",
            description: "Wilhelm I of Prussia is proclaimed German Emperor at Versailles, unifying the German states."
          }
        ]
      },
      {
        title: "20th century",
        summary: "Two world wars, the Weimar Republic, the Nazi regime and then the division of the country into two states until reunification in 1990 made it a century of ruptures.",
        events: [
          {
            date: "1933 – 1945",
            title: "Third Reich",
            description: "The National Socialist dictatorship led by Adolf Hitler, responsible for the Second World War and the Holocaust."
          },
          {
            date: "1949",
            title: "Division into two states",
            description: "Founding of the Federal Republic of Germany (West Germany) and the German Democratic Republic (East Germany)."
          },
          {
            date: "1961",
            title: "Construction of the Berlin Wall",
            description: "East Germany builds a wall separating West and East Berlin, a symbol of the country's division."
          },
          {
            date: "October 3, 1990",
            title: "German reunification",
            description: "East Germany joins West Germany, ending forty years of division."
          }
        ]
      },
      {
        title: "Today",
        summary: "Reunified Germany, with Berlin once again its capital from 1990, is a founding member of the European Union and adopted the euro in 2002.",
        events: [
          {
            date: "2002",
            title: "Euro notes and coins introduced",
            description: "Euro coins and banknotes replace the Deutsche Mark in everyday transactions."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Food",
        title: "A brewing tradition regulated since 1516",
        description: "The Reinheitsgebot, the Bavarian beer purity law issued in 1516, still governs part of German beer production today — one of the oldest food regulations still in force in the world.",
        examples: [
          "Bratwurst",
          "Pretzel",
          "Sauerkraut",
          "Beer (Pils, Weizen, Kölsch depending on the region)"
        ]
      },
      {
        category: "Celebrations",
        title: "Oktoberfest",
        description: "The world's largest folk festival has been held in Munich every year since 1810, drawing several million visitors.",
        examples: [
          "Beer served by the Maß (one-litre mug)",
          "Traditional dress (Lederhosen, Dirndl)"
        ]
      },
      {
        category: "Sport",
        title: "Football, the most popular sport",
        description: "Germany has won four FIFA World Cups (1954, 1974, 1990, 2014), and the Bundesliga has the highest stadium attendances in Europe.",
        examples: [
          "Bayern Munich",
          "Borussia Dortmund"
        ]
      },
      {
        category: "Music",
        title: "A major classical music tradition",
        description: "Bach, Beethoven, Brahms and Wagner were born or composed most of their work in German lands, founding an orchestral tradition that is still very much alive.",
        examples: [
          "Berlin Philharmonic",
          "Bayreuth Festival (works by Wagner)"
        ]
      },
      {
        category: "Heritage",
        title: "55 World Heritage sites",
        description: "In 2025 Germany has 55 properties inscribed on the UNESCO World Heritage List, including the palaces of King Ludwig II of Bavaria, inscribed that year.",
        examples: [
          "Cologne Cathedral",
          "Neuschwanstein Castle",
          "Museum Island in Berlin"
        ]
      }
    ]
  },
  territories: {
    summary: "Germany is a federal state made up of 16 Länder, each with its own government, parliament and constitution. The Länder are divided into districts (Landkreise) and district-free cities (kreisfreie Städte), themselves subdivided into municipalities.",
    divisions: [
      {
        name: "Länder",
        note: "Federal states, including 3 city-states."
      },
      {
        name: "Districts and district-free cities",
        note: "Landkreise and kreisfreie Städte."
      },
      {
        name: "Municipalities",
        note: "Gemeinden, mid-2024."
      }
    ],
    metropolitanRegions: LANDER,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "Share of renewable energy in gross final energy consumption."
    },
    indicators: [
      {
        label: "Forest cover"
      }
    ],
    risks: [
      "Floods",
      "Storms",
      "Heatwaves",
      "Drought"
    ],
    summary: "CO₂ emissions per capita remain higher than in neighbouring European countries, with an electricity mix still marked by coal despite the nuclear phase-out in 2023. The country remains exposed to flooding, such as the devastating Ahr valley flood of 2021, and to increasingly frequent summer heatwaves and droughts."
  },
  keyFacts: [
    {
      title: "A motorway network largely without speed limits",
      description: "A substantial part of the German motorway network (Autobahn) has no general speed limit, a singularity in Europe."
    },
    {
      title: "The birthplace of modern printing",
      description: "It was in Mainz, around 1450, that Johannes Gutenberg developed the first printing press with movable metal type, an invention that revolutionised the spread of the written word in Europe."
    },
    {
      title: "A dual vocational training system copied abroad",
      description: "German apprenticeships combine in-company training with vocational school (duale Ausbildung). This model, associated with low youth unemployment, inspires reforms in several countries in Europe and beyond."
    },
    {
      title: "An almost universal deposit on beverage containers",
      description: "Since 2003, most single-use bottles and cans have carried a deposit (Pfand). The consumer return rate exceeded 98% in 2021."
    },
    {
      title: "More than two million asylum applications processed between 2015 and 2017",
      description: "After the peak of 2015 (476,649 asylum applications, a record), Germany processed nearly two million asylum procedures between 2015 and 2017, an influx unmatched among European countries over that period."
    }
  ],
  cities: [
    {
      name: "Berlin"
    },
    {
      name: "Hamburg"
    },
    {
      name: "Munich"
    },
    {
      name: "Cologne"
    },
    {
      name: "Frankfurt am Main"
    },
    {
      name: "Stuttgart"
    },
    {
      name: "Düsseldorf"
    },
    {
      name: "Leipzig"
    },
    {
      name: "Dortmund"
    },
    {
      name: "Essen"
    }
  ],
  rivers: [
    {
      name: "Rhine",
      lengthKm: {
        note: "German section; 1,233 km in total."
      },
      source_location: "Swiss Alps",
      mouth: "North Sea (in the Netherlands)"
    },
    {
      name: "Danube",
      lengthKm: {
        note: "German section; 2,857 km in total."
      },
      source_location: "Donaueschingen (Black Forest)",
      mouth: "Black Sea"
    },
    {
      name: "Elbe",
      lengthKm: {
        note: "German section; 1,094 km in total."
      },
      source_location: "Giant Mountains (Czech Republic)",
      mouth: "North Sea, near Cuxhaven"
    }
  ],
  regions: LANDER,
  sources: {
    "BAMF — Bundesamt für Migration und Flüchtlinge": "BAMF — Federal Office for Migration and Refugees",
    "BBK — Bundesamt für Bevölkerungsschutz und Katastrophenhilfe": "BBK — Federal Office of Civil Protection and Disaster Assistance",
    "BIBB — Bundesinstitut für Berufsbildung": "BIBB — Federal Institute for Vocational Education and Training",
    "Bayerisches Landesamt für Vermessung": "Bavarian State Office for Surveying",
    "Bundesagentur für Arbeit": "Federal Employment Agency",
    "Bundesministerium für Verkehr": "Federal Ministry for Transport",
    "Bundeszentrale für politische Bildung": "Federal Agency for Civic Education",
    "DFB (Fédération allemande de football)": "DFB (German Football Association)",
    Destatis: "Destatis",
    "Deutsche Bundesbank": "Deutsche Bundesbank",
    "Deutsche UNESCO-Kommission": "German Commission for UNESCO",
    "Deutscher Brauer-Bund": "German Brewers' Association",
    "Deutscher Bundestag": "German Bundestag",
    "Gutenberg-Museum Mainz": "Gutenberg Museum Mainz",
    "Landeshauptstadt München": "City of Munich",
    Umweltbundesamt: "German Environment Agency",
    "Umweltbundesamt (UBA)": "German Environment Agency (UBA)",
    Verbraucherzentrale: "Verbraucherzentrale (consumer advice centre)",
    "fowid — Forschungsgruppe Weltanschauungen in Deutschland": "fowid — Research Group on Worldviews in Germany"
  }
};
