import type { CountryTranslation } from "@/lib/i18n/translation";

/** English translation of data/france — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "2e7f768e7616",
  capital: "Paris",
  geography: {
    headline: "A territory between three seaboards and two great mountain ranges",
    areaKm2: {
      note: "Metropolitan France, cadastral area."
    },
    highestPoint: {
      name: "Mont Blanc"
    },
    borderingCountries: [
      "Belgium",
      "Luxembourg",
      "Germany",
      "Switzerland",
      "Italy",
      "Monaco",
      "Spain",
      "Andorra"
    ],
    climate: "Oceanic in the west, semi-continental in the east, Mediterranean in the south, with mountain variations in the upland ranges.",
    summary: "Located at the western edge of Europe, metropolitan France is bordered by the English Channel, the Atlantic and the Mediterranean. Its terrain combines broad plains, ancient uplands (Massif Central, Vosges) and high mountains (Alps, Pyrenees)."
  },
  population: {
    total: {
      note: "Estimate as of 1 January 2025; whole of France (metropolitan France and the five overseas departments)."
    },
    density: {
      note: "Metropolitan France."
    },
    growthRate: {
      note: "Annual population change, driven by net migration and a natural balance close to zero."
    },
    summary: "France's population is growing moderately, driven mainly by net migration. It is concentrated around large urban areas, first and foremost the Île-de-France region, while vast rural areas remain sparsely populated."
  },
  languages: {
    entries: [
      {
        name: "French",
        note: "Language of the Republic since the 1992 constitutional amendment (Article 2 of the Constitution)."
      },
      {
        name: "Occitan, Breton, Alsatian, Corsican, Basque, Catalan, West Flemish, langues d'oïl…",
        note: "Recognised as part of France's heritage since 2008 (Article 75-1 of the Constitution). France has signed but not ratified the European Charter for Regional or Minority Languages."
      }
    ],
    summary: "French is the only official language of the Republic. Several regional languages, long spoken in the country, enjoy recognition as heritage without co-official status."
  },
  religion: {
    surveyName: "Trajectories and Origins 2 (TeO2)",
    ageScope: "aged 18–59, metropolitan France",
    points: [
      {
        label: "No religion"
      },
      {
        label: "Catholicism"
      },
      {
        label: "Islam"
      },
      {
        label: "Other religions and beliefs"
      }
    ],
    summary: "According to the Trajectories and Origins survey (Insee/Ined, 2019–2020), 51% of people aged 18 to 59 living in metropolitan France say they have no religion, 29% identify as Catholic and 10% as Muslim.",
    methodologyNote: "These figures are based on self-declared affiliation and do not measure religious practice, which is considerably lower across all faiths. They reflect what people declare, not a characterisation of the population as a whole."
  },
  politics: {
    stateForm: "Republic",
    regime: "Semi-presidential system (Fifth Republic)",
    headOfState: {
      title: "President of the Republic",
      name: "Emmanuel Macron",
      since: "May 14, 2017 (re-elected in 2022)"
    },
    headOfGovernment: {
      title: "Prime Minister",
      name: "Sébastien Lecornu",
      since: "September 9, 2025"
    },
    legislature: {
      name: "Parliament",
      chambers: [
        {
          name: "National Assembly"
        },
        {
          name: "Senate"
        }
      ]
    },
    constitution: {
      adopted: "October 4, 1958"
    },
    summary: "France is a republic whose system, established by the 1958 Constitution, combines a president elected by direct universal suffrage for five years with a government accountable to the National Assembly."
  },
  economy: {
    currency: {
      name: "Euro"
    },
    gdp: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    gdpPerCapita: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    unemploymentRate: {
      note: "Q4 2025, ILO definition."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry"
      },
      {
        name: "Construction"
      },
      {
        name: "Agriculture"
      }
    ],
    indicators: [],
    summary: "The French economy, one of the largest in the euro area, relies very heavily on services (retail, finance, public administration, tourism), with a significant industrial base in aerospace, automotive, luxury goods and energy."
  },
  history: {
    intro: "A few milestones to place the major stages in the country's formation and transformation — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Antiquity",
        summary: "The territory of present-day France was inhabited by Celtic peoples (the Gauls) before being incorporated into the Roman Empire from the 1st century BC.",
        events: [
          {
            date: "52 BC",
            title: "Battle of Alesia",
            description: "Vercingetorix is defeated by Julius Caesar, marking the gradual incorporation of Gaul into the Roman Empire."
          },
          {
            date: "1st – 5th century",
            title: "Roman Gaul",
            description: "Romanisation of the territory: towns, roads, law and the Latin language lay lasting foundations, especially for the language."
          }
        ]
      },
      {
        title: "Middle Ages",
        summary: "From the Frankish kingdom to the end of the Hundred Years' War, this long period saw the gradual rise of a centralised royal power and of the territorial structures of the Kingdom of France.",
        events: [
          {
            date: "486",
            title: "Clovis's victory at Soissons",
            description: "End of the last Gallo-Roman stronghold; expansion of the Merovingian Frankish kingdom."
          },
          {
            date: "800",
            title: "Coronation of Charlemagne",
            description: "Charlemagne, King of the Franks, is crowned emperor in Rome."
          },
          {
            date: "987",
            title: "Accession of Hugh Capet",
            description: "Election of Hugh Capet, the conventional starting point of the Capetian dynasty."
          },
          {
            date: "1337 – 1453",
            title: "Hundred Years' War",
            description: "A long conflict between the kingdoms of France and England that shaped the kingdom's identity and territory."
          }
        ]
      },
      {
        title: "Early modern period",
        summary: "The rise of absolute monarchy, the Wars of Religion, cultural and scientific influence, up to the financial and political crisis that preceded the Revolution.",
        events: [
          {
            date: "1598",
            title: "Edict of Nantes",
            description: "Henry IV grants Protestants civil toleration, ending several decades of Wars of Religion."
          },
          {
            date: "1643 – 1715",
            title: "Reign of Louis XIV",
            description: "High point of absolute monarchy by divine right; the court moves to Versailles in 1682."
          },
          {
            date: "18th century",
            title: "Age of Enlightenment",
            description: "Spread of the ideas of Montesquieu, Voltaire, Rousseau and Diderot, which would feed the revolutionary movement."
          }
        ]
      },
      {
        title: "Revolution & 19th century",
        summary: "The French Revolution ended absolute monarchy. The following century alternated between empires, constitutional monarchies and republics, until the Third Republic took lasting hold.",
        events: [
          {
            date: "July 14, 1789",
            title: "Storming of the Bastille",
            description: "A founding episode of the French Revolution, celebrated as the national holiday since 1880."
          },
          {
            date: "August 26, 1789",
            title: "Declaration of the Rights of Man and of the Citizen",
            description: "Founding text of the principles of liberty, equality and national sovereignty, still part of France's constitutional law today."
          },
          {
            date: "1804",
            title: "Coronation of Napoleon I",
            description: "Napoleon Bonaparte becomes Emperor of the French, establishing the First Empire."
          },
          {
            date: "September 4, 1870",
            title: "Proclamation of the Third Republic",
            description: "After the fall of the Second Empire, the Republic takes lasting hold."
          }
        ]
      },
      {
        title: "20th century",
        summary: "Two world wars, decolonisation and European integration profoundly reshaped France's place in the world; the Fifth Republic was established in 1958.",
        events: [
          {
            date: "1914 – 1918",
            title: "First World War",
            description: "A major conflict fought largely on French soil, with enormous loss of life."
          },
          {
            date: "1940 – 1944",
            title: "Occupation and Liberation",
            description: "Occupation by Nazi Germany, the Vichy regime, then the Liberation of the country in 1944."
          },
          {
            date: "1958",
            title: "Establishment of the Fifth Republic",
            description: "Adoption of the Constitution of 4 October 1958, driven by General de Gaulle."
          },
          {
            date: "1962",
            title: "Independence of Algeria",
            description: "End of the Algerian War and the country's accession to independence, following the Évian Accords."
          },
          {
            date: "1957",
            title: "Treaty of Rome",
            description: "France is a founding member of the European Economic Community."
          }
        ]
      },
      {
        title: "Today",
        summary: "Since the turn of the 2000s, France has remained a founding member state of the European Union, using the euro, and continues to adapt its institutions.",
        events: [
          {
            date: "2002",
            title: "Euro notes and coins introduced",
            description: "Euro coins and banknotes replace the franc in everyday transactions."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Food",
        title: "The gastronomic meal of the French",
        description: "Inscribed in 2010 on UNESCO's list of the Intangible Cultural Heritage of Humanity, as a social practice that structures meals in France — more than a list of dishes, a ritual of conviviality.",
        examples: [
          "Baguette",
          "PDO cheeses (Camembert, Roquefort…)",
          "Wines (Bordeaux, Burgundy, Champagne)",
          "Foie gras"
        ]
      },
      {
        category: "Celebrations",
        title: "Bastille Day, 14 July",
        description: "Commemorates the storming of the Bastille (1789) and the Fête de la Fédération (1790); made the national holiday by the law of 6 July 1880.",
        examples: [
          "Military parade on the Champs-Élysées",
          "Fireworks",
          "Firefighters' balls"
        ]
      },
      {
        category: "Sport",
        title: "The Tour de France",
        description: "A multi-stage cycling race created in 1903, one of the most watched cycling competitions in the world.",
        examples: [
          "Yellow jersey",
          "The climb to Alpe d'Huez",
          "Finish on the Champs-Élysées"
        ]
      },
      {
        category: "Cinema",
        title: "The Cannes Film Festival",
        description: "Founded in 1946, it is one of the world's leading international film festivals, known for its Palme d'Or."
      },
      {
        category: "Heritage",
        title: "An extensive world heritage",
        description: "France has 54 properties inscribed on the UNESCO World Heritage List as of 2025 (cultural, natural and mixed), the 4th longest list in the world.",
        examples: [
          "Mont-Saint-Michel",
          "Palace of Versailles",
          "Chartres Cathedral",
          "Old Lyon",
          "Pont du Gard"
        ]
      }
    ]
  },
  territories: {
    summary: "Metropolitan France is organised into regions and departments. Five overseas departments and regions (DROM) and several overseas collectivities complete the national territory, each with its own institutional status.",
    divisions: [
      {
        name: "Regions",
        note: "13 metropolitan regions and 5 overseas regions."
      },
      {
        name: "Departments",
        note: "96 metropolitan departments and 5 overseas departments."
      },
      {
        name: "Communes",
        note: "As of 1 January 2025."
      }
    ],
    metropolitanRegions: [
      {
        name: "Île-de-France"
      },
      {
        name: "Centre-Val de Loire"
      },
      {
        name: "Bourgogne-Franche-Comté"
      },
      {
        name: "Normandy"
      },
      {
        name: "Hauts-de-France"
      },
      {
        name: "Grand Est"
      },
      {
        name: "Pays de la Loire"
      },
      {
        name: "Brittany"
      },
      {
        name: "Nouvelle-Aquitaine"
      },
      {
        name: "Occitanie"
      },
      {
        name: "Auvergne-Rhône-Alpes"
      },
      {
        name: "Provence-Alpes-Côte d'Azur"
      },
      {
        name: "Corsica"
      }
    ],
    overseas: [
      {
        name: "Guadeloupe"
      },
      {
        name: "Martinique"
      },
      {
        name: "French Guiana"
      },
      {
        name: "Réunion"
      },
      {
        name: "Mayotte"
      },
      {
        name: "French Polynesia"
      },
      {
        name: "New Caledonia"
      },
      {
        name: "Saint Pierre and Miquelon"
      },
      {
        name: "Wallis and Futuna"
      },
      {
        name: "Saint Martin"
      },
      {
        name: "Saint Barthélemy"
      },
      {
        name: "French Southern and Antarctic Lands"
      }
    ]
  },
  environment: {
    renewableShare: {
      note: "Share of renewable energy in gross final energy consumption."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Nuclear share of electricity",
        value: {
          note: "The highest dependence on nuclear power in the world."
        }
      }
    ],
    risks: [
      "Floods",
      "Wildfires",
      "Landslides and subsidence",
      "Storms"
    ],
    summary: "Thanks to an electricity mix dominated by nuclear power, CO₂ emissions per capita are among the lowest in Western Europe, even though the share of renewables in energy consumption is growing more slowly. Floods and wildfires, which are increasing in the south of the country, remain the main natural hazards."
  },
  keyFacts: [
    {
      title: "The most visited country in the world",
      description: "With 102 million international visitors in 2024, France is the world's leading tourist destination, ahead of Spain and the United States."
    },
    {
      title: "The most awarded country in literature",
      description: "With 16 laureates, France has won more Nobel Prizes in Literature than any other country, ahead of the United Kingdom and the United States."
    },
    {
      title: "The country with the most time zones",
      description: "Thanks to its overseas departments and collectivities, France spans 12 time zones, a world record ahead of Russia and the United States (11 each)."
    },
    {
      title: "An electricity mix dominated by nuclear power",
      description: "Nuclear power supplied about 65% of the electricity generated in France in 2023, a unique case among major economies — which largely explains its low CO₂ emissions per capita."
    },
    {
      title: "Laïcité, a founding principle since 1905",
      description: "The law of 9 December 1905 separates the Churches and the State: the Republic does not recognise, pay or subsidise any religion."
    },
    {
      title: "The world's leading luxury nation",
      description: "French houses account for more than 30% of the luxury sector's global revenue, far ahead of their Italian, Swiss or American competitors."
    }
  ],
  cities: [
    {
      name: "Paris"
    },
    {
      name: "Marseille"
    },
    {
      name: "Lyon"
    },
    {
      name: "Toulouse"
    },
    {
      name: "Nice"
    },
    {
      name: "Nantes"
    },
    {
      name: "Montpellier"
    },
    {
      name: "Strasbourg"
    },
    {
      name: "Bordeaux"
    },
    {
      name: "Lille"
    }
  ],
  rivers: [
    {
      name: "Loire",
      source_location: "Mont Gerbier de Jonc (Ardèche)",
      mouth: "Atlantic Ocean"
    },
    {
      name: "Seine",
      source_location: "Langres Plateau (Côte-d'Or)",
      mouth: "English Channel"
    },
    {
      name: "Rhône",
      source_location: "Rhône Glacier (Swiss Alps)",
      mouth: "Mediterranean Sea"
    },
    {
      name: "Garonne",
      source_location: "Val d'Aran (Spain)",
      mouth: "Atlantic Ocean (Gironde estuary)"
    }
  ],
  regions: [
    {
      name: "Île-de-France"
    },
    {
      name: "Centre-Val de Loire"
    },
    {
      name: "Bourgogne-Franche-Comté"
    },
    {
      name: "Normandy"
    },
    {
      name: "Hauts-de-France"
    },
    {
      name: "Grand Est"
    },
    {
      name: "Pays de la Loire"
    },
    {
      name: "Brittany"
    },
    {
      name: "Nouvelle-Aquitaine"
    },
    {
      name: "Occitanie"
    },
    {
      name: "Auvergne-Rhône-Alpes"
    },
    {
      name: "Provence-Alpes-Côte d'Azur"
    },
    {
      name: "Corsica"
    }
  ],
  sources: {
    "Amaury Sport Organisation": "Amaury Sport Organisation",
    "Assemblée nationale": "National Assembly",
    "Banque de France": "Banque de France",
    "Comité Colbert": "Comité Colbert",
    "Conseil constitutionnel": "Constitutional Council",
    "Festival de Cannes": "Cannes Film Festival",
    "Géorisques — Ministère de la Transition écologique": "Géorisques — French Ministry for the Ecological Transition",
    IGN: "IGN",
    INSEE: "INSEE",
    "INSEE / INED": "INSEE / INED",
    "INSEE — Code officiel géographique": "INSEE — Official Geographic Code",
    "Larousse — Encyclopédie": "Larousse Encyclopedia",
    "Légifrance": "Légifrance",
    "Ministère de l'Économie": "French Ministry of the Economy",
    "Présidence de la République": "French Presidency",
    RTE: "RTE",
    "SDES — Ministère de la Transition écologique": "SDES — French Ministry for the Ecological Transition",
    Sandre: "Sandre"
  }
};
