import type { CountryTranslation } from "@/lib/i18n/translation";

const PROVINCES_AND_TERRITORIES = [
  "Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan", "Nova Scotia", "New Brunswick",
  "Newfoundland and Labrador", "Prince Edward Island", "Northwest Territories", "Yukon", "Nunavut",
].map((name) => ({ name }));

/** English translation of data/canada — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "69d0310b3d8f",
  capital: "Ottawa",
  geography: {
    headline: "The world's second-largest country, from sea to sea to sea, dominated by the Canadian Shield and the Arctic Archipelago",
    areaKm2: {
      note: "The world's second-largest country by area, after Russia."
    },
    coastlineKm: {
      note: "The longest coastline in the world, bordering the Pacific, Atlantic and Arctic oceans."
    },
    highestPoint: {
      name: "Mount Logan (Yukon)"
    },
    borderingCountries: [
      "United States"
    ],
    climate: "Extremely varied depending on latitude and distance from the oceans: temperate and humid on the Pacific and Atlantic coasts, continental with hot summers and harsh winters on the Prairies and in the centre, subarctic then Arctic (tundra and permafrost) in the Far North, where some stations are among the coldest and most remote inhabited places on Earth.",
    summary: "Stretching across nearly 10 million km² from the Atlantic to the Pacific and on to the Arctic Ocean, Canada shares only one land border, with the United States, more than 8,800 km long — the longest international border in the world. The country has more lakes than all other countries combined, a vast Precambrian shield (the Canadian Shield) covering nearly half its territory, and an immense Arctic Archipelago of more than 36,000 islands, largely uninhabited and covered in ice for much of the year."
  },
  population: {
    total: {
      note: "Quarterly estimate (Q1 2026)."
    },
    density: {
      note: "Calculated from total population and the country's area; one of the lowest densities in the world, as the population is concentrated in a narrow band along the US border."
    },
    growthRate: {
      note: "Growth has slowed sharply since 2024, after the federal government announced at the end of 2024 lower permanent and temporary immigration targets for 2025–2027, following several years of record growth driven almost entirely by immigration."
    },
    summary: "Canada is one of the least densely populated countries in the world: the vast majority of its inhabitants live in a narrow band near the US border, especially in the Windsor–Quebec City corridor, while the Far North remains largely uninhabited. Its population growth, one of the fastest in the developed world since the 2010s, relies almost entirely on immigration; it has slowed markedly since 2025 after the federal government deliberately tightened admission targets."
  },
  languages: {
    entries: [
      {
        name: "English",
        sharePercent: {
          note: "Share of the population whose mother tongue is English."
        },
        note: "Co-official with French at federal level; the de facto sole official language in most provinces other than Quebec and New Brunswick."
      },
      {
        name: "French",
        sharePercent: {
          note: "Share of the population whose mother tongue is French."
        },
        note: "The only official language of Quebec since the Charter of the French Language (1977); co-official with English in New Brunswick, the only officially bilingual province, and at federal level."
      },
      {
        name: "Indigenous languages (Cree, Inuktitut, Ojibwe...)",
        note: "More than 70 distinct Indigenous languages recorded; Inuktitut is co-official with English and French in Nunavut, and eleven languages (including Tłı̨chǫ, Gwich'in and several Dene dialects) are official in the Northwest Territories."
      },
      {
        name: "Immigrant languages (Mandarin, Punjabi, Cantonese, Spanish, Tagalog, Arabic...)",
        note: "Spoken by a growing share of the population, especially in the large metropolitan areas (Toronto, Vancouver, Montreal), reflecting diverse immigration."
      }
    ],
    summary: "English and French are Canada's two official languages at federal level, an institutional bilingualism unique among the major English-speaking countries, inherited from the country's dual British and French foundation. French remains, however, largely concentrated in Quebec, where it is the only official provincial language, and in francophone pockets of New Brunswick, Ontario and Manitoba; nationally, English overwhelmingly dominates everyday life outside Quebec."
  },
  religion: {
    surveyName: "Census of Population",
    ageScope: "Total population reporting a religious affiliation",
    points: [
      {
        label: "Catholic"
      },
      {
        label: "Protestant"
      },
      {
        label: "Other Christian (Orthodox and other)"
      },
      {
        label: "No religion"
      },
      {
        label: "Muslim"
      },
      {
        label: "Hindu"
      },
      {
        label: "Sikh"
      },
      {
        label: "Buddhist"
      },
      {
        label: "Jewish"
      },
      {
        label: "Other (including Indigenous spirituality)"
      }
    ],
    summary: "Christianity, historically overwhelmingly dominant, now accounts for only slightly more than half of the population, in steady decline for several decades in favour of no religion, now the second most reported category. Catholicism remains particularly present in Quebec, historically shaped by the Catholic Church until the Quiet Revolution of the 1960s, and in communities of Irish, Italian, Polish or Filipino origin; the rise of non-Christian religions (Islam, Hinduism, Sikhism) directly reflects the major waves of recent immigration.",
    methodologyNote: "2021 Census; the religion question is asked only once a decade, in census years ending in 1."
  },
  politics: {
    stateForm: "Federal constitutional monarchy",
    regime: "Westminster-style parliamentary democracy",
    headOfState: {
      title: "King",
      name: "Charles III",
      since: "September 8, 2022"
    },
    headOfGovernment: {
      title: "Prime Minister",
      name: "Mark Carney",
      since: "March 14, 2025"
    },
    legislature: {
      name: "Parliament of Canada",
      chambers: [
        {
          name: "House of Commons"
        },
        {
          name: "Senate"
        }
      ]
    },
    constitution: {
      adopted: "Constitution Act, 1867, completed by patriation in 1982 (Constitution Act, 1982 and the Canadian Charter of Rights and Freedoms)"
    },
    summary: "Canada is a federal constitutional monarchy: King Charles III, head of state and also sovereign of the United Kingdom and the other Commonwealth realms, is represented day to day by a Governor General — Louise Arbour since June 2026 — who exercises nearly all constitutional functions in his name (royal assent, appointment of judges and senators, summoning and dissolving Parliament). The Prime Minister, leader of the party holding the confidence of the House of Commons, heads the federal government, whose powers are shared with ten provinces and three territories according to a division of powers set out in the Constitution."
  },
  economy: {
    currency: {
      name: "Canadian dollar"
    },
    gdp: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    gdpPerCapita: {
      note: "Current US dollars."
    },
    unemploymentRate: {
      note: "Modelled estimate (ILO); Statistics Canada's Labour Force Survey publishes similar monthly rates, generally between 6.5% and 7%."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Industry"
      },
      {
        name: "Agriculture, forestry and fishing"
      },
      {
        name: "Other (net taxes on products, etc.)"
      }
    ],
    indicators: [
      {
        label: "Share of exports going to the United States",
        value: {
          value: "about 75%",
          note: "Very close trade integration with the US economy, governed by the Canada–United States–Mexico Agreement (CUSMA/USMCA), a recurring source of trade tensions."
        }
      }
    ],
    summary: "A developed and highly diversified economy, dominated by services (finance in Toronto, technology, tourism) but also rich in natural resources — oil and the Alberta oil sands, hydroelectricity in Quebec and Manitoba, mining, potash, forestry. Canada's foreign trade remains overwhelmingly oriented towards the United States, which makes the economy particularly sensitive to shifts in US trade policy."
  },
  history: {
    intro: "A few milestones to place the major stages in the building of the modern country — not an exhaustive summary of Canadian history, which is already widely documented elsewhere.",
    periods: [
      {
        title: "First Peoples and New France",
        summary: "The territory of present-day Canada has been inhabited for millennia by hundreds of Indigenous nations (First Nations, Inuit) with very diverse languages and social organisations. Following Jacques Cartier's exploration in 1534 and Samuel de Champlain's founding of Quebec City in 1608, France established the colony of New France, based on the fur trade and Catholic evangelisation, before ceding it to Great Britain at the end of the Seven Years' War.",
        events: [
          {
            date: "1608",
            title: "Founding of Quebec City",
            description: "Samuel de Champlain founds Quebec City, the first lasting permanent settlement of New France."
          },
          {
            date: "February 10, 1763",
            title: "Treaty of Paris",
            description: "At the end of the Seven Years' War, France cedes New France to Great Britain, except for Saint Pierre and Miquelon."
          }
        ]
      },
      {
        title: "British North America",
        summary: "Under British rule, the Quebec Act of 1774 guaranteed French-speaking settlers the continuation of their civil law and the Catholic religion. The arrival of tens of thousands of Loyalists fleeing the American Revolution, the War of 1812 against the United States, then the rebellions of 1837–1838 in Upper and Lower Canada gradually shaped distinct colonies, united into a single Province of Canada in 1841 and granted responsible government from 1848.",
        events: [
          {
            date: "1774",
            title: "Quebec Act",
            description: "The British Parliament guarantees the French-speaking inhabitants of the Province of Quebec the continuation of French civil law and the Catholic religion."
          },
          {
            date: "1837-1838",
            title: "Rebellions in Upper and Lower Canada",
            description: "Armed uprisings put down in Upper and Lower Canada, leading to the Durham Report and the Act of Union of 1840."
          }
        ]
      },
      {
        title: "Confederation and the rise of the Dominion",
        summary: "The British North America Act united, on July 1, 1867, the Province of Canada (split into Ontario and Quebec), Nova Scotia and New Brunswick within the Dominion of Canada. The country then expanded rapidly west and north through the purchase of Rupert's Land, the successive entry of Manitoba, British Columbia, Prince Edward Island, then Alberta and Saskatchewan, and the completion of the transcontinental railway in 1885. Its major role in the First World War, marked by the victory at Vimy Ridge in 1917, helped it obtain full legislative autonomy through the Statute of Westminster of 1931.",
        events: [
          {
            date: "July 1, 1867",
            title: "Canadian Confederation",
            description: "The British North America Act creates the Dominion of Canada, federating Ontario, Quebec, Nova Scotia and New Brunswick."
          },
          {
            date: "1885",
            title: "Completion of the Canadian Pacific Railway",
            description: "The transcontinental rail link connects the east of the country to British Columbia, opening Western Canada to settlement."
          },
          {
            date: "1931",
            title: "Statute of Westminster",
            description: "The British Parliament recognises Canada's full legislative autonomy, though the country remains tied to the United Kingdom through the Crown."
          }
        ]
      },
      {
        title: "World war, the Quiet Revolution and patriation of the Constitution",
        summary: "After a major contribution to the Allied war effort in the Second World War and Newfoundland's entry into the federation in 1949, Quebec went through the Quiet Revolution in the 1960s, which rapidly modernised a society until then strongly shaped by the Catholic Church and gave rise to a sovereigntist movement. The October Crisis of 1970, two Quebec referendums on sovereignty (1980 and 1995) and the failure of the Meech Lake (1987–1990) and Charlottetown (1992) constitutional accords marked several decades of tension over Quebec's place in the federation, while the country patriated its Constitution in 1982 and adopted a Charter of Rights and Freedoms. The period closed with the creation of the territory of Nunavut in 1999, following an agreement with the Inuit.",
        events: [
          {
            date: "October 1970",
            title: "October Crisis",
            description: "The Front de libération du Québec (FLQ) kidnaps a British diplomat and Quebec minister Pierre Laporte, later found murdered; the federal government invokes the War Measures Act, its only peacetime use in history."
          },
          {
            date: "May 20, 1980",
            title: "First Quebec referendum",
            description: "Quebecers reject, by 59.56% to 40.44%, the mandate to negotiate sovereignty-association proposed by the Parti Québécois government."
          },
          {
            date: "April 17, 1982",
            title: "Patriation of the Constitution",
            description: "The Constitution Act, 1982, including the Canadian Charter of Rights and Freedoms, ends the need for the British Parliament's consent to amend the Constitution; the Quebec government refuses to endorse it."
          },
          {
            date: "October 30, 1995",
            title: "Second Quebec referendum",
            description: "The No side narrowly wins, with 50.58% of the vote against 49.42% for Quebec sovereignty, on a record turnout of 93.52%."
          },
          {
            date: "April 1, 1999",
            title: "Creation of Nunavut",
            description: "This new, mainly Inuit territory is separated from the Northwest Territories following the 1993 Nunavut Land Claims Agreement."
          }
        ]
      },
      {
        title: "Reconciliation and contemporary Canada",
        summary: "From the 1830s until the last institutions closed in the late 1990s, some 150,000 First Nations, Métis and Inuit children were placed, often by force, in one of about 140 residential schools run jointly by the federal government and Christian churches, with the stated aim of assimilating Indigenous children into Canadian society. The Truth and Reconciliation Commission, created in 2008 as part of the largest class action settlement in the country's history, documented in its 2015 final report the deaths of at least 4,100 children — a figure its chair considered a large underestimate, possibly exceeding 6,000 — and described the system as \"cultural genocide\". Since 2021, the discovery by First Nations using ground-penetrating radar of large numbers of ground anomalies consistent with unmarked graves at former residential school sites has renewed public attention to this legacy. In another sphere, in 2025 the country went through an unprecedented political and trade rupture with the United States, which imposed tariffs and whose president publicly floated annexing Canada as the \"51st state\"; Mark Carney became Prime Minister in March 2025 in this context.",
        events: [
          {
            date: "June 11, 2008",
            title: "Official apology for residential schools",
            description: "Prime Minister Stephen Harper delivers an official apology in the House of Commons on behalf of the federal government for the residential school system."
          },
          {
            date: "2015",
            title: "Final report of the Truth and Reconciliation Commission",
            description: "The Commission publishes its findings and 94 calls to action to advance reconciliation between Canada and Indigenous peoples."
          },
          {
            date: "May 2021",
            title: "Anomalies detected in Kamloops",
            description: "The Tk'emlúps te Secwépemc First Nation announces the detection, by ground-penetrating radar, of hundreds of ground anomalies consistent with unmarked graves at the site of the former Kamloops residential school (British Columbia)."
          },
          {
            date: "March 14, 2025",
            title: "Mark Carney becomes Prime Minister",
            description: "The former governor of the Bank of Canada and the Bank of England succeeds Justin Trudeau as leader of the Liberal Party and head of the federal government."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Sport",
        title: "Ice hockey, the national winter sport",
        description: "Born in the 19th century in the British North American provinces, ice hockey has officially been Canada's national winter sport since a 1994 law, which also made lacrosse the national summer sport. The National Hockey League (NHL), founded in Montreal in 1917, is still followed fervently across the country.",
        examples: [
          "Stanley Cup",
          "National Hockey League",
          "Lacrosse"
        ]
      },
      {
        category: "Identity",
        title: "Multiculturalism, official policy since 1971",
        description: "In 1971 Canada became the first country in the world to adopt an official policy of multiculturalism, enshrined in 1988 in the Canadian Multiculturalism Act and then in the Canadian Charter of Rights and Freedoms. This approach, distinct from the French model of assimilation, encourages people to keep their cultural identities of origin within Canadian society."
      },
      {
        category: "Food",
        title: "Maple syrup and poutine",
        description: "The world's leading producer of maple syrup, with Quebec alone supplying most of the world's output, Canada also saw the birth of poutine (fries, cheese curds and brown gravy) in rural Quebec in the 1950s, now an iconic dish well beyond the province.",
        examples: [
          "Maple syrup",
          "Poutine",
          "Tourtière",
          "Butter tart"
        ]
      },
      {
        category: "Arts and literature",
        title: "The Group of Seven and Inuit art",
        description: "The Group of Seven, a collective of landscape painters active in the 1920s, strongly shaped Canada's visual identity with its depictions of the Canadian Shield and the vast northern spaces. Inuit sculpture and printmaking, notably from the Cape Dorset co-operative (Nunavut) founded in the late 1950s, are internationally recognised."
      },
      {
        category: "Natural heritage",
        title: "A vast network of national parks",
        description: "Banff National Park, created in 1885 in the Alberta Rockies, is Canada's oldest national park and one of the first in the world. The Parks Canada network now includes dozens of national parks and historic sites in every province and territory.",
        examples: [
          "Banff National Park",
          "Jasper National Park",
          "Niagara Falls"
        ]
      },
      {
        category: "Music and performing arts",
        title: "Cirque du Soleil and the Quebec music scene",
        description: "Founded in Baie-Saint-Paul (Quebec) in 1984 by former street performers, Cirque du Soleil has become the largest contemporary circus company in the world, present on every continent. French-speaking Quebec also has its own music industry and star system, distinct from the English-language scene in the rest of the country."
      }
    ]
  },
  territories: {
    summary: "Canada is a federation of ten provinces, which have their own constitutional powers, and three territories (Yukon, Northwest Territories, Nunavut), whose powers are delegated by the federal government. Unlike France, Canada has no non-contiguous or overseas territory: the whole country forms a single continental block, extended to the north by its Arctic Archipelago.",
    divisions: [
      {
        name: "Provinces"
      },
      {
        name: "Territories",
        note: "Yukon, Northwest Territories and Nunavut."
      }
    ],
    metropolitanRegions: PROVINCES_AND_TERRITORIES,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "Share of renewables in final energy consumption; electricity itself is largely decarbonised, with hydroelectricity alone supplying about 60%."
    },
    co2PerCapita: {
      note: "Among the highest of the developed countries, due to oil sands extraction, long travel distances and a harsh climate requiring heavy heating."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Nuclear share of electricity",
        value: {
          note: "National figure; nuclear power is in fact heavily concentrated in Ontario, where it supplies more than half of the province's electricity (53% in 2022), generated by 16 of the country's 17 commercial reactors. All Canadian reactors are of the CANDU design, a pressurised heavy-water technology developed in Canada that can run on natural, unenriched uranium."
        }
      }
    ],
    risks: [
      "Large-scale wildfires",
      "Spring floods",
      "Permafrost thaw in the Far North",
      "Ice storms and harsh winters"
    ],
    summary: "With electricity generation dominated by hydroelectricity and complemented by a nuclear fleet concentrated in Ontario, Canada's electricity mix is largely decarbonised, but CO2 emissions per capita remain among the highest of the developed countries because of oil and gas production, especially from the Alberta oil sands. The country is increasingly exposed to major wildfires, as in the record 2023 season, and to accelerating permafrost thaw in the Canadian Arctic, which threatens the infrastructure and ways of life of northern communities."
  },
  keyFacts: [
    {
      title: "A capital that is not the largest city",
      description: "Ottawa, chosen by Queen Victoria in 1857 as a compromise between Toronto and Montreal, is the federal capital, while Toronto, far more populous, remains the country's largest city and main economic centre."
    },
    {
      title: "The longest coastline in the world",
      description: "With 243,042 km of coastline along three oceans (Atlantic, Pacific and Arctic), Canada has the longest national coastline in the world."
    },
    {
      title: "Two official languages since 1969",
      description: "The Official Languages Act makes English and French the two official languages of the federal government, an institutional bilingualism unique among the major English-speaking powers."
    },
    {
      title: "A Canadian-designed nuclear reactor",
      description: "The CANDU, a pressurised heavy-water reactor developed in Canada, can run on natural, unenriched uranium; it supplies about 13% of the country's electricity, more than 50% of it in Ontario."
    },
    {
      title: "Quebec has twice rejected sovereignty",
      description: "The referendums of 1980 (59.56% No) and 1995 (50.58% No, a margin of just 54,288 votes) both saw Quebecers choose to remain in the Canadian federation."
    },
    {
      title: "A painful past with Indigenous peoples",
      description: "Some 150,000 Indigenous children went through the residential school system (1830s–1990s); in 2015 the Truth and Reconciliation Commission documented the deaths of at least 4,100 of them and described the system as \"cultural genocide\"."
    }
  ],
  cities: [
    {
      name: "Toronto",
      population: {
        note: "Census metropolitan area (CMA)."
      }
    },
    {
      name: "Montreal",
      population: {
        note: "CMA; the largest majority French-speaking city in North America."
      }
    },
    {
      name: "Vancouver",
      population: {
        note: "CMA."
      }
    },
    {
      name: "Ottawa",
      population: {
        note: "Ottawa–Gatineau CMA."
      }
    },
    {
      name: "Calgary",
      population: {
        note: "CMA."
      }
    },
    {
      name: "Edmonton",
      population: {
        note: "CMA."
      }
    },
    {
      name: "Quebec City",
      population: {
        note: "CMA; capital of the province of Quebec."
      }
    },
    {
      name: "Winnipeg",
      population: {
        note: "CMA."
      }
    }
  ],
  rivers: [
    {
      name: "St. Lawrence River",
      lengthKm: {
        note: "Including the Great Lakes basin, of which it is the outlet; about 1,200 km for the river alone between Lake Ontario and the gulf."
      },
      source_location: "Lake Ontario, at Kingston (Ontario)",
      mouth: "Gulf of St. Lawrence (Atlantic Ocean), in Quebec"
    },
    {
      name: "Mackenzie",
      lengthKm: {
        note: "Including the Finlay–Peace–Athabasca–Great Slave Lake system; Canada's longest river system."
      },
      source_location: "Thutade Lake, northern British Columbia (via the Finlay–Peace River system)",
      mouth: "Beaufort Sea (Arctic Ocean), in the Mackenzie Delta"
    },
    {
      name: "Fraser",
      source_location: "Fraser Pass, Rocky Mountains (British Columbia)",
      mouth: "Strait of Georgia (Pacific Ocean), near Vancouver"
    },
    {
      name: "Churchill",
      source_location: "Churchill Lake, northern Saskatchewan",
      mouth: "Hudson Bay, at Churchill (Manitoba)"
    },
    {
      name: "Nelson",
      lengthKm: {
        note: "About 2,570 km including the North Saskatchewan River basin, its ultimate source."
      },
      source_location: "Lake Winnipeg, at Warren Landing (Manitoba)",
      mouth: "Hudson Bay, near Port Nelson (Manitoba)"
    }
  ],
  regions: PROVINCES_AND_TERRITORIES,
  sources: {
    "Gouvernement du Canada": "Government of Canada",
    "Gouvernement du Canada — Relations Couronne-Autochtones et Affaires du Nord Canada": "Government of Canada — Crown-Indigenous Relations and Northern Affairs Canada",
    "Ministère de la Justice du Canada": "Department of Justice Canada",
    "Parcs Canada": "Parks Canada",
    "Ressources naturelles Canada": "Natural Resources Canada",
    "Ressources naturelles Canada / Wikipedia": "Natural Resources Canada / Wikipedia",
    "Statistique Canada": "Statistics Canada",
    "Statistique Canada (recensement de 2021)": "Statistics Canada (2021 Census)",
    "Wikipedia (démographie du Canada)": "Wikipedia (demographics of Canada)",
    "Wikipedia (géographie du Canada)": "Wikipedia (geography of Canada)",
    "Wikipedia, citant les données de la Régie de l'énergie du Canada (REC)": "Wikipedia, citing Canada Energy Regulator (CER) data"
  }
};
