import type { CountryTranslation } from "@/lib/i18n/translation";

const URBAN_AREA_NOTE = "Built-up area; the ONS has not republished an equivalent since the 2021 census.";
const NATIONS = [{ name: "England" }, { name: "Scotland" }, { name: "Wales" }, { name: "Northern Ireland" }];

/** English translation of data/royaume-uni — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "3854b63aa9cd",
  capital: "London",
  geography: {
    headline: "An island archipelago in north-western Europe",
    areaKm2: {
      note: "Land area."
    },
    highestPoint: {
      name: "Ben Nevis"
    },
    borderingCountries: [
      "Ireland"
    ],
    climate: "Temperate oceanic climate, with mild winters, cool summers and frequent rainfall throughout the year; harsher and wetter in the uplands of the north and west.",
    summary: "The United Kingdom covers most of the British Isles: Great Britain (England, Scotland, Wales) and the north-eastern part of the island of Ireland (Northern Ireland). Its terrain combines plains in the south and east with uplands and mountains in Scotland, Wales and northern England."
  },
  population: {
    total: {
      note: "Mid-2025 estimate, confirmed by the World Bank."
    },
    density: {
      note: "Derived value, not published directly by a single source."
    },
    summary: "With 69.5 million inhabitants, the United Kingdom is one of the most populous countries in Europe. The population is heavily concentrated in south-east England, around London, and in the large industrial conurbations of the Midlands and the North (Manchester, Birmingham, Leeds)."
  },
  languages: {
    entries: [
      {
        name: "English",
        note: "De facto language of government and public life throughout the country."
      },
      {
        name: "Welsh",
        note: "Co-official in Wales, where its use is protected by the Welsh Language Measure (2011)."
      },
      {
        name: "Scottish Gaelic",
        note: "Recognised and promoted in Scotland, especially in the Hebrides, under the aegis of Bòrd na Gàidhlig."
      },
      {
        name: "Irish, Scots, Cornish, Manx",
        note: "Regional/minority languages recognised to varying degrees in Northern Ireland, Scotland, Cornwall and the Isle of Man."
      }
    ],
    summary: "English is the predominant language throughout the United Kingdom. Welsh is co-official in Wales; Scottish Gaelic, Irish, Scots, Cornish and Manx enjoy varying degrees of recognition and institutional support depending on the constituent nation."
  },
  religion: {
    surveyName: "2021 Census (England and Wales)",
    ageScope: "Entire resident population",
    points: [
      {
        label: "Christian"
      },
      {
        label: "No religion"
      },
      {
        label: "Muslim"
      },
      {
        label: "Hindu"
      },
      {
        label: "Other religions"
      },
      {
        label: "Not stated"
      }
    ],
    summary: "According to the 2021 census, 46.2% of the population of England and Wales identify as Christian and 37.2% as having no religion — a sharp rise in the share of people with no religion compared with previous censuses.",
    methodologyNote: "These figures cover England and Wales only: Scotland and Northern Ireland run their own censuses, with separate results not included here. The religion question was voluntary (94% response rate)."
  },
  politics: {
    stateForm: "Constitutional monarchy",
    regime: "Parliamentary monarchy",
    headOfState: {
      title: "King",
      name: "Charles III",
      since: "September 8, 2022"
    },
    headOfGovernment: {
      title: "Prime Minister",
      name: "Andy Burnham",
      since: "July 20, 2026"
    },
    legislature: {
      name: "Parliament",
      chambers: [
        {
          name: "House of Commons"
        },
        {
          name: "House of Lords"
        }
      ]
    },
    constitution: {
      adopted: "Uncodified — a customary constitution based on a body of statutes, conventions and case law"
    },
    summary: "The United Kingdom is a constitutional monarchy without a single written constitution: the King is head of state, with a largely ceremonial role, while the Prime Minister, accountable to the House of Commons, leads the government."
  },
  economy: {
    currency: {
      name: "Pound sterling"
    },
    gdp: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    gdpPerCapita: {
      note: "Current US dollars — for a consistent comparison between countries."
    },
    unemploymentRate: {
      note: "April to June 2026."
    },
    sectors: [],
    indicators: [],
    summary: "The United Kingdom is one of the world's major economies, driven by a highly developed service sector — finance (the City of London), insurance, consulting, the creative industries — alongside a smaller industrial base than in the 20th century that remains significant (aerospace, pharmaceuticals, automotive)."
  },
  history: {
    intro: "A few milestones to place the major stages in the country's formation and transformation — not an exhaustive summary of its history.",
    periods: [
      {
        title: "Formation of the kingdom",
        summary: "The Norman Conquest of 1066 refounded the Kingdom of England, which gradually united with Wales before the Union of the Crowns of England and Scotland in 1603.",
        events: [
          {
            date: "1066",
            title: "Norman Conquest",
            description: "William the Conqueror seizes the English throne after the Battle of Hastings."
          },
          {
            date: "1215",
            title: "Magna Carta",
            description: "The Great Charter limits royal power for the first time and lays the foundations of English constitutional law."
          }
        ]
      },
      {
        title: "Union of the kingdoms",
        summary: "The Act of Union of 1707 merged England and Scotland into a Kingdom of Great Britain, joined by Ireland in 1801, as the country became the world's leading industrial and imperial power.",
        events: [
          {
            date: "1707",
            title: "Act of Union with Scotland",
            description: "England and Scotland merge into a single Kingdom of Great Britain."
          },
          {
            date: "1801",
            title: "Act of Union with Ireland",
            description: "The Kingdom of Great Britain and the Kingdom of Ireland merge to form the United Kingdom of Great Britain and Ireland."
          }
        ]
      },
      {
        title: "20th century",
        summary: "Two world wars, the independence of southern Ireland in 1922 and decolonisation profoundly transformed the country and its empire, while the welfare state was built after 1945.",
        events: [
          {
            date: "1922",
            title: "Independence of the Irish Free State",
            description: "Most of Ireland becomes independent; six northern counties remain within the United Kingdom as Northern Ireland."
          },
          {
            date: "1948",
            title: "Creation of the National Health Service",
            description: "The NHS establishes a public health system free at the point of use, a pillar of Britain's post-war welfare state."
          },
          {
            date: "1997 – 1998",
            title: "Devolution",
            description: "Creation of the Scottish Parliament, the Welsh Assembly and the Northern Ireland Assembly, each given powers of its own."
          }
        ]
      },
      {
        title: "Today",
        summary: "The 1998 Good Friday Agreement ended the Northern Ireland conflict; the country left the European Union following the 2016 referendum, effective in 2020.",
        events: [
          {
            date: "April 10, 1998",
            title: "Good Friday Agreement",
            description: "A peace agreement ending three decades of conflict in Northern Ireland."
          },
          {
            date: "June 23, 2016",
            title: "Brexit referendum",
            description: "51.9% of voters choose to leave the European Union."
          },
          {
            date: "January 31, 2020",
            title: "Exit from the European Union",
            description: "The United Kingdom officially leaves the European Union."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list, and without claiming to sum up the real diversity of people's habits.",
    items: [
      {
        category: "Sport",
        title: "Football, born in England",
        description: "The modern rules of football were codified in London in 1863 with the founding of the Football Association, the oldest football association in the world.",
        examples: [
          "Premier League",
          "FA Cup"
        ]
      },
      {
        category: "Food",
        title: "Afternoon tea",
        description: "The ritual of afternoon tea, popularised in the 19th century, remains a social practice associated with the country, alongside a cuisine diversified by immigration.",
        examples: [
          "Fish and chips",
          "Sunday roast",
          "Curry (very widely adopted)"
        ]
      },
      {
        category: "Music",
        title: "A worldwide musical influence",
        description: "From the Beatles to the punk, Britpop and electronic scenes, the United Kingdom has had a lasting influence on popular music worldwide since the 1960s.",
        examples: [
          "The Beatles",
          "Glastonbury Festival"
        ]
      },
      {
        category: "Heritage",
        title: "35 World Heritage sites",
        description: "The United Kingdom and its overseas territories have 35 properties inscribed on the UNESCO World Heritage List.",
        examples: [
          "Stonehenge",
          "Tower of London",
          "Old and New Towns of Edinburgh"
        ]
      }
    ]
  },
  territories: {
    summary: "The United Kingdom is made up of four constituent nations (England, Scotland, Wales, Northern Ireland) and retains sovereignty over 14 British Overseas Territories, remnants of the British Empire, which are distinct from the Crown Dependencies (Channel Islands, Isle of Man).",
    divisions: [
      {
        name: "Constituent nations"
      },
      {
        name: "British Overseas Territories"
      }
    ],
    metropolitanRegions: NATIONS,
    overseas: [
      {
        name: "Gibraltar",
        status: "British Overseas Territory"
      },
      {
        name: "Bermuda",
        status: "British Overseas Territory"
      },
      {
        name: "Cayman Islands",
        status: "British Overseas Territory"
      },
      {
        name: "Falkland Islands",
        status: "British Overseas Territory"
      }
    ]
  },
  environment: {
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Nuclear share of electricity"
      }
    ],
    risks: [
      "Floods",
      "Coastal erosion",
      "Storms",
      "Heatwaves"
    ],
    summary: "The United Kingdom has sharply reduced its CO2 emissions per capita thanks to the decline of coal in electricity generation, but remains one of the least forested countries in Europe and highly exposed to flooding and coastal erosion."
  },
  keyFacts: [
    {
      title: "No single written constitution",
      description: "The United Kingdom is one of the few democracies in the world without a single, codified constitutional text: its constitutional law rests on statutes, conventions and case law accumulated over centuries."
    },
    {
      title: "14 overseas territories across the globe",
      description: "From Gibraltar to the Falkland Islands and the British Antarctic Territory, these territories are the last direct remnants of the British Empire."
    },
    {
      title: "Driving on the left",
      description: "The United Kingdom is one of the countries where traffic drives on the left, a custom inherited from medieval traditions that survived even as the rest of continental Europe standardised on the right."
    }
  ],
  cities: [
    {
      name: "London",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Manchester",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Birmingham",
      population: {
        note: `West Midlands built-up area; ${URBAN_AREA_NOTE.charAt(0).toLowerCase()}${URBAN_AREA_NOTE.slice(1)}`
      }
    },
    {
      name: "Glasgow",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Liverpool",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Sheffield",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Bristol",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Edinburgh",
      population: {
        note: URBAN_AREA_NOTE
      }
    },
    {
      name: "Cardiff",
      population: {
        note: URBAN_AREA_NOTE
      }
    }
  ],
  rivers: [
    {
      name: "Severn",
      lengthKm: {
        note: "The longest river in the United Kingdom."
      },
      source_location: "Plynlimon, Powys (Wales)",
      mouth: "Severn Estuary, Bristol Channel"
    },
    {
      name: "Thames",
      source_location: "Thames Head, Gloucestershire",
      mouth: "Thames Estuary, North Sea"
    }
  ],
  regions: NATIONS,
  sources: {
    "British Council": "British Council",
    "Calculé (population ONS ÷ superficie Banque mondiale)": "Calculated (ONS population ÷ World Bank area)",
    "DESNZ (Digest of UK Energy Statistics)": "DESNZ (Digest of UK Energy Statistics)",
    "Donnée non disponible.": "Data not available.",
    "Environment Agency (GOV.UK)": "Environment Agency (GOV.UK)",
    "Historic UK": "Historic UK",
    ONS: "ONS",
    "ONS — Recensement 2011": "ONS — 2011 Census",
    "Office for National Statistics (ONS)": "Office for National Statistics (ONS)",
    "Ordnance Survey": "Ordnance Survey",
    "The Football Association": "The Football Association",
    "UK Parliament": "UK Parliament",
    "Wikipedia (infobox géographique)": "Wikipedia (geography infobox)",
    "gov.uk": "gov.uk"
  }
};
