import type { CountryTranslation } from "@/lib/i18n/translation";

const STATES = [
  "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo",
  "Ekiti", "Enugu", "Federal Capital Territory", "Gombe", "Imo", "Jigawa", "Kaduna", "Kebbi", "Kano", "Kogi", "Katsina",
  "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara",
].map((name) => ({ name }));

/** English translation of data/nigeria — generated by scripts/i18n/extract-translation.ts, then translated. */
export const en: CountryTranslation = {
  sourceHash: "9b2a89ec26ef",
  capital: "Abuja",
  geography: {
    headline: "Africa's most populous country, between the tropical Atlantic coast and the Sahelian savannahs",
    highestPoint: {
      name: "Chappal Waddi"
    },
    borderingCountries: [
      "Benin",
      "Niger",
      "Chad",
      "Cameroon"
    ],
    climate: "The climate gets hotter and drier from south to north: tropical monsoon climate and equatorial forest on the coast and in the Niger Delta, tropical savannah with contrasting seasons on the central plateaus, then a semi-arid Sahelian climate in the far north, where the dry season can last eight months. The harmattan, a hot, dust-laden wind from the Sahara, blows across the whole country from November to March.",
    summary: "With 923,769 km², Nigeria is one of the large countries of West Africa, bordered by the Gulf of Guinea along some 853 km of coastline and crossed from north to south by the Niger River, which joins its main tributary, the Benue, at Lokoja before forming the vast Niger Delta on the Atlantic coast. The terrain, generally modest, rises towards the east to the country's highest point, Chappal Waddi (2,419 m), in the highlands on the border with Cameroon."
  },
  population: {
    total: {
      note: "Estimate; the last full general census dates from 2006 (140.4 million inhabitants), as the results of a census conducted in late 2023 have not been published. Nigeria is the most populous country in Africa and the 6th in the world."
    },
    medianAge: {
      note: "One of the youngest populations in the world: more than half of Nigerians are under 15."
    },
    summary: "Driven by one of the highest population growth rates in the world, Nigeria has passed 230 million inhabitants and, according to United Nations projections, should become the third most populous country on the planet by mid-century, behind India and China. Its extremely young population is concentrated in a few megacities — first among them Lagos, one of the most dynamic and populous urban areas in Africa — and in the densely populated farming belt of the south-east and Yorubaland, while the semi-arid north, although also very populous (Kano), is generally less dense."
  },
  languages: {
    entries: [
      {
        name: "English",
        note: "The sole official language of the federal state, inherited from British colonisation; the language of government, higher education and the national media."
      },
      {
        name: "Hausa",
        sharePercent: {
          note: "Estimate; spoken as a first or second language, including as a lingua franca across much of the north."
        },
        note: "Recognised by the Constitution as a language that may be used in the National Assembly; dominant in the north and across the West African Sahel beyond Nigeria's borders."
      },
      {
        name: "Yoruba",
        sharePercent: {
          note: "Estimate."
        },
        note: "Language of the south-west, also recognised by the Constitution for use in the National Assembly."
      },
      {
        name: "Igbo",
        sharePercent: {
          note: "Estimate."
        },
        note: "Language of the south-east (the former Eastern Region, heartland of Biafra in 1967–1970), also recognised for use in the National Assembly."
      },
      {
        name: "Nigerian Pidgin",
        note: "An English-based creole, the country's most widespread informal lingua franca, used in everyday life and increasingly in the media (BBC Pidgin) and music, although without official status."
      },
      {
        name: "Other Niger-Congo and Chadic languages",
        note: "Nigeria has more than 500 recorded living languages (Fulfulde/Fula, Kanuri, Ijaw, Tiv, Ibibio, Edo...), one of the highest levels of linguistic diversity in the world."
      }
    ],
    summary: "Only English is official at federal level, a choice inherited from the colonial period to unify administratively a country of exceptional linguistic diversity: more than 500 languages are recorded there, making it one of the most multilingual countries in the world. Three languages nevertheless dominate by number of speakers and enjoy special constitutional recognition (they may be used in the National Assembly): Hausa in the mainly Muslim north, Yoruba in the south-west and Igbo in the south-east. Nigerian Pidgin, an English-based creole born in the port and oil areas, has become the country's real inter-ethnic vernacular, spoken daily by tens of millions of people without official status."
  },
  religion: {
    surveyName: "Pew Research Center estimate (Global Religious Landscape)",
    ageScope: "Total population, estimate",
    points: [
      {
        label: "Muslim"
      },
      {
        label: "Christian"
      },
      {
        label: "Other / traditional religions"
      }
    ],
    summary: "Nigeria is roughly evenly split between Muslims and Christians, a division that closely follows the country's geography: Islam, mainly Sunni with large Sufi brotherhoods (Tijaniyya, Qadiriyya), overwhelmingly dominates the north and the Nigerian Sahel, while Christianity (Catholic and above all Protestant, especially fast-growing evangelical and Pentecostal churches) dominates the south. The Middle Belt, in the centre of the country, is the most mixed contact zone, where Muslims, Christians and followers of local traditional religions coexist (the latter often combined with one of the two major religions rather than practised alone). Nigeria is thus both one of the countries with the most Muslims and one of those with the most Christians in the world.",
    methodologyNote: "The 1963 census was the last to ask the question (about 47% Muslims and 34% Christians): religion and ethnicity have since been removed from censuses, considered too sensitive in a country where the north–south balance determines the distribution of federal power. Current estimates come from surveys (Pew Research Center, Afrobarometer, DHS) and range from about 51 to 58% Muslim depending on the methodology."
  },
  politics: {
    stateForm: "Federal republic",
    regime: "Presidential system",
    headOfState: {
      title: "President of the Federal Republic of Nigeria",
      name: "Bola Ahmed Tinubu",
      since: "May 29, 2023"
    },
    headOfGovernment: {
      title: "President of the Federal Republic of Nigeria",
      name: "Bola Ahmed Tinubu",
      since: "May 29, 2023"
    },
    legislature: {
      name: "National Assembly",
      chambers: [
        {
          name: "House of Representatives"
        },
        {
          name: "Senate"
        }
      ]
    },
    constitution: {
      adopted: "May 29, 1999"
    },
    summary: "Nigeria is a federal republic with a presidential system: as in the United States or Brazil, the president is both head of state and head of government, is elected by direct universal suffrage for a four-year term renewable once, and is not accountable to the National Assembly. Legislative power belongs to a bicameral National Assembly (Senate and House of Representatives), and the 36 states, as well as the Federal Capital Territory (Abuja), each have their own governor and legislative assembly. The 1999 Constitution, the product of a transition steered by the outgoing junta, established the \"Fourth Republic\"."
  },
  economy: {
    currency: {
      name: "Naira"
    },
    gdp: {
      note: "Current US dollars; sharply down since 2022 (nearly 650 billion USD), a direct consequence of the naira's devaluation after the currency was floated in June 2023, rather than a contraction of the real economy."
    },
    gdpPerCapita: {
      note: "Current US dollars; one of the lowest among the major African economies despite the overall size of Nigeria's GDP, which reflects the country's demographic weight rather than its average wealth per person."
    },
    unemploymentRate: {
      note: "Of limited relevance: the National Bureau of Statistics' new methodology (2023–2024) caused the official rate to plunge (more than 33% under the old definition in 2020), while underemployment and informal work remain massive."
    },
    sectors: [
      {
        name: "Services"
      },
      {
        name: "Agriculture"
      },
      {
        name: "Industry"
      }
    ],
    indicators: [
      {
        label: "Oil's share of government revenue",
        value: {
          value: "about 2/3 of federal government revenue",
          note: "Oil accounts for only about 9% of GDP, but provides the overwhelming majority of export earnings, which makes the economy highly sensitive to crude prices."
        }
      },
      {
        label: "Inflation",
        value: {
          note: "After peaking above 30% in 2024, in the wake of the naira float and the removal of fuel subsidies."
        }
      }
    ],
    summary: "Africa's largest oil producer and a member of OPEC, Nigeria draws most of its export and budget revenue from Niger Delta crude, while its GDP is dominated by services and agriculture, which still employs a large share of the workforce. Since 2023, Bola Tinubu has removed fuel subsidies and floated the naira, ending decades of managed exchange rates: inflation soared and GDP in dollars collapsed. The country remains marked by mass poverty, a wide gap between an industrialised south and a rural north, and dependence on imports of refined fuel, for lack of functioning public refineries."
  },
  history: {
    intro: "A few milestones to place the major stages in the building of the modern country — not an exhaustive summary of Nigerian history.",
    periods: [
      {
        title: "From the Lagos colony to colonial amalgamation",
        summary: "The United Kingdom annexed Lagos in 1861 and then took control of the interior, divided in 1900 into Northern and Southern protectorates. In 1914 Frederick Lugard merged them, mainly for budgetary reasons, despite their deep religious and cultural differences — a decision that still weighs on the north–south balance. Independence came on October 1, 1960.",
        events: [
          {
            date: "January 1, 1914",
            title: "Amalgamation of the Northern and Southern protectorates",
            description: "Frederick Lugard merges the two protectorates and the Lagos colony into a single colony, British Nigeria."
          },
          {
            date: "October 1, 1960",
            title: "Independence of Nigeria",
            description: "A parliamentary system, with Abubakar Tafawa Balewa as Prime Minister."
          }
        ]
      },
      {
        title: "The First Republic and its fall",
        summary: "Built on a fragile coalition of regionally and ethnically based parties (Hausa-Fulani North, Yoruba West, Igbo East), the regime was undermined by tensions and disputed elections, until the coup of January 1966.",
        events: [
          {
            date: "October 1, 1963",
            title: "Proclamation of the Republic",
            description: "Nigeria becomes a republic within the Commonwealth; Nnamdi Azikiwe is its first president."
          },
          {
            date: "January 15, 1966",
            title: "First military coup",
            description: "Officers overthrow the government and kill Abubakar Tafawa Balewa; General Johnson Aguiyi-Ironsi takes power."
          }
        ]
      },
      {
        title: "Counter-coup, pogroms and the Biafran civil war",
        summary: "The counter-coup of July 1966 brought Yakubu Gowon to power; anti-Igbo pogroms in the North killed tens of thousands and drove more than a million Igbo to flee east. In 1967 that region seceded as Biafra. The ensuing war, until 1970, killed from several hundred thousand to two or three million people, mostly civilians starved by the federal blockade.",
        events: [
          {
            date: "May 30, 1967",
            title: "Proclamation of the Republic of Biafra",
            description: "Colonel Odumegwu Ojukwu declares the independence of the mainly Igbo Eastern Region."
          },
          {
            date: "July 6, 1967 – January 15, 1970",
            title: "Biafran civil war",
            description: "The conflict ends with Biafra's surrender and reintegration into Nigeria."
          }
        ]
      },
      {
        title: "Three decades dominated by military regimes",
        summary: "Coups and generals followed one another, apart from the civilian interlude of the Second Republic (1979–1983). Ibrahim Babangida annulled the 1993 election; Sani Abacha then imposed a repressive regime until his death in 1998, which paved the way for a return to civilian rule.",
        events: [
          {
            date: "December 31, 1983",
            title: "Muhammadu Buhari's coup",
            description: "General Muhammadu Buhari overthrows the civilian government of the Second Republic."
          },
          {
            date: "June 12, 1993",
            title: "Annulment of the presidential election",
            description: "Babangida annuls the vote, widely considered to have been won by Moshood Abiola."
          },
          {
            date: "June 1998",
            title: "Death of General Sani Abacha",
            description: "His successor Abdulsalami Abubakar organises a rapid transition to civilian rule."
          }
        ]
      },
      {
        title: "The Fourth Republic and the Boko Haram insurgency",
        summary: "Since 1999 the country has had its longest period of civilian government, with changes of power through the ballot box, including the first defeat of a sitting president in 2015. Since 2009, the Boko Haram and ISWAP insurgency in the north-east has caused about 350,000 deaths, direct and indirect, and displaced more than 2.4 million people.",
        events: [
          {
            date: "May 29, 1999",
            title: "Return to civilian rule",
            description: "Olusegun Obasanjo is sworn in as president under the 1999 Constitution."
          },
          {
            date: "2009",
            title: "Start of the Boko Haram insurgency",
            description: "The group takes up arms after the bloody crackdown on its founder Mohammed Yusuf."
          },
          {
            date: "April 14-15, 2014",
            title: "Chibok schoolgirls kidnapping",
            description: "Boko Haram abducts 276 schoolgirls; ten years later, 82 were still missing."
          },
          {
            date: "May 29, 2023",
            title: "Inauguration of Bola Tinubu",
            description: "Bola Ahmed Tinubu becomes president following the February 2023 election."
          }
        ]
      }
    ]
  },
  culture: {
    intro: "An overview of documented cultural practices — not an exhaustive list.",
    items: [
      {
        category: "Cinema",
        title: "Nollywood, one of the world's top film industries by volume",
        description: "Born in the 1990s from very low-cost direct-to-video production, Nollywood ranks, according to UNESCO, among the world's leading film industries by number of films, behind Bollywood. It has professionalised and exports across Africa and its diaspora."
      },
      {
        category: "Music",
        title: "From Fela Kuti's Afrobeat to global Afrobeats",
        description: "Afrobeat, a fusion of jazz, funk and Yoruba rhythms, was popularised in the 1970s by Fela Kuti, an outspoken opponent of the military regimes. The country is today one of the birthplaces of Afrobeats, a distinct genre carried internationally by Burna Boy, Wizkid and Davido.",
        examples: [
          "Fela Kuti",
          "Burna Boy",
          "Wizkid",
          "Davido"
        ]
      },
      {
        category: "Literature",
        title: "Wole Soyinka, Africa's first Nobel laureate in literature",
        description: "Wole Soyinka received the Nobel Prize in Literature in 1986, the first African laureate. Chinua Achebe's novel \"Things Fall Apart\" (1958), about the clash between Igbo society and colonisation, is one of the most widely read African works in the world.",
        examples: [
          "Wole Soyinka",
          "Chinua Achebe, Things Fall Apart",
          "Chimamanda Ngozi Adichie"
        ]
      },
      {
        category: "Heritage",
        title: "Nok terracottas and the Benin Bronzes",
        description: "The Nok culture, which emerged around 1500 BC, left the oldest known figurative sculptures in sub-Saharan Africa. The Kingdom of Benin (unrelated to the neighbouring state) produced bronzes from the 13th century onwards, largely looted by the British in 1897 and whose restitution remains debated."
      },
      {
        category: "Food",
        title: "Jollof rice, suya and egusi soup",
        description: "Nigerian cuisine combines spiced rice (jollof rice, a dish disputed with Ghana), grilled skewers (suya) and soups made from melon seeds (egusi), served with pounded yam or fufu.",
        examples: [
          "Jollof rice",
          "Suya",
          "Egusi soup",
          "Pounded yam"
        ]
      }
    ]
  },
  territories: {
    summary: "Nigeria is a federation of 36 states, plus the Federal Capital Territory (Abuja, the capital since 1991). Each state is in turn subdivided into Local Government Areas (LGAs), the basic tier of Nigerian administration, numbering 774 nationwide. Nigeria has no overseas territory.",
    divisions: [
      {
        name: "States"
      },
      {
        name: "Federal Capital Territory",
        note: "Abuja, the country's capital since 1991."
      },
      {
        name: "Local Government Areas (LGAs)",
        note: "The basic administrative tier, spread across the 36 states and the Federal Capital Territory."
      }
    ],
    metropolitanRegions: STATES,
    overseas: []
  },
  environment: {
    renewableShare: {
      note: "A misleading figure: it mainly reflects households' reliance on firewood and charcoal, for lack of widespread access to electricity; the electricity mix remains dominated by natural gas and hydropower."
    },
    co2PerCapita: {
      note: "Among the lowest in the world relative to population, because of still-limited access to electricity and industrialisation — not to be confused with the emissions and gas flaring linked to oil extraction, concentrated in the Niger Delta."
    },
    indicators: [
      {
        label: "Forest cover"
      },
      {
        label: "Access to electricity"
      }
    ],
    risks: [
      "Oil pollution and environmental degradation of the Niger Delta",
      "Desertification and the advance of the Sahara in the north, worsened by droughts",
      "Coastal erosion and seasonal flooding, especially around Lagos and the delta",
      "Deforestation driven by demand for firewood and agricultural expansion"
    ],
    summary: "The Niger Delta, the historic oil-producing region, is one of the most polluted areas in the world: several tens of millions of litres of hydrocarbons were spilled in Ogoniland alone between 2006 and 2019 according to local records, not counting massive gas flaring. This pollution fuelled the demands of the non-violent MOSOP movement, whose spokesman Ken Saro-Wiwa was executed by the military regime in 1995, and then the armed militancy of MEND until the 2009 amnesty. Elsewhere, the desert is advancing in the north and erosion threatens the coastline, especially around Lagos."
  },
  keyFacts: [
    {
      title: "A capital moved in 1991",
      description: "Congested and off-centre, Lagos handed its status as capital to Abuja, a planned city in the centre of the country, on December 12, 1991."
    },
    {
      title: "Africa's demographic giant",
      description: "With more than 230 million inhabitants, Nigeria is the most populous country in Africa and the 6th in the world; according to the UN, it should become the 3rd by 2050, behind India and China."
    },
    {
      title: "No religious census since 1963",
      description: "To avoid reviving tensions over the north–south balance, the 1991 and 2006 censuses excluded any question on religion or ethnicity."
    },
    {
      title: "Nollywood, a prolific film industry",
      description: "With several thousand films a year, often on very small budgets, Nollywood is among the world's leading film industries by volume."
    },
    {
      title: "Oil funds the state without sustaining the economy",
      description: "Oil accounts for only about 9% of GDP but provides nearly two-thirds of federal government revenue, which therefore depends on crude prices."
    },
    {
      title: "Ten years after their abduction, schoolgirls still missing",
      description: "Boko Haram abducted 276 schoolgirls in Chibok in April 2014; in April 2024, 82 were still missing."
    }
  ],
  cities: [
    {
      name: "Lagos",
      population: {
        note: "Population of the urban area at the last reliable national census; current estimates, hotly disputed between Lagos State and the federal administration in the absence of a new census, range from 11 to more than 20 million inhabitants for Greater Lagos."
      }
    },
    {
      name: "Abuja",
      population: {
        note: "A planned new city that became the federal capital in 1991; its urban area was estimated at more than 3.7 million inhabitants in 2022 according to population projections, in the absence of a more recent census."
      }
    },
    {
      name: "Kano",
      population: {
        note: "The country's 2nd city and the main urban centre of the Muslim north."
      }
    },
    {
      name: "Ibadan",
      population: {
        note: "The largest city in Yorubaland by historical area."
      }
    },
    {
      name: "Port Harcourt",
      population: {
        note: "The main urban and port centre of the Niger Delta, heart of Nigeria's oil industry."
      }
    }
  ],
  rivers: [
    {
      name: "Niger",
      lengthKm: {
        note: "Africa's 3rd-longest river, which gives the country its name; much of its lower course, down to its vast delta on the Gulf of Guinea, lies in Nigerian territory."
      },
      source_location: "Loma Mountains, in Guinea",
      mouth: "Niger Delta, Gulf of Guinea (Atlantic Ocean)"
    },
    {
      name: "Benue",
      lengthKm: {
        note: "The Niger's main tributary, which it joins at Lokoja."
      },
      source_location: "Adamawa Plateau, in Cameroon",
      mouth: "Confluence with the Niger, at Lokoja (Nigeria)"
    },
    {
      name: "Kaduna",
      source_location: "Jos Plateau (Plateau State, Nigeria)",
      mouth: "Confluence with the Niger, south of Bida"
    },
    {
      name: "Cross River",
      source_location: "Cameroon highlands",
      mouth: "Gulf of Guinea (Bight of Biafra), between Oron and Calabar"
    }
  ],
  regions: STATES,
  sources: {
    "Assemblée nationale du Nigeria": "National Assembly of Nigeria",
    "Bureau national de statistique du Nigeria (NBS)": "National Bureau of Statistics of Nigeria (NBS)",
    "Division de la population des Nations unies": "United Nations Population Division",
    "Division de la population des Nations unies (ONU)": "United Nations Population Division (UN)",
    Ethnologue: "Ethnologue",
    "Recensement national du Nigeria (NPC)": "National Population Census of Nigeria (NPC)",
    "State House (présidence du Nigeria)": "State House (Presidency of Nigeria)",
    "Wikipedia (Economy of Nigeria)": "Wikipedia (Economy of Nigeria)"
  },
  units: {
    "% (glissement annuel, avril 2026)": "% (year on year, April 2026)"
  }
};
